### ISSUE TITLE
table样式与浏览器展现不一致

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/mp-html#193]
[提示]: tbale带入了 align=‘center’属性后，与浏览器展现不一致，请问怎么样解决呢？

**使用平台**  

[提示]: <微信> 

![image](https://user-images.githubusercontent.com/21222276/92079715-f6ff0c80-edf2-11ea-8432-b3a733137333.png)
![image](https://user-images.githubusercontent.com/21222276/92079745-054d2880-edf3-11ea-8990-7b2717e58c23.png)

**html 代码**  

```
读一读，填空。<br /><tab>&nbsp;</tab>​明明写作业时遇到了一个难题，就到班级论坛上发布了一个求助问题：遇到不理解的词语时，该怎样做？同学们看到了，纷纷留言讨论起来，请你也参与进来，帮他们完善一下吧。<table border='1' align='center' cellspacing='0' cellpadding='0' style='width: 450px;'><tbody><tr><td>求助：遇到不理解的词语时，该怎样做？<br />一楼：我遇到不理解的词语时，通常会<fill>&nbsp;</fill>解决，因为字典中有词语的各种解释，我从中选出合适的一项就可以了。<br />二楼：我会通过<fill>&nbsp;</fill>来理解，根据它前后的句子就能推断出词语的意思。<br />三楼：我会用<fill>&nbsp;</fill>来理解，比如&ldquo;敬爱&rdquo;中的&ldquo;敬&rdquo;是尊敬的意思，&ldquo;爱&rdquo;是热爱的意思，&ldquo;敬爱&rdquo;就是尊敬热爱的意思。</td></tr></tbody></table>​

```

**Comment by 45221378** [comment]
感谢，问题已经修复。

**Comment by 45221378** [comment]
html代码
`
根据加、减法各部分间的关系，写出另外两个等式。​<table border='1' cellspacing='0' cellpadding='0' style='width: 293px;'><tbody><tr><td rowspan='2' colspan='1' style='width: 2px;'><span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2svg/a8e543b37723cc401d1f0caf97d5eee7.svg'/></span></td><td style='width: 161px;'> </td></tr><tr><td style='width: 161px;'> </td></tr><tr><td rowspan='2' colspan='1' style='width: 2px;'><span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2svg/7649314e85838a15cee8bb30043f1dd7.svg'/></span></td><td style='width: 161px;'> </td></tr><tr><td style='width: 161px;'> </td></tr></tbody></table>
`
富文本编辑器插件生成的html代码。此段代码自动在td 里面带入了' style='width: 2px;' 导致小程序无法解析。但是用浏览器解析没有问题，用rich-text 也可以解析出来，但是用parser后，就解析不出来了，麻烦帮忙看下怎么处理呢？

**Comment by jin-yufeng** [comment]
这个问题主要是因为移动端图片很容易超出屏幕大小，所以组件内部给所有 `img` 都加了 `max-width:100%`，然后遇上这里设置了 `width:2px` 就没了，这个问题还挺麻烦的，直接把 `max-width` 去掉也不合适，可能带来更多问题

**Comment by 45221378** [comment]
能给点思路吗？这边暂时想不到好的办法 把它显示出来。
