### ISSUE TITLE
如果保留标签的自定义属性

### ISSUE THREAD

**Issue by Lkx2217** [jin-yufeng/mp-html#211]
比如有一段富文本是 <div data-jump=""></div>

在解析的时候如何保留 data-jump 这个自定义的属性，我看 dom 里所有自定义的属性全部消失了

**Comment by Lkx2217** [comment]
&lt;div  data-jump=""&gt;&lt;/div&gt;

**Comment by jin-yufeng** [comment]
为减小解析结果大小，默认会去除所有 `data-`  的属性，暂时可以改 [这里](https://github.com/jin-yufeng/Parser/blob/master/parser/libs/MpHtmlParser.js#L79)
