### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by SouthernPenguin** [jin-yufeng/mp-html#212]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信小程序
[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  
在使用Parser时，点击图片预览后，在页面中又出次发了一次请求
[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
提供能复现的 `demo` 项目
