### ISSUE TITLE
设置

### ISSUE THREAD

**Issue by xlkit456852** [jin-yufeng/mp-html#213]
**使用平台**  

百度小程序

**问题描述**  

想设置富文本文本的默认字体大小为28.8rpx，但是无法生效。在tagStyle中试过    
p : "font-size:28.8rpx"
view : "font-size:28.8rpx"
'rich-text': "font-size:28.8rpx"
这三种方式，均无法设置，请问应该如何设置呢？

** 代码**  

tagStyle:{
	p : "font-size:28.8rpx"
},

**Comment by jin-yufeng** [comment]
直接在 `parser` 标签的 `style` 属性里加 `font-size:28.8rpx`  
`tag-style` 可能不支持 `rpx`
