### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by FFFZZZ** [jin-yufeng/mp-html#214]
是否可以传入格式化好的node节点

**Comment by jin-yufeng** [comment]
以前的版本曾经试过可以传入 `string` 或解析好的 `array`  
但是有一些问题，本组件内部的 `node` 格式和 `rich-text` 并不完全一致，本组件并不是递归显示所有节点（这样会有很多的递归节点，效率较差），对于节点下没有图片、链接等特殊标签的，会直接通过 `rich-text` 标签显示，要实现这一功能就必须在解析过程中做标记（哪些节点要继续递归），另外对于 `rich-text` 不支持的标签和属性还要进行特定的转换  
因此，除非是用本组件的解析脚本产生的 `node`（事实上大部分后台都不用 `js`，而且有一些操作必须要在前端完成，比如 `rich-text` 标签内部不支持 `rpx`，要使用 `rpx` 就必须在解析的时候根据屏幕宽度手动转换），对传入的 `array` 还要进行二次转换，增加了处理复杂度，再加上一般来说转为 `array` 后大小比 `string` 要大，会增加网络传输的时间，这样一来能达到的优化效果就有限了，所以后来统一成只能传入 `string` 了
