### ISSUE TITLE
空白换行在微信小程序中不显示

### ISSUE THREAD

**Issue by willswu** [jin-yufeng/mp-html#223]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
`html` 里换行要用 `br` 标签

**Comment by guxiaowei** [comment]
![image](https://user-images.githubusercontent.com/22518288/100705621-7bf1c600-33e2-11eb-9e97-a45c6d0e4dbb.png)
实现不了类似于上面的换行，红框里的是parse解析出来的结果

**Comment by jin-yufeng** [comment]
> ![image](https://user-images.githubusercontent.com/22518288/100705621-7bf1c600-33e2-11eb-9e97-a45c6d0e4dbb.png)
> 实现不了类似于上面的换行，红框里的是parse解析出来的结果

这段的 `html` 是什么，放在浏览器里有没有换行
