### ISSUE TITLE
table富文本格式不正确

### ISSUE THREAD

**Issue by xiao-qiangLn** [jin-yufeng/mp-html#227]
**使用平台**  
微信小程序
**问题描述**  
使用插件在小程序中显示不正确
![image](https://user-images.githubusercontent.com/49442060/101514802-a500f080-39b8-11eb-9d3c-ea6988166562.png)

**html 代码**  
```html
<table cellpadding="0" cellspacing="1" width="100%" border="0" class="Ptable"><tr><th class="tdTitle" colspan="2">型号信息</th><tr><tr><td class="tdTitle">品牌</td><td>普联（TP-LINK）</td></tr><tr><td class="tdTitle">型号</td><td>TL-R473G</td></tr><tr><td class="tdTitle">认证型号</td><td>TL-R473G</td></tr><tr><th class="tdTitle" colspan="2">基本信息</th><tr><tr><td class="tdTitle">尺寸（mm）</td><td>209(w)x126(D)x26(H) mm</td></tr><tr><td class="tdTitle">重量（kg）</td><td>以实物为准</td></tr><tr><td class="tdTitle">机身材质分类</td><td>金属机身</td></tr><tr><td class="tdTitle">适用面积</td><td>大户型（90-120㎡）</td></tr><tr><td class="tdTitle">使用-场景</td><td>企业办公</td></tr><tr><th class="tdTitle" colspan="2">规格信息</th><tr><tr><td class="tdTitle">WAN接入口</td><td>千兆网口</td></tr><tr><td class="tdTitle">LAN输出口</td><td>千兆网口</td></tr><tr><td class="tdTitle">无线协议</td><td>无</td></tr><tr><td class="tdTitle">处理器</td><td>其他</td></tr><tr><th class="tdTitle" colspan="2">属性信息</th><tr><tr><td class="tdTitle">工作温度</td><td>0℃～40℃</td></tr><tr><td class="tdTitle">存储温度</td><td>-40℃～70℃</td></tr></table>
```

**Comment by xiao-qiangLn** [comment]
’<table cellpadding="0" cellspacing="1" width="100%" border="0" class="Ptable"><tr><th class="tdTitle" colspan="2">主体</th><tr><tr><td class="tdTitle">系列</td><td>联想-天逸510Pro</td></tr><tr><td class="tdTitle">型号</td><td>510Pro</td></tr><tr><td class="tdTitle">推荐用途</td><td>商用电脑</td></tr><tr><td class="tdTitle">平台</td><td>Intel平台</td></tr><tr><td class="tdTitle">操作系统</td><td>Win10家庭中文版</td></tr><tr><td class="tdTitle">机箱类型</td><td>大机箱</td></tr><tr><th class="tdTitle" colspan="2">主板</th><tr><tr><td class="tdTitle">芯片组</td><td>其它</td></tr><tr><td class="tdTitle">网卡</td><td>无线网卡</td></tr><tr><th class="tdTitle" colspan="2">CPU</th><tr><tr><td class="tdTitle">类型</td><td>酷睿</td></tr><tr><td class="tdTitle">CPU型号</td><td>Intel酷睿六核处理器i5-8400</td></tr><tr><td class="tdTitle">速度</td><td>处理器基本频率 2.8GHz</td></tr><tr><td class="tdTitle">核心数</td><td>六核</td></tr><tr><th class="tdTitle" colspan="2">显卡</th><tr><tr><td class="tdTitle">显示芯片</td><td>NVIDIA GT730</td></tr><tr><td class="tdTitle">显存容量</td><td>独立2GB</td></tr><tr><td class="tdTitle">显存规格</td><td>DDR5</td></tr><tr><th class="tdTitle" colspan="2">内存</th><tr><tr><td class="tdTitle">容量</td><td>8GB</td></tr><tr><td class="tdTitle">速度</td><td>其他</td></tr><tr><td class="tdTitle">插槽数量</td><td>2个</td></tr><tr><td class="tdTitle">最大支持容量</td><td>32GB</td></tr><tr><th class="tdTitle" colspan="2">硬盘</th><tr><tr><td class="tdTitle">容量</td><td>1TB</td></tr><tr><td class="tdTitle">转速</td><td>7200转/分钟</td></tr><tr><th class="tdTitle" colspan="2">显示器</th><tr><tr><td class="tdTitle">宽屏</td><td>是</td></tr><tr><th class="tdTitle" colspan="2">输入设备</th><tr><tr><td class="tdTitle">鼠标</td><td>有线鼠标</td></tr><tr><td class="tdTitle">键盘</td><td>有线键盘</td></tr><tr><th class="tdTitle" colspan="2">前(侧)面接口</th><tr><tr><td class="tdTitle">USB</td><td>4</td></tr><tr><th class="tdTitle" colspan="2">后面接口</th><tr><tr><td class="tdTitle">视频接口</td><td>VGA\HDMI接口</td></tr><tr><td class="tdTitle">USB</td><td>4</td></tr><tr><td class="tdTitle">RJ45</td><td>10/100/1000 LAN (rear)</td></tr><tr><th class="tdTitle" colspan="2">扩展性</th><tr><tr><td class="tdTitle">PCI-E</td><td>2 (1 for combo wifi&BT, another for SSD)</td></tr><tr><th class="tdTitle" colspan="2">规格</th><tr><tr><td class="tdTitle">电源</td><td>180W ES电源</td></tr><tr><td class="tdTitle">尺寸</td><td>324.5mm(L) X 165mm(W) X 376mm(H)</td></tr><tr><th class="tdTitle" colspan="2">特性</th><tr><tr><td class="tdTitle">特性</td><td> 三年有限保修及三年上门服务 /正版Office家庭和学生版 2016/WiFi/蓝牙</td></tr></table>‘

**Comment by jin-yufeng** [comment]
![微信截图_20201209155028](https://user-images.githubusercontent.com/48236054/101600505-598d2780-3a36-11eb-9b48-aac0035a82a3.png)
这里好几个 `tr` 的结束标签都少了 `/`，浏览器应该是能自动纠错，插件里的解析还不能

**Comment by xiao-qiangLn** [comment]
嗯，发现了；多谢
