### ISSUE TITLE
图片添加链接之后，没有触发点击事件

### ISSUE THREAD

**Issue by xiaochenggit** [jin-yufeng/mp-html#229]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信
[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  

[提示]: <> (请详细描述遇到的问题，最好附上截图)  
![image](https://user-images.githubusercontent.com/17794871/101736912-1480f800-3aff-11eb-8954-44c4d7981748.png)
在您示例小程序也发现了同样的问题
**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
暂时可以把 `trees.wxml` 里图片的 `catchtap` 改成 `bindtap` 来解决

**Comment by jin-yufeng** [comment]
已修复
