### ISSUE TITLE
ios 兼容性问题

### ISSUE THREAD

**Issue by Hooks7** [jin-yufeng/mp-html#234]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信小程序

**问题描述**  
ios上无法长按复制  长按图片时和预览图片冲突

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

> 
![image](https://user-images.githubusercontent.com/52195679/102447511-0a18ae00-406b-11eb-8c78-e6b8fba874ac.png)

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
无法复制是已知问题而且目前无法解决 #187
至于预览和长按冲突每次都会吗？可以放一个 `image` 同时绑定 `bindtap` 和 `show-menu-by-longpress` 试试会不会同时触发

**Comment by Hooks7** [comment]
每次都会，长按之后松手会触发图片点击事件

**Comment by Hooks7** [comment]
@jin-yufeng 每次都会，长按结束后会继续触发图片点击事件，仅在ios上

**Comment by jin-yufeng** [comment]
直接放一个 `image` 也会同时触发吗？

**Comment by Hooks7** [comment]
@jin-yufeng  是的

**Comment by jin-yufeng** [comment]
那要向官方反馈啊

**Comment by jin-yufeng** [comment]
给图片绑定了 `longpress`，长按应该不会触发 `tap` 了

**Comment by Hooks7** [comment]
@jin-yufeng 谢谢大佬，刚试了没有问题了

**Comment by Hooks7** [comment]
@jin-yufeng 大佬我想问下，你是如何在image没有预览情况下，长按图片可以调用操作菜单的（发送好友。）

**Comment by jin-yufeng** [comment]
[image](https://developers.weixin.qq.com/miniprogram/dev/component/image.html) 有一个属性 `show-menu-by-longpress`，设置为 `true` 就有了

**Comment by Hooks7** [comment]
@jin-yufeng 感谢
