### ISSUE TITLE
富文本中包含多个video时互斥

### ISSUE THREAD

**Issue by AbnerZS** [jin-yufeng/mp-html#237]
**新功能描述**  
如果富文本中包含多个video时是否支持之前播放的video停止或者暂停, 当前的播放
[提示]: <> (描述需要的功能或改进建议)  

**应用场景**  
富文本中包含多个video标签时
[提示]: <> (描述该新功能的应用场景)

**Comment by jin-yufeng** [comment]
默认就是这样吧，可以通过 `autopause` 属性关闭

**Comment by AbnerZS** [comment]
小程序video组件没有这个属性

**Comment by jin-yufeng** [comment]
我是说本组件已经有这个功能和这个属性 [组件属性](https://jin-yufeng.gitee.io/parser/#/instructions?id=%e7%bb%84%e4%bb%b6%e5%b1%9e%e6%80%a7)
