### ISSUE TITLE
文本中含有无法解析的图片时，文章加载时间过长

### ISSUE THREAD

**Issue by cary-hu** [jin-yufeng/mp-html#238]
**使用平台**  

微信

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  

加载一个包含有无法打开的图片时，页面加载时间过长。
![image](https://user-images.githubusercontent.com/41052104/103145365-31aafd00-4774-11eb-9532-8997cb9e71b0.png)

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html
that.selectComponent("#article").setContent(data.Content);
```

**Comment by jin-yufeng** [comment]
是内容本身太长了吧？就放一张图会很慢？

**Comment by cary-hu** [comment]
相同的内容，不含图片，加载速度还可以，有哪个加载不出来的图片， 就会卡，直到控制台报图片加载错误的提示，文字才被加载出来

**Comment by jin-yufeng** [comment]
提供能复现的 `demo` 项目

**Comment by cary-hu** [comment]
我刚才写了一个测试的Demo，发现确实是setContent过大，导致的加载慢，请问有什么优化的方法嘛？

**Comment by jin-yufeng** [comment]
内容多了肯定会变慢的，最好是分页吧，每页显示一部分
一定要放在一起的话也可以分多次设置，后面调用 `setContent` 的时候将第二个参数设置为 `true` 即可在尾部追加，不过这样只能让一开始显示的快一点，无法解决总标签数过多的问题
