### ISSUE TITLE
grid布局处理表格的一些问题

### ISSUE THREAD

**Issue by xhlgr** [jin-yufeng/mp-html#239]
## 使用环境  
微信小程序

## 问题描述
如果不考虑改变原始html内容的情况下，有如下问题：
- html有合并行列的表格中的图片没有设置width或width大于屏幕宽度时，图片没有被处理，显示时依次是原图宽度或设置的width宽度。希望能统一被程序处理成表格或者上一级的宽度100%显示。
- 如果表格的td有设置宽度，会被转换成在单元格中的百分比，而不是表格宽度的百分比。希望在处理表格后保留原来表格的列宽。没有合并行列有链接的表格使用display:table好像也没有保留原列宽。

## 复现方式
- 代码片段 https://developers.weixin.qq.com/s/N2mmSUmX7Kmn

**Comment by jin-yufeng** [comment]
现在应该可以了，试试 https://developers.weixin.qq.com/s/VqNm3Umg7Omy

**Comment by xhlgr** [comment]
列宽可以了。
另外，src/miniprogram/parser.js的第386行：`if (i == -1) {`可能是`if (i == 1) {`才会将图片加入imgList?

**Comment by jin-yufeng** [comment]
是 `-1`
上面的循环如果正常结束，`i` 的值就是 `-1`，这时就会加入 `imgList`
不正常的结束就是 `361` 行如果父级中有 `a` 标签或 `table` 标签，此时不加入 `imgList`
`a` 标签是因为链接内有图片的时候只响应链接的点击，图片不可预览，因此不加入 `imgList`
`table` 标签一个是因为表格内的图片通常是不太重要的小图片，不太需要放大预览；另外，如果要将 `table` 中的图片暴露出来进行预览（不用 `rich-text`），需要转为 `table` 布局或 `grid` 布局，这个方案应用于链接效果还不错，但是图片某些情况下还是有问题（比如 #194，用 `table` 标签就没有问题，转为 `table` 布局就有问题），所以表格里的图片也禁用预览了

**Comment by xhlgr** [comment]
原来如此，谢谢

**Comment by jin-yufeng** [comment]
#194 我找到办法解决了，那 `table` 里的图片也可以预览了
