### ISSUE TITLE
打开了editable插件后没有渲染

### ISSUE THREAD

**Issue by golden-mountain** [jin-yufeng/mp-html#241]
## 使用环境  
MAC OS 

## 问题描述  
mp-html 自己编译后不能显示出来

## 复现方式  

1.  按照官方文档， 打开了插件的editable并编译成功
编译命令： npm run build:mp-weixin

![image](https://user-images.githubusercontent.com/12361133/103203058-1a643f00-492f-11eb-8cf7-d027979213f4.png)

![image](https://user-images.githubusercontent.com/12361133/103203112-31a32c80-492f-11eb-8166-1b2c13e385dc.png)

2. 使用在微信小程序中
```
 "parser": "mp-weixin/index",
```

```
<parser html="{{info.content}}"></parser>
```

3. 没有任何显示 
![image](https://user-images.githubusercontent.com/12361133/103203490-010fc280-4930-11eb-8d09-27aee0b20151.png)

4. 去掉插件， 重新编译，也没有任何显示

**Comment by jin-yufeng** [comment]
`html` 属性更名为 `content` 了，可以参考 [更新指南](https://jin-yufeng.gitee.io/mp-html/#/changelog/changelog?id=v200)，另外引入 `editable` 后，还需要给组件设置 `editable` 属性才可编辑，[文档](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=editable) 里有示例项目可以试一下

**Comment by golden-mountain** [comment]
谢谢， 可以了！
