### ISSUE TITLE
mpvue怎么使用

### ISSUE THREAD

**Issue by zyghhhh** [jin-yufeng/mp-html#243]
更新后mpvue怎么使用呢

**Comment by jin-yufeng** [comment]
使用方法和原来没什么变化吧
`mpvue` 官方文档里没找到如何引入原生自定义组件的内容，可以参考一下 [网上的教程](https://blog.csdn.net/pengjunlee/article/details/100018939)，大概就是这样：
1. 拷贝 [dist/mp-weixin](https://github.com/jin-yufeng/mp-html/tree/master/dist/mp-weixin) 到 `static` 目录下，更名为 `mp-html`  
2. 在需要使用页面的文件夹下添加 `main.json`  

   ```json
   {
     "usingComponents": {
       "mp-html": "../../static/mp-html/index"
     }
   }
   ```
3. 在需要使用页面文件夹下的 `index.vue` 里添加  
 
   ```vue
   <template>
     <view>
       <mp-html :content="html" />
     </view>
   </template>
   <script>
   export default {
     data() {
       return {
         html: ''
       }
     },
     onLoad() {
       this.html = '<div>Hello World!</div>'
     }
   }
   </script>
    ```
