### ISSUE TITLE
在子组件slot中使用mp-html，无法被解析

### ISSUE THREAD

**Issue by zst-steven** [jin-yufeng/mp-html#244]
子组件接收父组件的slot来显示HTML的内容无法解析。
父组件：
`<parent>
  <view slot="content">{{html}}</view>
</parent>
`
子组件：
`<child>
     <view>
        <slot name="content">
          <mp-html content="{{content}}" />
      </slot>
    </view>
</child>
`

**Comment by jin-yufeng** [comment]
标签原样显示多半是因为传入的 `html` 被转义了，参考 [标签原样显示](https://jin-yufeng.gitee.io/mp-html/#/question/faq?id=entity)
如果不是的请提供能复现的 `demo` 项目
