### ISSUE TITLE
Taro微信小程序图片渲染失败

### ISSUE THREAD

**Issue by ief820** [jin-yufeng/mp-html#248]

**Comment by jin-yufeng** [comment]
500 说明图片链接有问题啊

**Comment by ief820** [comment]
> 500 说明图片链接有问题啊

但是这个图片我在editor  富文本编辑里可以打开，   而且我自己云存储的图片也是500  无法打开

**Comment by ief820** [comment]
> 是的
> 可以先把你的 `html` 放在原生框架的 [示例项目](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=demo) 中试一下正不正常，如果也不正常，请提供你的 `html`
> 如果在原生框架正常的话，可能是引入出了问题吧，可以提供一个能复现的 `taro` `demo` 项目

https://github.com/ief820/test_taro_mphtml.git
新建了一个taro工程，用源码方式引入dist目录下的mp-wexin  放入src下， 
引入：
 usingComponents: {
      'mp-html': '../../mp-html/index' // 书写第三方组件的相对路径
    }

使用：

<mp-html content={content} />

content为示例项目中的content

在小程序中显示只有文字，没有样式和图片

**Comment by jin-yufeng** [comment]
我检查了一下，这个问题是这样的，源码里是这样的
![1](https://user-images.githubusercontent.com/48236054/103765652-7a0dc900-5058-11eb-950b-3ea1a75ea0c2.png)

然后构建组件包的时候经过 `uglify` 压缩，变成了这样
![2](https://user-images.githubusercontent.com/48236054/103766009-07e9b400-5059-11eb-9467-4b68a219a704.png)

一些语句被放在了 `void` 里，然后再被 `taro` 编译了一次
![3](https://user-images.githubusercontent.com/48236054/103765762-b2ada280-5058-11eb-8b87-8531dedb1bc7.png)
`void(xxx)` 直接变成了 `undefined`，中间的语句没有了，所以就出问题了

暂时的解决办法是用非压缩版的（[示例项目](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=demo) 里的就是非压缩版的），反正 `taro` 编译后也会压缩的
`taro 3.x` 是没有这个问题的

**Comment by jin-yufeng** [comment]
下个版本改成这样就没有问题了
![微信截图_20210106212527](https://user-images.githubusercontent.com/48236054/103773250-b693f180-5065-11eb-959b-6946640d37bd.png)

**Comment by ief820** [comment]
非常感谢您这么快速的支持，修复  ，问题解决了
