### ISSUE TITLE
不支持预览base64格式图片

### ISSUE THREAD

**Issue by dyy2016** [jin-yufeng/mp-html#249]
## 使用环境  
taro

## 问题描述  
将从服务端获取的图片二进制流转base64显示出来了，但是点图片没反应

**Comment by jin-yufeng** [comment]
这个目前设计上就是这个样子，主要有以下几个原因：  
1. `base64` 一般只用于几个 `KB` 的小图片，这种小图片一般不需要放大预览（小程序环境下要通过 `setData` 将数据送到视图层，`base64` 要是大了更容易影响性能）  
2. `previewImage` 和长按保存等基本都不支持 `base64`，所以即使预览了基本也无法使用  
这个问题之前有一个解决办法是通过 `FileSystemManager.writeFile` 把 `base64` 写到本地文件里再预览，组件卸载的时候再清理掉缓存；这样虽然可行，但一个是增加了复杂度，另外有些时候组件的 `detached` 周期不一定会执行（比如首页或者直接被关掉），这样容易造成缓存堆积，所以还是去掉了

**Comment by dyy2016** [comment]
> 这个目前设计上就是这个样子，主要有以下几个原因：
> 
> 1. `base64` 一般只用于几个 `KB` 的小图片，这种小图片一般不需要放大预览（小程序环境下要通过 `setData` 将数据送到视图层，`base64` 要是大了更容易影响性能）
> 2. `previewImage` 和长按保存等基本都不支持 `base64`，所以即使预览了基本也无法使用
>    这个问题之前有一个解决办法是通过 `FileSystemManager.writeFile` 把 `base64` 写到本地文件里再预览，组件卸载的时候再清理掉缓存；这样虽然可行，但一个是增加了复杂度，另外有些时候组件的 `detached` 周期不一定会执行（比如首页或者直接被关掉），这样容易造成缓存堆积，所以还是去掉了

感谢您的回复，还有一个问题，我如果不想图片自适应，就显示图片的原大小，怎么处理

**Comment by jin-yufeng** [comment]
是说不要限制图片的最大宽度吗？因为很多图片原始大小都会超出屏幕大小，所以组件默认给所有图片加了 `max-width:100%`，不需要的话可以去掉以下两个地方：  
1. [parser.js](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/parser.js#L414)  
2. [node/node.wxss](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/node/node.wxss#L16)  

`dist` 目录可以对应着找一下位置

**Comment by dyy2016** [comment]
> 是说不要限制图片的最大宽度吗？因为很多图片原始大小都会超出屏幕大小，所以组件默认给所有图片加了 `max-width:100%`，不需要的话可以去掉以下两个地方：
> 
> 1. [parser.js](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/parser.js#L414)
> 2. [node/node.wxss](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/node/node.wxss#L16)
> 
> `dist` 目录可以对应着找一下位置

用的是mp-html/dist/mp-weixin下的文件，没您说的这两行代码

**Comment by jin-yufeng** [comment]
`dist` 目录下是压缩后的，只有一行，可以搜索一下 `max-width`  
或者在 `src` 目录下修改，然后构建到 `dist` 目录  
```bash
npm install
npm run build:weixin
```

**Comment by dyy2016** [comment]
> `dist` 目录下是压缩后的，只有一行，可以搜索一下 `max-width`
> 或者在 `src` 目录下修改，然后构建到 `dist` 目录
> 
> ```shell
> npm install
> npm run build:weixin
> ```

删了您刚说的两个地方，重新构建，宽度还是100%

**Comment by jin-yufeng** [comment]
提供 `html` 内容或能复现的 `demo` 项目

**Comment by dyy2016** [comment]
> 提供 `html` 内容或能复现的 `demo` 项目

http://note.youdao.com/s/KwcxR6pC

**Comment by dyy2016** [comment]
> > 提供 `html` 内容或能复现的 `demo` 项目
> 
> http://note.youdao.com/s/KwcxR6pC

**Comment by jin-yufeng** [comment]
没有复现你说的问题
[demo.zip](https://github.com/jin-yufeng/mp-html/files/5776790/demo.zip)

![微信截图_20210106235617](https://user-images.githubusercontent.com/48236054/103789297-ccf87800-507a-11eb-834a-05b5ad73c444.png)

**Comment by dyy2016** [comment]
> 没有复现你说的问题
> [demo.zip](https://github.com/jin-yufeng/mp-html/files/5776790/demo.zip)
> 
> ![微信截图_20210106235617](https://user-images.githubusercontent.com/48236054/103789297-ccf87800-507a-11eb-834a-05b5ad73c444.png)

非常感谢大神的耐心回复，已经解决，我这面文件引用的问题
