### ISSUE TITLE
在uni-app上使用，微信小程序懒加载不起作用

### ISSUE THREAD

**Issue by yeyifen** [jin-yufeng/mp-html#250]
## 使用环境  

微信小程序版本  2.13.0

## 问题描述  
加载类似以下代码：
```
<p><img src="xxx" /></p>
<p><img src="xxx" /></p>
<p><img src="xxx" /></p>
```

图片懒加载不起效果，图片高度起码有4-5屏的高度，调用的代码为
```
<mp-html loading-img="xxx" error-img="xxx" lazy-load :preview-img="false" :content="configuration" class="detail_content" />
```
其中configuration就是上面的富文本内容，在开发工具上看，生成的代码的class是重复的，还有undefined，不知道跟这个有没关系
![image](https://user-images.githubusercontent.com/19640756/103986684-23260200-51c6-11eb-9e75-74b6092d4b0e.png)

## 复现方式  

已更新为最新的代码，还是无法使用，看起来图片上也没加上 lazy-load的属性

**Comment by jin-yufeng** [comment]
看 #118

**Comment by yeyifen** [comment]
下滑过程没有再加载了，看了下网络请求，都是一次性全加载进来了

**Comment by jin-yufeng** [comment]
示例项目里是可以的
你这个问题应该是因为内容全是图片，图片在没加载的时候大小会被设置成 `1x1`，加载完再恢复成原大小，所以一开始所有图片都是 `1×1`，都在视图范围内，所以都加载了，如果有一些其他内容就不会这样
至于为什么没加载时设置成 `1×1` 而不是按照 `image` 默认的 `320×240`，一个是因为预设了这样一个大小，加载过程中图片会变形（缩放到预设大小，加载慢的时候比较明显），加载完后又恢复正常，还有有一些图比这个预设的大小小，会出现加载完突然缩回去的现象，影响体验，所以预设的很小，加载完再恢复正常（网页里没加载的图片也是没有大小的）
要解决的话可以试试以下方案：
1. 通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性给 `p` 标签设置一个 `min-height`
2. 给 `node/node.vue` 中 `style` 里的 `._img` 加一个 `min-height` 或去掉 `template` 里的 `height:1px`
3. 设置 [loading-img](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=loading-img) 属性在加载过程中占位（下个版本可以，现在还有问题）

**Comment by yeyifen** [comment]
拷贝了最新的src里的uni-app到项目里，尝试 1 直接通过正则替换给p加上min-height：cont.replace(/<p/gi, `<p style="min-height:500px;"`)

**Comment by jin-yufeng** [comment]
提供能复现的 `demo` 项目
