### ISSUE TITLE
大佬,H5 图片好像如果默认设置了高度的会变形.

### ISSUE THREAD

**Issue by Y-A-K-E** [jin-yufeng/mp-html#253]
## 问题描述  
```
<p>
<img src="//r.photo.store.qq.com/psc?/V13iVwZo2obvUj/r5r.jW0JZFmFKdRYe5qoxgQ*nPkPfi3MjrVyu0jz6gxS6kgHKqUjf4WIPtZjzr1Ld26s4dV8*txdW0SDRypZ0wBiopixOuSk72nTEf7qe*Y!/mnull&amp;bo=DwWAAl0GJQMBCds!&amp;rf=photolist&amp;t=5/r/_yake_qzoneimgout.png" 
alt="" width="1629" height="805" />
</p>
```

我网站后台插入图片会自动计算长宽插入代码中.
像我这种指定了长高的,图片会变形.  

![QQ截图20210118133206](https://user-images.githubusercontent.com/6988291/104876295-659fc980-5992-11eb-8f5b-26d8501d1b1d.jpg)

浏览器中隐藏图片默认的高度样式才正常.

![QQ截图20210118134001](https://user-images.githubusercontent.com/6988291/104876489-bfa08f00-5992-11eb-94f9-270ee0cb07d5.jpg)

**Comment by jin-yufeng** [comment]
开手机调试模式试一下？
解析的时候如果图片设置的宽度超过了窗口宽度，会自动把 `height` 去掉的
![微信截图_20210118154234](https://user-images.githubusercontent.com/48236054/104885924-cedc0880-59a3-11eb-9073-9c107abe051f.png)

**Comment by Y-A-K-E** [comment]
手机版式是正常的,只有宽PC版式才会有此问题.

(不知道将原来自带的宽高样式加max前缀会不会解决)

**Comment by jin-yufeng** [comment]
宽度被 `max-width:100%` 限制，高度不变导致了变形吧
可以通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性给 `img` 加一个 `height: auto`

**Comment by Y-A-K-E** [comment]
可以,有效果.谢谢.
