### ISSUE TITLE
插件 editable 是否支持修改字体颜色，添加删除线，下划线

### ISSUE THREAD

**Issue by moshanghan** [jin-yufeng/mp-html#254]
## 问题描述  

插件 editable 是否支持修改字体颜色，添加删除线，下划线等
我想这个应该是富文本编辑器基本的功能，然而翻阅文档，没有找到相关资料，所以有此一问。
感谢
再次感谢作者提供此插件

**Comment by jin-yufeng** [comment]
你说的这些通通都没有哈哈哈，有的都写在 [文档](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=editable) 上了
移动端一般只做一些简单的编辑，所以功能上比较简单
修改字体颜色可能要用到调色盘什么的，比较麻烦
删除线下划线倒是不难，只是现在的操作菜单已经差不多满一行了，再加要分行，需要调整调整样式
大家需要的多的话可以再添加一下

**Comment by moshanghan** [comment]
感谢及时反馈
