### ISSUE TITLE
PC端富文本table标签没有border属性，但是可以显示表格线，移动端没有border属性，就无法显示表格线，建议优化解析富文本的时候做一下判断

### ISSUE THREAD

**Issue by AcmanHu** [jin-yufeng/mp-html#255]
PC端是这样解析的
![image](https://user-images.githubusercontent.com/45252510/105117629-c6044780-5b07-11eb-87bd-adecdd8f206a.png)
本插件是这样
![image](https://user-images.githubusercontent.com/45252510/105117733-fb109a00-5b07-11eb-9e1a-ed88d26d580f.png)
关键HTML
![image](https://user-images.githubusercontent.com/45252510/105117913-53479c00-5b08-11eb-8534-51002213eb5b.png)
手动改成 <table width="100%" border="1" cellspacing="0" cellpadding="5" style="border-collapse: collapse;">

**Comment by jin-yufeng** [comment]
这是你的编辑器自带的样式给表格加了边框吧，把这段 `html` 放到浏览器里也是没有边框的，`table` 默认不带边框
可以通过以下方法加上边框：
1. 修改 `html`，添加 `border`  

   ```javascript
   html = html.replace(/<table/g, '<table border="1" cellspacing="0" style="border-collapse:collapse"')
   ```
2. 通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性给表格设置默认的边框样式  

   ```html
   <mp-html :tag-style="tagStyle">
   ```
   ```javascript
   data() {
     return {
       tagStyle: {
         table: 'border-top: 1px solid gray; border-left: 1px solid gray;',
         th: 'border-right: 1px solid gray; border-bottom: 1px solid gray;',
         td: 'border-right: 1px solid gray; border-bottom: 1px solid gray;'
       }
     }
   }
   ```

**Comment by allanwxl** [comment]
下载mp-html 改下node.vue中的逻辑
