### ISSUE TITLE
渲染出来的 rich-text 都不带 class

### ISSUE THREAD

**Issue by amialone** [jin-yufeng/mp-html#256]
## 使用环境  
原生平台，基础库 2.14.4

## 问题描述  
生成的 wxml 中 rich-text 不带 class，无法根据类名自定义样式

**Comment by jin-yufeng** [comment]
`rich-text` 只是个容器，内部的标签有 `class` 啊

**Comment by amialone** [comment]
> `rich-text` 只是个容器，内部的标签有 `class` 啊

如果给的 html 不带 class 也没有内联的样式，想通过父元素 .content h3 这种方式是不是没可能。
只能是通过内联样式的方法才行

**Comment by jin-yufeng** [comment]
外部样式只能用 `class` 选择器，不能用标签名选择器
设置标签的默认样式可以用 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性

**Comment by amialone** [comment]
> 外部样式只能用 `class` 选择器，不能用标签名选择器
> 设置标签的默认样式可以用 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性

感谢，问题解决了！
