### ISSUE TITLE
获取到接口的html后，正则添加 class，rich-text 传入html 是有样式的，使用插件样式没有作用上？

### ISSUE THREAD

**Issue by yuzhenliu** [jin-yufeng/mp-html#261]
## 问题描述  
获取到接口的html后，正则添加 class，直接使用rich-text 传入html 是有样式的，使用插件样式没有作用上，是要配置什么嘛？

**Comment by jin-yufeng** [comment]
外部样式要写在组件里（`node/node.wxss`），组件内外存在样式隔离
可以写在 `tools/config.js` 中的 `externStyle` 字段中，然后自动构建到组件包中，详见 [个性化](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=setting)

**Comment by yuzhenliu** [comment]
好的，我试试，感谢 ～

**Comment by Jamin-Deng** [comment]
1

**Comment by Jamin-Deng** [comment]
<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />
preview-img和selectable是这样用吗，为什么不起效呢

**Comment by jin-yufeng** [comment]
@Jamin-Deng 提问请新开一个 `issue`，并按照要求描述问题
