### ISSUE TITLE
请问preview-img和selectable怎么用

### ISSUE THREAD

**Issue by Jamin-Deng** [jin-yufeng/mp-html#262]
```html
<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />
```
为什么没有效果

**Comment by Jamin-Deng** [comment]
<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />
为什么没有效果

**Comment by Jamin-Deng** [comment]
<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />

**Comment by jin-yufeng** [comment]
使用平台是什么？你是怎么写的？

**Comment by Jamin-Deng** [comment]
微信小程序，不知道为什么我发布了代码咧<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />

**Comment by Jamin-Deng** [comment]
``<mp-html class='left-msg' content="{{item.content}}" :preview-img="true" :selectable="true" />``急

**Comment by Jamin-Deng** [comment]
这样不生效ios和安卓都是

**Comment by jin-yufeng** [comment]
看我上面说的，原生平台的格式是 `selectable="{{true}}"` 没有冒号

**Comment by Jamin-Deng** [comment]
还是不行

**Comment by Jamin-Deng** [comment]
·· <mp-html class='left-msg' content="{{item.content}}" preview-img="{{true}}" selectable="{{true}}" />··
下面是content
··<div>
                            <p><span>【${d.index}】</span><span style='color: #096dd9;font-size: 35rpx;font-weight: bold;' :copy-link="true">${d.title}</span></p>
                        </div>··

**Comment by Jamin-Deng** [comment]
``<div>
 <p><span>【${d.index}】</span><span style='color: #096dd9;font-size: 35rpx;font-weight: bold;' :copy-link="true">${d.title}</span></p>
</div>``

**Comment by Jamin-Deng** [comment]
```
<mp-html class='left-msg' content="{{item.content}}" preview-img="{{true}}" selectable="{{true}}" />
下面是content
```
```
<div>
<p><span>【${d.index}】</span><span style='color: #096dd9;font-size: 35rpx;font-weight: bold;' :copy-link="true">${d.title}</span></p>
</div>

**Comment by jin-yufeng** [comment]
提供能复现的 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
