### ISSUE TITLE
请问如何修改表格样式,之前的parser在trees.wxss设置的样式不生效

### ISSUE THREAD

**Issue by IAtone** [jin-yufeng/mp-html#264]
._table ._tr {
  border-right: 1px solid #cfcfcf;
  border-bottom: 1px solid #cfcfcf;
  overflow: auto;
}
这样设置tr和td不生效，但是._table设置样式生效，能否支持更高级的样式修改，比如：&:first-child这样的

**Comment by jin-yufeng** [comment]
`._xxx` 的样式不是一定生效的（不会作用于 `rich-text` 内的内容，只是用于模拟 `rich-text` 本身支持的标签效果）  
要设置标签的默认样式可以通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性（要给表格添加边框的话可以参考 [#255](https://github.com/jin-yufeng/mp-html/issues/255#issuecomment-763319415)）
要使用更高级的选择器可以通过 [外部样式](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=setting) 引入，但只能使用 `class` 选择器，即需要自行给需要的标签添加 `class`，然后可以使用 `.class:first-child`

**Comment by IAtone** [comment]
tagStyle: {
        p: "margin-bottom: 16px;line-height: 26px;font-size: 15px;color: #3d464d;white-space: initial;text-align: justify;",
        div: "margin-bottom: 16px;line-height: 26px;font-size: 15px;color: #3d464d;white-space: initial;text-align: justify;",
        span: "margin-bottom: 16px;line-height: 26px;font-size: 15px;color: #3d464d;white-space: initial;text-align: justify;",
        a: "margin-bottom: 16px;line-height: 26px;font-size: 15px;color: #3d464d;white-space: initial;text-align: justify;",
        li: "margin-bottom: 16px;line-height: 26px;font-size: 15px;color: #3d464d;white-space: initial;text-align: justify;",
        td: "color:#3d464d;font-size: 14px!important;overflow: auto;flex: 1;width: auto!important;padding: 5px;border-right: 1px solid #E0E7F6;border-bottom:1px solid #E0E7F6;word-wrap:break-word;",
        th: "color:#3d464d;font-size: 14px!important;overflow: auto;flex: 1;width: auto!important;padding: 5px;border-right: 1px solid #E0E7F6;border-bottom:1px solid #E0E7F6;word-wrap:break-word;",
        table: "table-layout:fixed;width: 100%;box-sizing: border-box;border: 2px solid #C7DAFF;border-radius: 6px;overflow: auto;border-collapse: collapse;border-spacing: 0;"
      },
在tag-style中div标签的样式设置好像不生效，其他的好像都可以，然后table设置border-radius也未生效，这边设置样式还有些问题，麻烦看一下，谢谢啦，然后还有个问题是，它在渲染的时候是不是有一定时间，有些内容过多就会有些慢，我在获取节点的时候高度都是0，设置了一个定时器500ms延迟才获取到节点的高度。以后要是能在样式中写它下的标签样式就更好了，谢谢！

**Comment by jin-yufeng** [comment]
`table` 的 `border-radius` 不生效可以参考 [这篇文章](https://www.cnblogs.com/7z7chn/p/5727334.html)，和 `border-collapse: collapse` 好像不能共存
至于 `div` 的样式不生效有没有被行内 `style` 覆盖了？没有的话可以提供一个 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html) 给我试试
高度可以在 [load](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=load) 或 [ready](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=ready) 事件中去获取

**Comment by IAtone** [comment]
好的，谢谢，表格圆角好了，有几个问题不好描述在这里，发邮件给你了。表格如何去除最后一个td/th的border，你之前说是要加个类名然后进行操作样式，但是加个类名这个操作比较麻烦，还有其他的比较简单的方法吗，效果其实就是给表格内部th/td用线条隔开

**Comment by jin-yufeng** [comment]
发到哪个邮箱了？我好想没有看到

**Comment by IAtone** [comment]
> 发到哪个邮箱了？我好想没有看到

能加个qq或者微信吗，还遇到些问题，需要你的帮助

**Comment by jin-yufeng** [comment]
qq: 2247603352

**Comment by jin-yufeng** [comment]
邮件回复啦
