### ISSUE TITLE
百度小程序渲染图片默认宽高都为1px

### ISSUE THREAD

**Issue by sty-loading** [jin-yufeng/mp-html#266]
## 问题描述  
![image](https://user-images.githubusercontent.com/17961751/108703776-0a8b6480-7546-11eb-9ffe-a4d35bb906b2.png)

**Comment by jin-yufeng** [comment]
图片加载完毕后就会变换回原大小，如果一直是 `1px` 的应该是加载失败了，看看有没有触发 `error` 事件
