### ISSUE TITLE
作者你好，关于富文本解析长按复制的问题

### ISSUE THREAD

**Issue by MmmMMMmmmyang** [jin-yufeng/mp-html#267]
作者你好，我是uni-app的开发者，已经查看过你在uni-app官方插件对网友的回复和官方文档中的提醒。
        但是关于ios无法长按复制，安卓可以长按复制的问题，希望可以寻求一个解决方法或者替换方法，因为我的小程序是内容学习类小程序，长按复制文章内容是小程序的核心功能，几乎可以是不可或缺。已经思考过几天，并没有思考出更好的解决方案。
        关于你在uni-app中的回复“官方 text 标签的 user-select 属性会变成 inline-block 影响布局”不知道会如何影响布局，如果影响不大，期望加一个属性“是否开启user-select”。盼回复，祝好！

**Comment by jin-yufeng** [comment]
`inline-block` 布局影响主要就是可能导致多余的换行，比如 [这个例子](https://developers.weixin.qq.com/community/develop/doc/000a8c966e44602732da21d7b59c00?highLine=user-select)  
这个问题我也想了很久，目前想到不影响布局的方法就是一个字一个 `text` 标签，但这样会增加大量的标签，影响性能，所以还没有太好的办法
自行选择是否开启 `user-select` 是一个可能的方案，可以试试
