### ISSUE TITLE
能支持在remax框架中使用吗？尝试了一下好像不可以

### ISSUE THREAD

**Issue by mmryzmr** [jin-yufeng/mp-html#269]

**Comment by jin-yufeng** [comment]
参考 [小程序自定义组件](https://remaxjs.org/guide/basic/custom-component)  引入原生包试试

**Comment by mmryzmr** [comment]
你好，我的使用方式大致如下：
import mpHtml from 'mp-html/dist/mp-weixin';
const htmlTpl = '<p>某某某先生:</p ><p><br></p >';
const App: React.FC = () => {
 return <mpHtml content={htmlTpl} />
}
![image](https://user-images.githubusercontent.com/22735565/108941345-e5a30880-768f-11eb-8dea-98fbdc825755.png)
![image](https://user-images.githubusercontent.com/22735565/108941438-14b97a00-7690-11eb-81b6-856e1ffb663f.png)

**Comment by jin-yufeng** [comment]
`import MpHtml from 'mp-html/dist/mp-weixin/index'` 试一下

**Comment by mmryzmr** [comment]
> `import MpHtml from 'mp-html/dist/mp-weixin/index'` 试一下

这样写会出现编辑卡住的问题：
![image](https://user-images.githubusercontent.com/22735565/108953950-fdd25200-76a6-11eb-80ae-f5d46b977a1c.png)

**Comment by jin-yufeng** [comment]
我试了一下确实会卡住
可能是 `remax` 没有做好自定义组件内引用另一个自定义组件的适配

**Comment by jin-yufeng** [comment]
给他们提了个 [issue](https://github.com/remaxjs/remax/issues/1490)，看看能不能解决

**Comment by mmryzmr** [comment]
> 给他们提了个[issue](https://github.com/remaxjs/remax/issues/1490)，看看能不能解决

感谢大神的解答

**Comment by jin-yufeng** [comment]
`remax` 升级到 `2.11.6` 后可以了
