### ISSUE TITLE
如何设置网页全屏显示

### ISSUE THREAD

**Issue by wk989898** [jin-yufeng/mp-html#270]
https://github.com/jin-yufeng/mp-html/blob/1c3a3d0fa5828e29691d7e2e6083a37162044c68/src/miniprogram/parser.js#L413-415

如果我想让网页宽度为全屏，而不是大于屏幕从而导致左右滑动应该怎么做

**Comment by jin-yufeng** [comment]
你是说一个 `1000px` 宽的网页放到屏幕宽度只有 `500px` 的手机上时把网页整体缩小一半？

**Comment by wk989898** [comment]
是这个意思，或者让其自适应屏幕也行

**Comment by jin-yufeng** [comment]
获取到网页的宽度并不简单
一个简单的办法是先渲染一下获取宽度再进行缩小，但这样会闪一下
如果要在解析的过程中获取最大宽度需要考虑 `margin`、`padding`、单位换算等非常复杂
而且这样会减慢速度，缩小后字也可能变得特别小

事实上目前对于设置的宽度超出屏幕宽度的，都会[自动加上 max-width:100%](https://github.com/jin-yufeng/mp-html/blob/1c3a3d0fa5828e29691d7e2e6083a37162044c68/src/miniprogram/parser.js#L577)，所以一般不会超出去

**Comment by wk989898** [comment]
我是在做解析邮箱内容，所以无法确定网页内容。
`max-width:100%`这个并没有生效，`style`中自带的`width：_px`依然起作用。
