### ISSUE TITLE
点击a标签的时候需要获取到标签里的内容

### ISSUE THREAD

**Issue by lvan-zhang** [jin-yufeng/mp-html#271]
## 新功能描述
点击a标签的时候需要获取到标签里的内容，目前只能获取到href和data-之类的属性。
如：
<a href="">点击</a>
获取到"点击"

## 应用场景
点击 a 标签的时候，需要获取 a 标签的内容进行埋点

**Comment by StarSky1993** [comment]
nvue不支持innerText
