### ISSUE TITLE
部分文本在APP端百度小程序中无法显示

### ISSUE THREAD

**Issue by fatefate0727** [jin-yufeng/mp-html#272]
## 使用环境  

百度开发者工具
基础库：3.120.16

移动端百度小程序
swan-js version：3.280.2
native version：2.28.0
宿主 version：12.9.0.11

## 问题描述  
部分文本在开发者工具中能够显示，但在App端小程序中无法显示
百度开发者工具截图：
![百度开发者工具截图](https://user-images.githubusercontent.com/42198858/109473267-0e6f3780-7aae-11eb-9a39-a4049b89939b.png)

App端小程序截图：
![App端小程序截图](https://user-images.githubusercontent.com/42198858/109473294-14fdaf00-7aae-11eb-9e45-39844e345dae.jpg)

## 复现方式  
示例项目：
html：<div>

      Test 文本 011
      <ul>
      Test 文本 012
              <li>
              Test 文本 013
                  <p>
                      Test 文本 014
                  </p>
              </li>
              </ul>
      </div>

个人demo:
~~暂无~~
[https://github.com/fatefate0727/mp-html-test](https://github.com/fatefate0727/mp-html-test)

复现方式：
使用百度开发者工具打开对应项目，点击上方预览，使用百度APP扫码预览

**Comment by jin-yufeng** [comment]
我没有百度账号，可以真机调试看一下 `Swan Element` 里的结构吗？

**Comment by fatefate0727** [comment]
> 我没有百度账号，可以真机调试看一下 `Swan Element` 里的结构吗？

![EORS%W3GA V9@EV79YKK5JR(1)](https://user-images.githubusercontent.com/42198858/109611189-d24cdd00-7b68-11eb-80b8-b6befa399219.png)
![真机调试截图(1)](https://user-images.githubusercontent.com/42198858/109611234-e1cc2600-7b68-11eb-8975-38ac86051f67.png)

**Comment by jin-yufeng** [comment]
试试 [mp-html-test-master.zip](https://github.com/jin-yufeng/mp-html/files/6095233/mp-html-test-master.zip) 可不可以

**Comment by fatefate0727** [comment]
> 试试 [mp-html-test-master.zip](https://github.com/jin-yufeng/mp-html/files/6095233/mp-html-test-master.zip) 可不可以

可以了，感谢。
我本地重新build了一份dist后可以正常显示了。（最新的代码似乎并没有提交更新后的dist）
