### ISSUE TITLE
富文本内容 选中高亮后 给富文本加标识

### ISSUE THREAD

**Issue by zhuweilong** [jin-yufeng/mp-html#273]
您好，大佬作者，现在像微信读书app等读书类的， 他们都有文章选中文本高亮然后可以加划线等样式和点击事件，请问小程序上实现思路是啥？
1.一个重要的难点是，富文本的内容，怎么匹配选中高亮的文本代码？

**Comment by jin-yufeng** [comment]
我觉得小程序中没法实现
现在小程序上能获取到选中内容的接口只有 [wx.getSelectedTextRange](https://developers.weixin.qq.com/miniprogram/dev/api/ui/keyboard/wx.getSelectedTextRange.html)，但仅限在输入框 `focus` 时用
非输入框获取不到选中的文本，就更没法加样式什么的了
