### ISSUE TITLE
最新版本不支持秀米防盗链了

### ISSUE THREAD

**Issue by shiyuanjieyi** [jin-yufeng/mp-html#275]
## 使用环境  

微信小程序 2.15.0
## 问题描述  

如题，我更新mp-html最新版本之后，富文本若有秀米图片，在真机浏览不显示，但是我尝试用以前的Parser版本，发现真机可以正常显示，我猜测是新版本对图片进行处理，没加载成功不会显示图片导致的，实际上秀米图片确实会报403错误，但是不影响真机显示。希望作者可以考虑修复这个bug，或者考虑开发支持秀米防盗链的问题。感谢！！！
附：
之前我的做法是将秀米图片链接htpps改为http，在真机就可以正常显示了，现在改成http也没用
秀米图片链接：
http://img.xiumi.us/xmi/ua/1ZDgi/i/e07ab6524b8558a168ec6883cf40bf0a-sz_149828.jpg

**Comment by jin-yufeng** [comment]
我试了一下
```html
<image src="http://img.xiumi.us/xmi/ua/1ZDgi/i/e07ab6524b8558a168ec6883cf40bf0a-sz_149828.jpg" />
```
模拟器和真机都不行

```html
<rich-text nodes="<img src='http://img.xiumi.us/xmi/ua/1ZDgi/i/e07ab6524b8558a168ec6883cf40bf0a-sz_149828.jpg'>" />
```
模拟器不行，真机可以

估计是 `rich-text` 和 `image` 采取的加载策略是不一样的
原来的版本是用 `rich-text` 来显示图片，现在改成了 `image` 所以不行了
事实上之前的版本中在用 `rich-text` 还是 `image` 显示图片已经反复横跳很多次了，可以参考 [图片处理](https://github.com/jin-yufeng/mp-html/blob/v1.x/docs/instructions.md#%E5%9B%BE%E7%89%87%E5%A4%84%E7%90%86)，现在觉得还是 `image` 比较方便
防盗链的问题估计还是要自行转存来解决
