### ISSUE TITLE
头条小程序 markdown 渲染 代码块没有渲染

### ISSUE THREAD

**Issue by mkm0094** [jin-yufeng/mp-html#280]
## 使用环境  

uniapp 打包
mp-html 2.1

## 问题描述  

markdown在头条小程序里 代码块无法渲染

<img width="444" alt="QQ20210401-133533@2x" src="https://user-images.githubusercontent.com/18025419/113248296-3a6d1b00-92ef-11eb-905a-55998f6b13f7.png">

其他场景下正常
<img width="387" alt="QQ20210401-133639@2x" src="https://user-images.githubusercontent.com/18025419/113248338-57095300-92ef-11eb-9dfe-c76dec690a56.png">

## 复现方式  

直接跑头条小程序即可

**Comment by jin-yufeng** [comment]
是不是还用了 `highlight` 插件？

**Comment by mkm0094** [comment]
> 是不是还用了`highlight`插件？

已经删除了 还是这样，可能是字节的问题吧，我渲染md文件，和其他小程序都相差很多，我已经放弃了 使用web-view给头条小程序用了

**Comment by jin-yufeng** [comment]
我试了一下，`uni-app` 编译的时候默认给组件设置了 `addGlobalClass`，头条小程序设置了 `addGlobalClass` 导致组件内的 `rich-text` 里标签的 `class` 无法匹配组件 `ttss` 中的内容，导致一些样式丢失了
试试这个 [demo.zip](https://github.com/jin-yufeng/mp-html/files/6247530/demo.zip) 是不是正常的
