### ISSUE TITLE
能够解析微信公众号文章中的视频吗？

### ISSUE THREAD

**Issue by l0rraine** [jin-yufeng/mp-html#282]
## 问题描述  
那视频必须点击一下播放按钮，video开始播放才有src……
这种神仙操作可以完成吗？

**Comment by jin-yufeng** [comment]
你说的是 `iframe` 标签吧，如果是腾讯视频的可以用 [腾讯视频插件](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=txv-video) 播放

**Comment by l0rraine** [comment]
大佬，太佩服了啊，这都能弄？
谢谢呀，没想到去翻文档，丢人了
