### ISSUE TITLE
uniapp下 百度小程序经解析之后video显示不了

### ISSUE THREAD

**Issue by NanmiCoder** [jin-yufeng/mp-html#285]
## 使用环境  

百度小程序调试基础库版本：3.280.26

## 问题描述  

同样的HTML中含有video通过HBuilderX编译后微信小程序表现正常，百度小程序显示不出来
图一微信  图二百度

![image](https://user-images.githubusercontent.com/47178017/114262652-bb28c700-9a13-11eb-94b3-5500fdef8457.png)

## 复现方式  

	<div class="videocontent" style="text-align: center;">
			<video vid="590" playsinline="" webkit-playsinline="" class="video-js vsg-skin vjs-16-9"
			controls="" preload="auto" width="640" height="360" poster="https://www.yeecar.cn/static/upload/video_posters/2020-10/f3t2SoNU2wD2-1604053890374.jpg">
				<source src="https://1253351594.vod2.myqcloud.com/2bc1a6c5vodgzp1253351594/d9da49c85285890809331262408/84XAa0D83nsA.mp4"
				type="video/mp4" res="9" label="原画" />
				<source src="https://1253351594.vod2.myqcloud.com/2bc1a6c5vodgzp1253351594/d9da49c85285890809331262408/84XAa0D83nsA.mp4"
				type="video/mp4" res="3" label="高清" />
			</video>
		</div>

**Comment by jin-yufeng** [comment]
![微信截图_20210410161008](https://user-images.githubusercontent.com/48236054/114263302-435c9b80-9a17-11eb-8298-f785b5c0a60d.png)  
我这里可以播放，请提供复现的 `demo` 项目

**Comment by NanmiCoder** [comment]
找到原因了，百度调试器的问题，预览跟真机模式线都是好的。
