### ISSUE TITLE
uniapp 富文本编辑器上传视频之后是否不支持视频预览

### ISSUE THREAD

**Issue by duliz** [jin-yufeng/mp-html#286]
看代码是直接渲染为view标签
![image](https://user-images.githubusercontent.com/23290413/114532921-e9124380-9c7f-11eb-910c-d91825f2d27b.png)

**Comment by jin-yufeng** [comment]
因为 `uni-app` 的 `H5` 端 `video` 标签无法产生点击事件，点击视频就无法弹出对应的菜单，所以在编辑状态下，直接用一个黑框来占位，编辑完成后就变回 `video` 了
