### ISSUE TITLE
图片展示

### ISSUE THREAD

**Issue by Shaoyouqing** [jin-yufeng/mp-html#288]
我的图标展示有截断,希望大佬优化下
如下图:
![image](https://user-images.githubusercontent.com/51347185/115012746-c6cc3000-9ee2-11eb-967c-edaa274c4b43.png)

**Comment by Shaoyouqing** [comment]
图片,不是图标

**Comment by jin-yufeng** [comment]
按照模板要求提供可复现的 `html` 内容或 `demo` 项目

**Comment by Shaoyouqing** [comment]
<p>下表说明了我们在特定业务场景下收集的信息以及我们使用信息的目的。信息的收集和使用因场景而异。</p><p></p><p>请注意，当您选择接受某项<strong>UBR</strong>服务时，您应向我们提供或允许我们收集为实现该等服务的主要目的或使用该等服务的核心功能（合称“<strong>核心功能</strong>”）的所必需的某些信息，否则我们将无法向您提供该等核心功能。</p><p></p><p>您也可能被要求向我们提供某些附加信息，使我们能够为您提供更好的用户体验。但是，如果您选择不提供此类附加信息，您仍可以使用核心功能，但可能无法使用某些附加服务或享受如下所述的更好的用户体验。</p><p></p><p>下表说明了我们收集的信息类型以及我们使用这些信息的目的。每一项UBR服务收集的信息及使用该等信息的目的可能会有所不同。请注意，我们可能使用部分或全部此类信息以遵守法律、发现或防止欺诈并维护我们的合法权利。有关各项目的的更多细节，请参见下表“关于使用目的的专项说明”。</p><p></p><p><strong>个人信息</strong>是指以电子或者其他方式记录的能够单独或者与其他信息结合识别特定自然人身份或者反映特定自然人活动情况的各种信息。个人信息包括姓名、出生日期、身份证件号码、个人生物识别信息、住址、通信通讯联系方式、通信记录和内容、账号用户名及密码、财产信息、征信信息、行踪轨迹、住宿信息、健康生理信息、交易信息等。</p><p></p><p><strong>个人敏感信息</strong>是指一旦泄露、非法提供或滥用可能危害人身和财产安全，极易导致个人名誉、身心健康受到损害或歧视性待遇等的个人信息。个人敏感信息包括身份证件号码、个人生物识别信息、银行账户、通信记录和内容、财产信息、征信信息、行踪轨迹、住宿信息、健康生理信息、交易信息、14岁以下(含)儿童的个人信息等。<strong><u>本政策下的个人敏感信息以粗体和下划线显示。</u></strong></p><p></p><div class="media-wrap image-wrap align-center" style="text-align:center"><img src="https://amposs.app.universalbeijingresort.com/image/20210317/e542dbff-c684-4999-a26c-9bfcecb49b89.png" width="329" height="1346.80908203125" style="width:329px;height:1346.80908203125px"/></div><p></p>

**Comment by Shaoyouqing** [comment]
`<p>下表说明了我们在特定业务场景下收集的信息以及我们使用信息的目的。信息的收集和使用因场景而异。</p><p></p><p>请注意，当您选择接受某项<strong>UBR</strong>服务时，您应向我们提供或允许我们收集为实现该等服务的主要目的或使用该等服务的核心功能（合称“<strong>核心功能</strong>”）的所必需的某些信息，否则我们将无法向您提供该等核心功能。</p><p></p><p>您也可能被要求向我们提供某些附加信息，使我们能够为您提供更好的用户体验。但是，如果您选择不提供此类附加信息，您仍可以使用核心功能，但可能无法使用某些附加服务或享受如下所述的更好的用户体验。</p><p></p><p>下表说明了我们收集的信息类型以及我们使用这些信息的目的。每一项UBR服务收集的信息及使用该等信息的目的可能会有所不同。请注意，我们可能使用部分或全部此类信息以遵守法律、发现或防止欺诈并维护我们的合法权利。有关各项目的的更多细节，请参见下表“关于使用目的的专项说明”。</p><p></p><p><strong>个人信息</strong>是指以电子或者其他方式记录的能够单独或者与其他信息结合识别特定自然人身份或者反映特定自然人活动情况的各种信息。个人信息包括姓名、出生日期、身份证件号码、个人生物识别信息、住址、通信通讯联系方式、通信记录和内容、账号用户名及密码、财产信息、征信信息、行踪轨迹、住宿信息、健康生理信息、交易信息等。</p><p></p><p><strong>个人敏感信息</strong>是指一旦泄露、非法提供或滥用可能危害人身和财产安全，极易导致个人名誉、身心健康受到损害或歧视性待遇等的个人信息。个人敏感信息包括身份证件号码、个人生物识别信息、银行账户、通信记录和内容、财产信息、征信信息、行踪轨迹、住宿信息、健康生理信息、交易信息、14岁以下(含)儿童的个人信息等。<strong><u>本政策下的个人敏感信息以粗体和下划线显示。</u></strong></p><p></p><div class="media-wrap image-wrap align-center" style="text-align:center"><img src="https://amposs.app.universalbeijingresort.com/image/20210317/e542dbff-c684-4999-a26c-9bfcecb49b89.png" width="329" height="1346.80908203125" style="width:329px;height:1346.80908203125px"/></div><p></p>`

**Comment by jin-yufeng** [comment]
![微信截图_20210416195900](https://user-images.githubusercontent.com/48236054/115021173-372c7e80-9eee-11eb-9046-b520c006b26d.png)
没有复现你说的问题，提供可复现的 `demo` 项目

**Comment by Shaoyouqing** [comment]
你在_img加一个background-size: contain;就可以化解了
