### ISSUE TITLE
图片缓存功能

### ISSUE THREAD

**Issue by PentaTea** [jin-yufeng/mp-html#292]
## 新功能描述

app端缓存图片到本地

图片下载到本地缓存目录后通过uni.setStorage保存图片地址和文件名,

每次加载图片前uni.getStorage查找是否存在缓存

## 应用场景

断网情况或者大图预览等

请问mp-html是否已经有相关功能实现或者计划,没有的话我实现后提交pr可以吗

**Comment by jin-yufeng** [comment]
我试了一下，`nvue` 中因为用的是 `web-view`，可以自动缓存  
`vue` 确实不行，断网重开就显示不了了，不过我查了一下，好像只有安卓端有这个问题（[78386](https://ask.dcloud.net.cn/question/78356)、[67860](https://ask.dcloud.net.cn/question/67860)）
再加上大部分情况下 `html` 内容也是从服务器上获取的吧，这样的话断网即使有图片缓存也没有用  
这样的话应用面就比较窄  
另外，我曾经试过把 `base64` 图片缓存到本地方便预览，要在合适的时机清理掉过期的文件，避免缓存文件越堆越多，还是挺麻烦的  
所以我觉得不太必要

**Comment by PentaTea** [comment]
我现在的需求类似于便签,所以需要在断网环境下针对文章拥有读写能力,而且mphtml也是拥有富文本编辑插件的,如果只能在网络环境编辑限制就有点大了吧,请问这个缓存需求可以开发插件解决吗

另,我现在需要保留一些标签上的dataset属性,只能通过更改 `parser.prototype.onAttrName` 的逻辑解决吗,近期版本mphtml计划提供相关属性来控制显示吗

**Comment by jin-yufeng** [comment]
通过插件实现应该是可行的，大致思路如下（具体参考 [开发插件](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=develop)），可以试试看，可以的话可以提个 `pr`  
```javascript
const local = uni.getStorageSync('xxx')
function Cache() {
  // 初始化
  // 清理过期文件
}
// #ifdef APP-PLUS
Cache.prototype.onParse = function (node) {
  // 解析到图片
  if (node.name == 'img' && node.attrs.src) {
    if (local[node.attrs.src]) {
      // 缓存中有这张图片
      node.attrs.src = local[node.attrs.src] // 替换为本地路径
    } else {
      uni.downloadFile({
        url: node.attrs.src,
        success: res => {
          // 保存文件，更新 local...
        }
      })
    }
  }
}
// #endif
module.exports = Cache
```

**Comment by PentaTea** [comment]
我尝试着写了一下,现在有这么几个问题:
- 判断缓存记录时需要使用 `plus.io.resolveLocalFileSystemURL` 方法确定本地文件存在,只能异步修改src属性,请问我该怎么在onParse中实现异步
- 没有获取到缓存时会正常显示图片并开启一个下载task,但这样貌似就相当于下载了两遍?

**Comment by jin-yufeng** [comment]
1. `onParse` 只能是同步的，不过 `node` 是设置到视图层的变量，修改它 `uni` 会自动同步到视图层，所以先把 `node.attrs.src` 设置为空，异步回调里再设置回去就行了，只是这样的话图片会出现的比文字慢一点  
不过，`storage` 还在的情况下缓存文件被清理了的概率高吗？不高的话也可以直接认为 `storage` 里存的文件存在吧  
2. 和 `1` 差不多，如果想只下载一次，可以先把 `node.attrs.src` 设置为空，保存到本地后再将 `src` 设置为本地地址，就是这样应该也会慢一点，看怎么权衡了

**Comment by PentaTea** [comment]
基本功能实现了,但貌似[图片点击和长按逻辑](https://github.com/jin-yufeng/mp-html/blob/38172495d663c66a4e6604fb282d031ad08ac58e/src/uni-app/components/mp-html/node/node.vue#L196-L240)使用的`this.root.imgList`不是响应式的,无法浏览和保存图片..

**Comment by jin-yufeng** [comment]
我试了一下，这样是可以的  
```javascript
function Cache (vm) {
  this.i = 0 // 用于标记第几张图
  this.vm = vm // 组件实例
}
Cache.prototype.onParse = function (node, parser) {
  if (node.name == 'img' && node.attrs.src) {
    let src = node.attrs.src // 暂存 src
    node.attrs.src = '' // 设置为空
    node.attrs.i = this.i // 标记第 i 张图
    this.i++
    parser.expose() // 使得 img 不被 rich-text 包含，否则无法点击预览
    setTimeout(() => { // 模拟异步回调
      node.attrs.src = src // 恢复 src
      this.vm.imgList[node.attrs.i] = src // 设置 imgList
    }, 3000)
  }
}
```
