### ISSUE TITLE
请问这个能设置缩放嘛，看文档中是没有的

### ISSUE THREAD

**Issue by 1451544363** [jin-yufeng/mp-html#296]

**Comment by jin-yufeng** [comment]
固定的缩放比例的话在 [container-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=container-style) 属性里设置 `transform: scale(x)` 就可以了  
如果要动态的双指缩放这种的话没有，曾经试过，但是感觉非原生的双指缩放实现复杂，且效果都不好
