### ISSUE TITLE
原生小程序项目使用链接，点击链接，会报错 Cannot read property 'triggerEvent' of undefined

### ISSUE THREAD

**Issue by RookieDouby** [jin-yufeng/mp-html#300]
## 基础库2.16.1, 现在在做的原生项目，测试最基本a链接报错Cannot read property 'triggerEvent' of undefined
mpContent: `<a href="/pages/index/index">链接</a>`,
`<mp-html content="{{mpContent}}">`
按照文档的下载zip包方式引入的，没有问题。链接能渲染出来，但是点击链接会报错Cannot read property 'triggerEvent' of undefined， 并且不能跳转。我看这个错误是node.js里边的this.root.triggerEvent('linktap')有问题，貌似是this.root获取不到？
有可能是什么问题呢？

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目
