### ISSUE TITLE
a标签换行问题

### ISSUE THREAD

**Issue by maxwelldu** [jin-yufeng/mp-html#302]
## 问题描述  

![Screen Shot 2021-05-24 at 5 43 36 PM](https://user-images.githubusercontent.com/10094605/119329337-af3d4f80-bcb7-11eb-938d-d192bf7068d5.png)

一段带a 标签的问题，出现了换行，请问有什么办法可以避免吗

预期的表现
请描述预期的表现
a 标签后文本不换行

实际的表现
请描述实际的表现
a标签后文本换行了
html代码
请附上出现问题的html代码（或附件），例如：
`" <a href="/pages/stock/ts/ts?stock_code=sz000661&stock_type=SZ&type=1" style="color: #006CFC">长春高新</a> 上周五放量跌停，今天继续大跌，引起各方投资者议论，都在为它的大跌找理由。其实什么理由也不用找，就是涨得太多了，有些资金觉得赚够了，可以兑现筹码了。<br><br>从2015年以来， <a href="/pages/stock/ts/ts?stock_code=sz000661&stock_type=SZ&type=1" style="color: #006CFC">长春高新</a> 从33元涨到522元，上涨了将近16倍。而从去年下半年以来，波动明显加大，双顶明显，调整早晚都要来的，根本不用为大跌找理由。<br><br>这种大市值的公司，就看趋势就行，大趋势上行，就参与，下行就撤退，时间足够，不用研究太深，研究得太深，反而容易误导自己。<br><br>只看趋势，不看故事！"`

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目

**Comment by maxwelldu** [comment]
发现没有问题，是自己之前加了样式影响的，关闭吧，打扰
