### ISSUE TITLE
关于微信小程序 a 标签跳转的问题

### ISSUE THREAD

**Issue by Lupeiwen0** [jin-yufeng/mp-html#304]
## 新功能描述

希望可以提供一个<控制默认跳转>的参数
可以关闭默认的跳转
因为有些场景下并不是希望直接跳转，而是需要对参数进行转化，解码
有些富文本编辑器还会对a标签默认添加 http:// 的前缀，所以默认跳转有时候并不能很好的适用

## 应用场景
微信小程序

**Comment by jin-yufeng** [comment]
如果是外部链接的话把 [copy-link](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=copy-link) 属性设置为 `false` 就不会自动 复制/跳转了
内部链接的话目前只要页面存在就会自动跳转，不需要的话暂时可以把 [这里](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/node/node.js#L146) 去掉
