### ISSUE TITLE
有没有办法设置超出几行显示省略号

### ISSUE THREAD

**Issue by Cjw-259** [jin-yufeng/mp-html#308]
有没有办法设置超出几行显示省略号，使用css webkit的超出显示省略号的属性，app端会出现内容不显示，内容重叠的bug

**Comment by jin-yufeng** [comment]
`ios` `app` 中 `-webkit-line-clamp` 内只能放行内标签

**Comment by mh1874** [comment]
大佬这个有办法解决吗 @jin-yufeng

**Comment by mh1874** [comment]
想问一下，最后用什么方案解决的呢 @Cjw-259
