### ISSUE TITLE
大量图片的富文本加载会比较毫性能，希望可以支持虚拟滚动类似的支持

### ISSUE THREAD

**Issue by wekerSnail** [jin-yufeng/mp-html#309]
## 新功能描述
大量图片的富文本加载会比较毫性能，希望可以支持虚拟滚动类似的支持
## 应用场景
大量图片的商品或者文章类富文本加载，页面可能会卡顿

**Comment by jin-yufeng** [comment]
虚拟滚动的前提是内容能够拆成很多个块，翻到下面的块的时候隐藏上面的块
但是富文本是一个树状结构，程序几乎没法很好的把内容拆成若干块又不影响样式
除非是人工的进行分段，那可以结合 [recycle-view](https://developers.weixin.qq.com/miniprogram/dev/extended/component-plus/recycle-view.html) 来做，每段一个富文本标签，其会自动进行回收
