### ISSUE TITLE
style 插件，样式无法显示

### ISSUE THREAD

**Issue by heisenme** [jin-yufeng/mp-html#313]
## 使用环境  
微信原生小程序 富文本

## 问题描述  
style 标签样式无法显示

## 复现方式  
`
            <p class="ql-align-right" >sdfjeoafnidnfae</p>
            <style>
            .ql-align-right {
                text-align: center;
            }
            </style>
 `

**Comment by jin-yufeng** [comment]
目前只支持 `style` 标签要放在前面的，因为是按照顺序解析下来的
放在后面的话要解析两次才行，比较慢
