### ISSUE TITLE
页面跳转之后，视频还是在播放，有没有预留方法，暂停播放

### ISSUE THREAD

**Issue by w3812127** [jin-yufeng/mp-html#317]
页面跳转之后，视频还是在播放，有没有预留方法，暂停播放
方便 在页面的 hide()生命周期中调用

**Comment by jin-yufeng** [comment]
什么平台啊？
可以试试这样吧
```javascript
onHide() {
  for (let video of this.$refs.article._videos) {
    video.pause()
  }
}
```

**Comment by w3812127** [comment]
uniapp  android 平台

**Comment by w3812127** [comment]
uniapp android 平台，  
 for (let video of this.$refs.article._videos) {
    video.pause()
  }
这个方法 debug 的时候 _videso 是空的，没有拿到视频

**Comment by jin-yufeng** [comment]
是有这个问题，暂时没有找到好的解决办法

**Comment by qingyun1029** [comment]
> 页面跳转之后，视频还是在播放，有没有预留方法，暂停播放 方便 在页面的 hide()生命周期中调用

可以利用 `if` 指令来控制（销毁） `video`
