### ISSUE TITLE
如何实现简单互动

### ISSUE THREAD

**Issue by letitfly** [jin-yufeng/mp-html#319]
比如点击一个按钮，则隐藏/显示一个区域。具体实现可以使用data-*传递参数，不清楚的是怎么选择到某一个元素（节点），并增加/移除该元素的样式。

**Comment by letitfly** [comment]
我自己实验了一下（uview/u-parse)，基本原理的是可行的。就是遍历nodes找到相应的节点，然后修改attrs.class就可以了。

有点困惑的一个问题是 uview/u-parse 和 mp-view 实现的好像不一样，节点结构不一样。是使用同一个库吗？

**Comment by jin-yufeng** [comment]
`uview/u-parse` 用的是旧版本的，不过结构差不多吧，在 `nodes` 里找到对应的节点即可，具体哪里不一样？

**Comment by letitfly** [comment]
谢谢。nodes的结构是一样的(具体的attrs如id,data-*等有细微区别)，我指的是dom结构，造成u-parse有些问题。

比如我测试下面的html: (hidden 是全局样式 display: none)
<div class="hidden"><div>text</div><img src="..."/></div>
u-parse渲染成:
<trees class="hidden"><view ..><richtext>...</richtext><image>...</image></view></trees>
因为trees有固有的display值，并且插入的额外的view，造成在trees上的样式失效。

而uni-app/mp-html似乎是一对一映射成view，所以对样式的支持好多了。

测试接下来的主要问题是支持动态样式，有两种方式：1.动态样式是全局的，可行但所有样式必须预先编译进小程序，因为小程序不支持动态加载样式文件。2. 样式inline成style，但这样似乎动态加减样式不产生变化。可能的解决办法是做个监听样式增加移除的机制，并根据事件重新inline样式。

这是我粗浅的理解，请指正。谢谢

**Comment by jin-yufeng** [comment]
`dom` 树是通过自定义组件递归显示的，在小程序里，自定义组件本身是一层，`vue` 要求组件内必须有一个根标签，所以一个 `div` 就会被渲染成 `<tree><view></view></tree>` 这样的两层，旧版本的处理是把标签的样式加在 `view` 层上，然后 `tree` 层设置 `inherit` 继承样式，不过有时候还是会影响样式；不过现在微信小程序支持 [虚拟化组件节点](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)，去掉自定义组件层，所以新版本可以渲染成 `div` 一对一映射成 `view`  
至于修改样式，因为 `nodes` 变量是设置到视图层的变量，`vue` 里修改 `nodes` 就会自动同步到视图层的，只要在 `nodes` 里递归的找到要修改的标签，然后修改 `node.attrs.style` 或者 `class` 就可以了，之前有一个这样子的扩展插件 [document](https://github.com/jin-yufeng/mp-html/blob/v1.x/patches/document/document.uni.js)，可以参考一下实现方式  
还有个问题是，为了减小设置到视图层的数据大小，在解析的时候，把大部分 `data-` 和 `id` 等渲染时用不到的属性都删除了，这样查找起来也会比较困难，可以视情况修改一下这几个地方 [L221](https://github.com/jin-yufeng/mp-html/blob/master/src/uni-app/components/mp-html/parser.js#L221)、[L294](https://github.com/jin-yufeng/mp-html/blob/master/src/uni-app/components/mp-html/parser.js#L294)

**Comment by letitfly** [comment]
谢谢解释！我自己已经找到了修改的地方，并实现了toggle/carousel等简单功能。感觉mp-html很不错，谢谢！
