### ISSUE TITLE
在taro中使用报缺少模板，是我使用姿势不对吗？

### ISSUE THREAD

**Issue by missMHWGO** [jin-yufeng/mp-html#321]
将代码拷进components:
![image](https://user-images.githubusercontent.com/14312158/124585435-ddea4080-de87-11eb-8b8b-750b4c4bcd21.png)
![image](https://user-images.githubusercontent.com/14312158/124585103-8fd53d00-de87-11eb-9f74-c97e29c71cf7.png)
![image](https://user-images.githubusercontent.com/14312158/124585513-f0fd1080-de87-11eb-8212-afd8899cb21e.png)
![image](https://user-images.githubusercontent.com/14312158/124584406-ccecff80-de86-11eb-917c-b656e7d651c9.png)

如上图所示，编译少了模版
taro版本:3.0.23
mp-html:2.1.3
参考文档：http://taro-docs.jd.com/taro/docs/mini-third-party

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目
