### ISSUE TITLE
ruby-align设置了没效果

### ISSUE THREAD

**Issue by lopaz** [jin-yufeng/mp-html#325]
这样一段html: `<ruby>他<rt>tā</rt>卷<rt>juǎn</rt>了<rt>le</rt>一<rt>yī</rt>支<rt>zhī</rt>烟<rt>yān</rt></ruby>`
看这里，ruby和rt应该都是受信任标签，转换时应该保持标签名不变，但实际上似乎转成了text和div节点：
https://github.com/jin-yufeng/mp-html/blob/a0c1e3450818c8925190898a74b616c80465d767/src/miniprogram/parser.js#L7
![image](https://user-images.githubusercontent.com/8480947/125797031-c51d99db-3989-410a-80d3-23fbb59c495f.png)
从上面截图看，ruby-align属性被加到了普通的view标签上面，这应该是不生效的原因。下图显示了rich-text和mp-html的对比，mp-html中拼音并没有预期的那样居中：
![image](https://user-images.githubusercontent.com/8480947/125797115-e328e53c-f577-4db4-b008-0aed97b4da12.png)

**Comment by jin-yufeng** [comment]
保持标签名不变只是解析的过程中不变，渲染的时候肯定要通过其他小程序标签模拟（`ruby` 标签只有微信的 `rich-text` `2.7.1` 基础库以上才支持，为了兼容，也没有直接用 `rich-text` 显示）
这个没有居中对齐是有点问题，我调整一下
