### ISSUE TITLE
使用 style插件使用问题

### ISSUE THREAD

**Issue by comxza** [jin-yufeng/mp-html#326]
文档中这个style的使用方式，查阅文档暂未找到可行的使用方式
![1](https://user-images.githubusercontent.com/21981010/126249777-331d9c56-63dd-4e60-90f5-b2131beae5d7.png)

## 问题描述  
就是我在使用这个style标签的时候，，我返回的富文本值就包含这些class或者id，比如以下类型
`<span class="aa">Hello </span><span id="bb">world!</span>`
那么我想对class为aa的或者id为bb的单独设置样式，这个style样式需要写在哪里呢，我在uni-app问答社区有回复，告知写在[externStyle](https://ask.dcloud.net.cn/question/127254)或者[mp-html/node/node.vue](https://ask.dcloud.net.cn/question/127254)，但是这个如果写在externStyle这个有参考模版之类的吗，我尝试很多个写法都不行，在nvue情况下

**Comment by comxza** [comment]
但是我又发现   如果把样式写在`mp-html/node/node.vue`，这样一来的话，在非app端是生效的，在app端是不生效

**Comment by jin-yufeng** [comment]
[style](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=style) 插件用于解析和匹配传入 `html` 中的 `style` 标签，比如这样：  
```html
<mp-html content="<style>.aa{color:red}</style><div class='aa'>123</div>" />
```
如果是固定的内容可以写在 `tools/config.js` 的 [externStyle](https://github.com/jin-yufeng/mp-html/blob/master/tools/config.js#L30) 字段里，然后 [构建](https://jin-yufeng.gitee.io/mp-html/#/advanced/develop?id=pack) 组件包：  
```bash
npm install
npm run build:uni-app
```
最后拷贝 `dist/uni-app` 到项目中使用就可以了  
添加到 `node/node.vue` 中是仅在非 `app` 端生效的，`nvue` 的 `app` 端用 `web-view` 渲染，需要添加到 `static/mp-html/local.html` 里，写在 `tools/config` 中进行构建，会自动添加到需要的地方

**Comment by comxza** [comment]
如果我写在externStyle，是直接写`.aa{color:red};或者#bb{color:red}`，还是需要像`<style>.aa{color:red}</style>`这种写法呢

**Comment by jin-yufeng** [comment]
不需要加 `<style></style>`，直接写 `css` 内容即可

**Comment by comxza** [comment]
好的，谢谢回复

**Comment by comxza** [comment]
我在使用上面方式把css样式写在externStyle，并且编译后放在uniapp对应的目录后运行到h5 
`/components/mp-html/node/node.vue`此文件的style
![12](https://user-images.githubusercontent.com/21981010/126899712-2a0f1cb0-7d6d-41d7-a665-7578a55a29a9.png)
但是实际上的浏览器展示，未识别到我写的class样式 
![13](https://user-images.githubusercontent.com/21981010/126899739-5b017ddb-9de5-40dc-aa63-5b736fb44d43.png)

然后在app端   uni-app编译模式下的nvue  
`/static/app-plus/mp-html/local.html`此文件的style
![134](https://user-images.githubusercontent.com/21981010/126899781-03bb5f59-ed43-4a7c-ab7a-836c4e037b37.png)
但是客户端显示的，border-top: 1px solid #ccc;这个class未识别到吗
![Screenshot_20210725_205701_com yunxun bbs](https://user-images.githubusercontent.com/21981010/126899835-bf956014-e119-4d30-9280-88a6a7ffc1ef.jpg)

**Comment by jin-yufeng** [comment]
`h5` 因为 [这个](https://ask.dcloud.net.cn/question/102899)，确实有问题，我调整一下

**Comment by QLLMr** [comment]
externStyle 构建 不支持 类名带下划线吗？

**Comment by QLLMr** [comment]
您好，tools/config.js 的 externStyle 字段里，例子：  externStyle: '.aaa_bbb{ color: red;}'    构建完成后下划线后面的bbb会被过滤掉，变成了.aaa_{color:red}，这样正常吗？

**Comment by jin-yufeng** [comment]
> 您好，tools/config.js 的 externStyle 字段里，例子： externStyle: '.aaa_bbb{ color: red;}' 构建完成后下划线后面的bbb会被过滤掉，变成了.aaa_{color:red}，这样正常吗？

不正常，我修复一下
