### ISSUE TITLE
如果页面嵌套代码块，小程序端页面可以左右拖动，超出屏幕。

### ISSUE THREAD

**Issue by bruceqiq** [jin-yufeng/mp-html#327]
页面有种下面的这段代码块，这个是在PC端渲染的效果。
![Snipaste_2021-07-26_23-29-31](https://user-images.githubusercontent.com/17756106/127016140-be8d0ca6-38d0-4a7b-ac3d-d93638e6f0f5.png)
下小程序端，会出现下面的情况。
![WechatIMG95](https://user-images.githubusercontent.com/17756106/127016776-cda4d5b1-edae-44b1-a697-dde1d7055812.jpeg)

**Comment by jin-yufeng** [comment]
提供 `html` 内容

**Comment by bruceqiq** [comment]
<section id="nice" data-tool="mdnice编辑器" data-website="https://www.mdnice.com" style="font-size: 16px; color: black; padding: 0 10px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: left; font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"><h2 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; border-bottom: 2px solid rgb(239, 112, 96); font-size: 1.3em;"><span class="prefix" style="display: none;"></span><span class="content" style="display: inline-block; font-weight: bold; background: rgb(239, 112, 96); color: #ffffff; padding: 3px 10px 1px; border-top-right-radius: 3px; border-top-left-radius: 3px; margin-right: 3px;">文章简介</span><span class="suffix"></span><span style="display: inline-block; vertical-align: bottom; border-bottom: 36px solid #efebe9; border-right: 20px solid transparent;"> </span></h2>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">在日常开发中，我们会经常遇到某一张表中某列或者多列的值是唯一的，不能重复插入同一个值。遇到这样的设计，我们一般会设置一个<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">unique</code>的索引。也就是在要求值不能是重复的列或者多列上添加一个唯一索引。例如，会执行这一条SQL语句：</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">alter&nbsp;table&nbsp;table_name&nbsp;add&nbsp;unique&nbsp;[index_name]&nbsp;(col_name(lenght))<br></code></pre>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">或者</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">create&nbsp;unique&nbsp;index&nbsp;index_name&nbsp;on&nbsp;table_name(col_name(length))<br></code></pre>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">这两条语句都表示给表中创建一条唯一索引的字段。</p>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">当我们创建好唯一索引之后，如果给索引列插入了重复值之后，MySQL会报一个下列的错误信息。</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">insert&nbsp;into&nbsp;userinfo(nickname,&nbsp;openid)&nbsp;VALUE&nbsp;(ENCRYPT(RAND()&nbsp;*&nbsp;1000),&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>);<br>--&nbsp;具体得错误信息。<br>Duplicate&nbsp;entry&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>&nbsp;<span class="hljs-keyword" style="color: #f92672; font-weight: bold; line-height: 26px;">for</span>&nbsp;key&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'ixd_openid'</span><br></code></pre>
<blockquote class="multiquote-1" data-tool="mdnice编辑器" style="border: none; display: block; font-size: 0.9em; overflow: auto; overflow-scrolling: touch; border-left: 3px solid rgba(0, 0, 0, 0.4); color: #6a737d; padding-top: 10px; padding-bottom: 10px; padding-left: 20px; padding-right: 10px; margin-bottom: 20px; margin-top: 20px; border-left-color: rgb(239, 112, 96); background: #fff9f9;">
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0px; color: black; line-height: 26px;">表示不能在索引ixd_openid列上重复插入值<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">jf/IxWYA060PA</code>。</p>
</blockquote>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">针对这种情况，我们在业务代码中，可以直接根据改错误信息来做具体得处理。同时也可以让MySQL层面对改情况做处理。下面针对该情况做一个实际案例的颜值。</p>
<h2 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; border-bottom: 2px solid rgb(239, 112, 96); font-size: 1.3em;"><span class="prefix" style="display: none;"></span><span class="content" style="display: inline-block; font-weight: bold; background: rgb(239, 112, 96); color: #ffffff; padding: 3px 10px 1px; border-top-right-radius: 3px; border-top-left-radius: 3px; margin-right: 3px;">表结构</span><span class="suffix"></span><span style="display: inline-block; vertical-align: bottom; border-bottom: 36px solid #efebe9; border-right: 20px solid transparent;"> </span></h2>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">首先我们创建一张userinfo表，表中结构如下：</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">CREATE&nbsp;TABLE&nbsp;`demo`.`userinfo`&nbsp;&nbsp;(<br>&nbsp;&nbsp;`id`&nbsp;int(10)&nbsp;UNSIGNED&nbsp;ZEROFILL&nbsp;NOT&nbsp;NULL&nbsp;AUTO_INCREMENT,<br>&nbsp;&nbsp;`nickname`&nbsp;varchar(255)&nbsp;CHARACTER&nbsp;SET&nbsp;utf8mb4&nbsp;COLLATE&nbsp;utf8mb4_unicode_ci&nbsp;NOT&nbsp;NULL,<br>&nbsp;&nbsp;`openid`&nbsp;varchar(100)&nbsp;CHARACTER&nbsp;SET&nbsp;utf8mb4&nbsp;COLLATE&nbsp;utf8mb4_unicode_ci&nbsp;NOT&nbsp;NULL,<br>&nbsp;&nbsp;PRIMARY&nbsp;KEY&nbsp;(`id`)&nbsp;USING&nbsp;BTREE,<br>&nbsp;&nbsp;UNIQUE&nbsp;INDEX&nbsp;`ixd_openid`(`openid`)&nbsp;USING&nbsp;BTREE<br>)&nbsp;ENGINE&nbsp;=&nbsp;InnoDB&nbsp;AUTO_INCREMENT&nbsp;=&nbsp;20&nbsp;CHARACTER&nbsp;SET&nbsp;=&nbsp;utf8mb4&nbsp;COLLATE&nbsp;=&nbsp;utf8mb4_unicode_ci&nbsp;ROW_FORMAT&nbsp;=&nbsp;Dynamic;<br></code></pre>
<h2 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; border-bottom: 2px solid rgb(239, 112, 96); font-size: 1.3em;"><span class="prefix" style="display: none;"></span><span class="content" style="display: inline-block; font-weight: bold; background: rgb(239, 112, 96); color: #ffffff; padding: 3px 10px 1px; border-top-right-radius: 3px; border-top-left-radius: 3px; margin-right: 3px;">方案实现</span><span class="suffix"></span><span style="display: inline-block; vertical-align: bottom; border-bottom: 36px solid #efebe9; border-right: 20px solid transparent;"> </span></h2>
<h3 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; font-size: 20px;"><span class="prefix" style="display: none;"></span><span class="content">先查询在插入</span><span class="suffix" style="display: none;"></span></h3>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">按照常规的逻辑，我们先查询索引列的值是否存在，如果不存在则插入，存在则返回用户信息。这种方式操作简单，但是在并发情况下，就会存在问题。</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">--&nbsp;先执行查询操作<br>select&nbsp;openid&nbsp;from&nbsp;userinfo&nbsp;<span class="hljs-built_in" style="color: #a6e22e; line-height: 26px;">where</span>&nbsp;openid&nbsp;=&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>;<br>--&nbsp;如果MySQL返回空，表示数据不存在则执行插入操作<br>insert&nbsp;into&nbsp;userinfo(nickname,&nbsp;openid)&nbsp;VALUE&nbsp;(ENCRYPT(RAND()&nbsp;*&nbsp;1000),&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>);<br></code></pre>
<h3 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; font-size: 20px;"><span class="prefix" style="display: none;"></span><span class="content">使用ignore</span><span class="suffix" style="display: none;"></span></h3>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">当我们重复插入数据时，MySQL会返回一个<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">Duplicate entry xxx for xxx</code>的信息，表示该列重复。适用ignore就会忽略该错误信息，只是MySQL不会做插入操作。
<img src="https://gitee.com/bruce_qiq/picture/raw/master/2021-7-18/1626543884385-Snipaste_2021-07-18_01-44-26.png" alt="Snipaste_2021-07-18_01-44-26" style="display: block; margin: 0 auto; max-width: 100%;"></p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">insert&nbsp;ignore&nbsp;into&nbsp;userinfo(nickname,&nbsp;openid)&nbsp;VALUE&nbsp;(ENCRYPT(RAND()&nbsp;*&nbsp;1000),&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>);<br></code></pre>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">增加<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">ignore</code>之后，出现重复插入的情况，MySQL会返回<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">Affected rows: 0</code>。只是插入的数据为条数0，并且id内部也会自增，导致id的值不是连续的。此时我们增加一条不重复的数据，在来查询数据表，就会发现id字段不是连续的。
<img src="https://gitee.com/bruce_qiq/picture/raw/master/2021-7-18/1626543945721-Snipaste_2021-07-18_01-45-35.png" alt="Snipaste_2021-07-18_01-45-35" style="display: block; margin: 0 auto; max-width: 100%;"></p>
<h3 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; font-size: 20px;"><span class="prefix" style="display: none;"></span><span class="content">on duplicate key update</span><span class="suffix" style="display: none;"></span></h3>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">使用该方式插入，当存在重复插入的情况下，MySQL同样的不会返回重复插入的信息。</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">insert&nbsp;&nbsp;into&nbsp;userinfo(nickname,&nbsp;openid)&nbsp;VALUE&nbsp;(ENCRYPT(RAND()&nbsp;*&nbsp;1000),&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>)&nbsp;on&nbsp;duplicate&nbsp;key&nbsp;update&nbsp;openid&nbsp;=&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>;<br></code></pre>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">此时MySQL会返回一个<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">Affected rows: 0</code>信息。只是插入的数据为条数0，并且id内部也会自增，导致id的值不是连续的。</p>
<h3 data-tool="mdnice编辑器" style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; font-size: 20px;"><span class="prefix" style="display: none;"></span><span class="content">replace</span><span class="suffix" style="display: none;"></span></h3>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">使用该方式，会将原来存在的数据进行删除，然后新增一条数据。</p>
<pre class="custom" data-tool="mdnice编辑器" style="margin-top: 10px; margin-bottom: 10px; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.55) 0px 2px 10px;"><span style="display: block; background: url(https://files.mdnice.com/user/3441/876cad08-0422-409d-bb5a-08afec5da8ee.svg); height: 30px; width: 100%; background-size: 40px; background-repeat: no-repeat; background-color: #272822; margin-bottom: -7px; border-radius: 5px; background-position: 10px 10px;"></span><code class="hljs" style="overflow-x: auto; padding: 16px; color: #ddd; display: -webkit-box; font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; font-size: 12px; -webkit-overflow-scrolling: touch; padding-top: 15px; background: #272822; border-radius: 5px;">replace&nbsp;into&nbsp;userinfo(nickname,&nbsp;openid)&nbsp;value(ENCRYPT(RAND()&nbsp;*&nbsp;1000),&nbsp;<span class="hljs-string" style="color: #a6e22e; line-height: 26px;">'jf/IxWYA060PA'</span>);<br></code></pre>
<p data-tool="mdnice编辑器" style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">此时MySQL会返回一个<code style="font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);">Affected rows: 2</code>信息。这里返回2。表示你1条数据被删除的数据，另外新增1条数据。</p>
</section>

**Comment by jin-yufeng** [comment]
我用示例项目没有复现出这个问题，看看有没有设置了什么样式吧，或者提供可复现的 `demo` 项目
