### ISSUE TITLE
请问markdown如何配置

### ISSUE THREAD

**Issue by iamxjb** [jin-yufeng/mp-html#329]
## 无法在微信小程序显示markdown渲染

已在config.js 里启用了markdown：

.......

   'markdown',  // 解析 md

.....

在mp-html里引入了markdown插件，在wxml里代码如下：

<pre><code>
 《mp-html content="{{ detail.content }}" bindlinktap="ATap" copy-link="{{false}}" selectable="{{true}}" lazy-load="{{true}}"  markdown="{{true}}" /》</code> </pre>

请问上述配置哪里有问题，导致无法显示markdown的渲染效果

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目

**Comment by iamxjb** [comment]
我找到了原因如果markdown代码外边包裹一层p或div标签，会导致无法正常显示markdown，比如

`<div>## 这段是markdown</div>`

**Comment by jin-yufeng** [comment]
`markdown` 解析是通过 [marked](https://github.com/markedjs/marked) 实现的，被 `html` 标签包裹的应该就不认为是 `markdown` 内容了
