### ISSUE TITLE
a 标签 style 里包含 display: inline-block; 时默认事件未绑定

### ISSUE THREAD

**Issue by 1107115073** [jin-yufeng/mp-html#332]
## 使用环境  
小程序基础包： 2.18
mp-html: 2.1.4

## 问题描述  
a 标签 style 里包含 display: inline-block;  时默认事件未绑定。

### 异常代码截图
![image](https://ftp.bmp.ovh/imgs/2021/07/1a9a81ea93c39a94.png)

### 正常代码截图
![image](https://ftp.bmp.ovh/imgs/2021/07/7f9b671ff4e19a37.png)

## 复现方式  

使用说明：由于代码片段分享有大小限制，因此导入代码片段要执行 ` npm install  `安装依赖包，再使用小程序工具构建 `npm`

小程序代码：``` https://developers.weixin.qq.com/s/fVihhbmS7Esm ```

分享截图：
![image](https://ftp.bmp.ovh/imgs/2021/07/ed245810999e997f.png)

**Comment by 1107115073** [comment]
大佬，预计什么时候能发布新版本呢。

**Comment by jin-yufeng** [comment]
已发布
