### ISSUE TITLE
编译到微信小程序是发生错误页面【components/mp-html/mp-html]错误:  Error: This application has not registered any plugins yet.

### ISSUE THREAD

**Issue by wYuJian** [jin-yufeng/mp-html#333]
通过npm方式打包成组件方式编译到微信小程序发生错误 
![image](https://user-images.githubusercontent.com/29095188/127797685-2007f90a-9781-4e0e-9af3-5711bcf33cf1.png)
![image](https://user-images.githubusercontent.com/29095188/127797713-ab8d0a74-ce7b-4b53-aef3-4d9996e2799e.png)
![image](https://user-images.githubusercontent.com/29095188/127797736-556aa940-996e-487c-8659-96ee83560cfd.png)

**Comment by jin-yufeng** [comment]
参考 #247

**Comment by wYuJian** [comment]
> 参考 #247

好的，3Q，domain主域名设置在小程序中是无效的吗？

**Comment by jin-yufeng** [comment]
有效的，没有用的话提供可复现的 `demo` 项目
