### ISSUE TITLE
请问如何实现特定链接跳转，其余链接被拷贝到剪贴板？

### ISSUE THREAD

**Issue by missMHWGO** [jin-yufeng/mp-html#334]
![image](https://user-images.githubusercontent.com/14312158/127861259-db92111c-2ca3-479f-b863-4fc0d153faa1.png)

**Comment by missMHWGO** [comment]
或者建议 copy-link 改成 (e) => boolean

**Comment by jin-yufeng** [comment]
把 [copy-link](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=copy-link) 属性设置为 `false`，然后 `linktap` 事件里  
```javascript
linktap(e) {
  if (xxx) {
    // 自定义跳转
  } else {
    wx.setClipboardData({
      data: e.detail.href
    })
  }
}
```

**Comment by missMHWGO** [comment]
是的，现在是这么做的，感谢～
