### ISSUE TITLE
ql-align-right未能识别出样式

### ISSUE THREAD

**Issue by liuyue1212** [jin-yufeng/mp-html#336]
[{"name":"p","attrs":{"class":"ql-align-right"},"children":[{"name":"span","attrs":{"style":"color:rgb(127, 127, 127)"},"children":[{"type":"text","text":"123"}]}]}]

[{"name":"p","attrs":{"class":"ql-align-center","style":"text-align:center"},"children":[{"name":"span","attrs":{"style":"color:rgb(127, 127, 127)"},"children":[{"type":"text","text":"123"}]}]}]
center正常

**Comment by liuyue1212** [comment]
完整的html:
content == <p><span style="color: rgb(127, 127, 127);">更多课程在陆续制作中非常感谢！</span></p><p><br></p><p><br></p><p class="ql-align-right"><br></p><p><span style="color: rgb(127, 127, 127);">特别鸣谢：</span></p><p class="ql-align-right"><br></p><p class="ql-align-center"><span style="color: rgb(127, 127, 127);">主&nbsp;&nbsp;讲：宋拯源</span></p><p class="ql-align-right"><span style="color: rgb(127, 127, 127);">出&nbsp;&nbsp;演：何剑&nbsp;杨博文</span></p>

**Comment by liuyue1212** [comment]
`content == <p><span style="color: rgb(127, 127, 127);">这是急视救与重庆市急救医疗中心联合自制的课程，更多课程在陆续制作中。内容有任何问题或建议请在“急视飞救”微信公众号给我们留言，让我们共同制作出高质量的属于我们自己的急救课程，非常感谢！</span></p><p><br></p><p><br></p><p class="ql-align-right"><br></p><p><span style="color: rgb(127, 127, 127);">特别鸣谢：</span></p><p class="ql-align-right"><br></p><p class="ql-align-center"><span style="color: rgb(127, 127, 127);">主&nbsp;&nbsp;讲：宋拯源</span></p><p class="ql-align-right"><span style="color: rgb(127, 127, 127);">出&nbsp;&nbsp;演：何剑&nbsp;杨博文</span></p>`

**Comment by liuyue1212** [comment]
完整的html:
`content == <p><span style="color: rgb(127, 127, 127);">更多课程在陆续制作中。</span></p><p><br></p><p><br></p><p class="ql-align-right"><br></p><p><span style="color: rgb(127, 127, 127);">特别鸣谢：</span></p><p class="ql-align-right"><br></p><p class="ql-align-center"><span style="color: rgb(127, 127, 127);">主&nbsp;&nbsp;讲：宋拯源</span></p><p class="ql-align-right"><span style="color: rgb(127, 127, 127);">出&nbsp;&nbsp;演：何剑&nbsp;杨博文</span></p>`

**Comment by liuyue1212** [comment]
另外可以支持识别iframe吗？目前只是简单的替换成video标签。

**Comment by jin-yufeng** [comment]
`align-center` 用的比较多，所以在解析时做了 [特殊处理](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/parser.js#L633)  
其他样式需要自行引入（参考 [外部样式](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=setting)），把   
```css
.ql-align-right {
  text-align: right;
}
```
加到 `tools/config.js` 中的 [externStyle](https://github.com/jin-yufeng/mp-html/blob/master/tools/config.js#L30) 字段里，然后执行  
```bash
npm install
npm run build
```
然后把 `dist` 中的内容拷贝到项目中使用

**Comment by jin-yufeng** [comment]
小程序中不支持 `iframe`，如果是腾讯视频的链接可以用 [腾讯视频插件](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=txv-video) 显示

**Comment by liuyue1212** [comment]
> `align-center` 用的比较多，所以在解析时做了 [特殊处理](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/parser.js#L633)
> 其他样式需要自行引入（参考 [外部样式](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=setting)），把
> 
> ```css
> .ql-align-right {
>   text-align: right;
> }
> ```
> 
> 加到 `tools/config.js` 中的 [externStyle](https://github.com/jin-yufeng/mp-html/blob/master/tools/config.js#L30) 字段里，然后执行
> 
> ```shell
> npm install
> npm run build
> ```
> 
> 然后把 `dist` 中的内容拷贝到项目中使用

谢谢！

**Comment by liuyue1212** [comment]
> `align-center` 用的比较多，所以在解析时做了 [特殊处理](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/parser.js#L633)
> 其他样式需要自行引入（参考 [外部样式](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=setting)），把
> 
> ```css
> .ql-align-right {
>   text-align: right;
> }
> ```
> 
> 加到 `tools/config.js` 中的 [externStyle](https://github.com/jin-yufeng/mp-html/blob/master/tools/config.js#L30) 字段里，然后执行
> 
> ```shell
> npm install
> npm run build
> ```
> 
> 然后把 `dist` 中的内容拷贝到项目中使用
