### ISSUE TITLE
对富文本类容的截取

### ISSUE THREAD

**Issue by comxza** [jin-yufeng/mp-html#337]
## 问题描述  
我想把这个富文本类容用作于列表，但这个我需要怎么截取不让他全部显示出来呢，如下图
![image](https://user-images.githubusercontent.com/21981010/128979609-ae5ebca5-a99e-444c-94fe-54c3c3abac6f.png)

**Comment by jin-yufeng** [comment]
用 `css` 里的 [-webkit-line-clamp](https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-line-clamp) 吧
