### ISSUE TITLE
富文本编辑后，通过什么事件获取编辑后的内容啊？自定义保存按钮吗

### ISSUE THREAD

**Issue by Funny-dot** [jin-yufeng/mp-html#339]
## 问题描述  
富文本编辑后，通过什么事件获取编辑后的内容啊？自定义保存按钮吗

**Comment by jin-yufeng** [comment]
目前没有事件可以获取，编辑完成后，调用组件实例上的 `getContent` 方法获取编辑后的 `html` 内容
