### ISSUE TITLE
在Taro中如何使用？

### ISSUE THREAD

**Issue by qiufeng5LIFE** [jin-yufeng/mp-html#340]
## 新功能描述
不支持在Taro中使用吗？

**Comment by jin-yufeng** [comment]
参考 [文档](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=other)

**Comment by jin-yufeng** [comment]
参考 [文档](https://nervjs.github.io/taro/docs/hybrid#%E4%BD%BF%E7%94%A8%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6) 可以引入原生组件包使用
