### ISSUE TITLE
希望支持传入自定义的`linkTap`方法覆盖默认逻辑

### ISSUE THREAD

**Issue by sws797** [jin-yufeng/mp-html#343]
## 新功能描述
例如：支持传入自定义方法，覆盖原有的`linktap`逻辑

## 应用场景
富文本内容由网页端编辑，文本内超链接连接到同站点下的页面。
在小程序中配置了`@linktap`，所以点击该链接也可以跳转到小程序中对应的页面。

但是因为链接中含有`://`，在`linkTap`默认逻辑中会识别成外部链接，即使可以在小程序内部跳转，也会弹出“链接已复制”

## 临时办法
小程序渲染富文本内容时，将小程序可以跳转的链接转化成小程序链接，匹配`linkTap`的逻辑

**Comment by jin-yufeng** [comment]
把 [copy-link](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=copy-link) 设置成 `false` 就可以屏蔽默认的自动复制了  
然后就可以在 [linktap](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=linktap) 事件里自定义处理

**Comment by sws797** [comment]
> 把 [copy-link](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=copy-link) 设置成 `false` 就可以屏蔽默认的自动复制了
> 然后就可以在 [linktap](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=linktap) 事件里自定义处理

谢谢，是我看错地方看到`miniprogram`里面去了，也没有仔细看文档😂
