### ISSUE TITLE
在 taro3 中使用，图片点击事件不触发

### ISSUE THREAD

**Issue by ZhangJiL** [jin-yufeng/mp-html#344]
使用如下： `<mp-html content={htmlContent} onImgtap={tapImg} />`  现在内容可以正常显示，但是图片的点击事件一直不触发。

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目

**Comment by ZhangJiL** [comment]
[https://github.com/jin-yufeng/mp-html/issues/344](demo 地址)

你好，现在发现问题出在了图片 src 属性上，详情见 demo 。谢谢

**Comment by jin-yufeng** [comment]
试了一下，`taro` 里这样引入图片会被转为 `base64`，然后目前的设计上是屏蔽 `base64` 图片的事件的，详见 #249

**Comment by ZhangJiL** [comment]
了解，谢谢。现在遇到另外一个问题， `preview-img` 设置为 `false` ,但是点击图片还是会弹出预览。可参考之前的 demo

**Comment by jin-yufeng** [comment]
写成 `previewImg` 吧，`preview-img` `taro` 好像识别不到

**Comment by ZhangJiL** [comment]
谢谢，可以实现效果
