### ISSUE TITLE
后台返回节点中的属性到小程序中就没有了？

### ISSUE THREAD

**Issue by chenzhenyu222** [jin-yufeng/mp-html#347]
## 问题描述  
后台返回的文本格式如下：
```
<tag data-attr="attrValue">要渲染的节点</tag>
```
渲染到微信小程序后只有
```
<view class="_span">
  <text>要渲染的节点</text>
</view>
```

我需要为节点添加事件，需要后台返回的这个属性，想请教一下这个应该怎么做？

**Comment by jin-yufeng** [comment]
目前只有 `img` 和 `a` 标签支持点击事件，这两个标签的 `data-` 属性会被保留，并在 [imgtap](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=imgtap) 和 [linktap](https://jin-yufeng.gitee.io/mp-html/#/basic/event?id=linktap) 事件中返回  
其余标签为减小解析结果大小会移除 `data-` 属性
