### ISSUE TITLE
兄弟，请问微信小程序的table样式怎么自定义呢

### ISSUE THREAD

**Issue by xuehengfei** [jin-yufeng/mp-html#348]
table的源数据是常规的<table></table>格式的，在小程序上显示时，表格的样式该怎么控制呢

**Comment by xuehengfei** [comment]
![12](https://user-images.githubusercontent.com/30588181/131474663-cdcf90c4-cc6e-473c-bb01-b0ec132afab4.png)
附上table在小程序的效果，我想让单边框

**Comment by xuehengfei** [comment]
![12](https://user-images.githubusercontent.com/30588181/131474663-cdcf90c4-cc6e-473c-bb01-b0ec132afab4.png)
附上table在小程序的效果，我想让单边框

**Comment by jin-yufeng** [comment]
`html` 里 `table` 的样式怎么控制就怎么控制呗  
如果 [浏览器](https://jin-yufeng.gitee.io/mp-html/#/question/feedback?id=notice) 渲染的效果和小程序里不一样可以提供可复现的 `html` 内容
