### ISSUE TITLE
是否可以提过示例程序的源码，想要示例中的工具栏

### ISSUE THREAD

**Issue by LuceLuo** [jin-yufeng/mp-html#354]
是否可以提过示例程序的源码，想要示例中的工具栏

**Comment by jin-yufeng** [comment]
`editable` 的示例 [代码片段](https://developers.weixin.qq.com/s/LkxKpvmo7Ks2) 里有这个工具栏

**Comment by LuceLuo** [comment]
> `editable` 的示例 [代码片段](https://developers.weixin.qq.com/s/LkxKpvmo7Ks2) 里有这个工具栏

收到，感谢
