### ISSUE TITLE
问问大伙QQ小程序审核的问题.

### ISSUE THREAD

**Issue by Y-A-K-E** [jin-yufeng/mp-html#355]
我昨天提交小程序审核:

`您好，您的小程序存在链接/文案等引导用户跳出QQ外站的行为，请修改后再提审.`

好像点击链接复制是被QQ禁止的.我小程序审核失败了.大家是怎么处理的.

**Comment by ren2436** [comment]
把复制链接的功能关掉呗

**Comment by Y-A-K-E** [comment]
![QQ图片20210918133235](https://user-images.githubusercontent.com/6988291/133874033-c613d27b-172f-4071-b021-f27c9f844531.png)

大家看看.
