### ISSUE TITLE
富文本编译器里面图片地址问题

### ISSUE THREAD

**Issue by Anonymeg** [jin-yufeng/mp-html#359]
`在编译器中，我通过`this.$refs.article.getSrc`上传一个图片到服务器，返回了一个线上地址。`
当前图片的src默认是本地的路径，请问我怎么把这个返回的地址放到当前的图片的src上。

**Comment by jin-yufeng** [comment]
`getSrc` 方法怎么设置的，返回线上地址的话应该设置的就是线上地址吧

**Comment by Anonymeg** [comment]
你好，解决了，下面代码覆盖了上面的内容，谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jin-yufeng/mp-html"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月2日(星期六) 中午1:58
***@***.***&gt;;
抄送:&nbsp;"Ver __________聼╰→♪ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jin-yufeng/mp-html] 富文本编译器里面图片地址问题 (#359)





 
getSrc 方法怎么设置的，返回线上地址的话应该设置的就是线上地址吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
