### ISSUE TITLE
table嵌套的富文本中，image标签max-width显示无效

### ISSUE THREAD

**Issue by ren2436** [jin-yufeng/mp-html#362]
## 使用环境  

平台：原生微信小程序
经测试 uniapp也存在

## 问题描述  

富文本中，图片的外层有 table/tr/td 元素包裹，这些table属性 如：
``` css
display: table;
display: table-row;
display: table-cell;
```
 会导致 image标签的 max-width 无效，显示的尺寸为最终的width和height尺寸
最终的结果就是出现横向滚动条
![image](https://user-images.githubusercontent.com/8308372/139782220-4e89e558-5198-4a6e-a59b-76a866f6ad41.png)

## 复现方式  

富文本内容
``` html
<table>
  <tr>
    <td>
      <img  src="https://user-images.githubusercontent.com/8308372/139782220-4e89e558-5198-4a6e-a59b-76a866f6ad41.png" />
    </td>
  </tr>
</table>
```

**Comment by ren2436** [comment]
手动将table的这些属性 修改为 display: block; 问题即可解决
还有什么办法，既保留table属性 又能解决横向滚动的问题

**Comment by jin-yufeng** [comment]
是有这个问题，可以给 `table` 加上 `style="table-layout:fixed;width:100%"`
