### ISSUE TITLE
想问一下为什么移除input标签

### ISSUE THREAD

**Issue by zhangaichen** [jin-yufeng/mp-html#364]
想问一下为什么移除input标签，我的需求可能需要input，是否可以放开input，如何放开？我试着删除input，但是还是不显示
![image](https://user-images.githubusercontent.com/24717970/140446648-2de711bb-57ca-45c8-b14c-3d3eb3cd9838.png)

**Comment by jin-yufeng** [comment]
富文本一般不包含表单组件吧，编辑器好像也没有添加表单组件的  
要添加把这里去掉是不够的，还要在 [模板文件](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/node/node.wxml#L33) 里配置需要的属性和事件

**Comment by zhangaichen** [comment]
Duplicate of # 感谢，我是用富文本去写样式，所以用到了input，如果放开input对于小程序的发版和使用没有影响，我就放开input标签了

**Comment by zhangaichen** [comment]
div 下如果有input input会不显示，放在a标签里可以

**Comment by zhangaichen** [comment]
在ios上 多次点击非滚动区域的内容，会出现弹窗的滚动内容滚动无效 ，代码片段如下：
const changeStyle = (obj = {}) => {
  let style = '';
  Object.keys(obj).forEach((item) => {
    style += `${item}:${obj[item] ? obj[item] : '\'\''};`;
  });
  return style;
};

 const styles = {
      [`${clsPrefix}_overlay`]: {
        width: '100%',
        height: '100%',
        'z-index': 999,
        position: 'fixed',
        background: '#03000F',
        opacity: '0.6',
      },
      [`${clsPrefix}_sku-popup`]: {
        left: 0,
        top: 0,
        width: '100%',
        'max-height': '80%',
        'z-index': 999,
        position: 'fixed',
        background: "#fff",
        bottom: '0',
        padding: '30rpx',
        'border-radius': '20rpx 20rpx 0px 0px',
        'box-sizing': 'border-box',
      },
      [`${clsPrefix}_goods-box`]: {
        display: 'flex',
      },
      [`${clsPrefix}_goods-img`]: {
        width: '180rpx',
        height: '180rpx'
      },
      [`${clsPrefix}_goods-price`]: {
        'margin-left': '20rpx',
        'font-size': '0'
      },
      [`${clsPrefix}_red-number-price`]: {
        color: '#FF4C29',
        'font-size': '40rpx'
      },
      [`${clsPrefix}_red-symbol-price`]: {
        color: '#FF4C29',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_red-decimal-price`]: {
        color: '#FF4C29',
        'font-size': '34rpx'
      },
      [`${clsPrefix}_red-del-price`]: {
        color: '#999999',
        'font-size': '26rpx',
        'margin-left': '10rpx'
      },
      [`${clsPrefix}_bottom-symbol-price`]: {
        color: '#333333',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_bottom-number-price`]: {
        color: '#333333',
        'font-size': '28rpx'
      },
      [`${clsPrefix}_bottom-decimal-price`]: {
        color: '#333333',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_bottom-vip-icon`]: {
        'width': '88rpx',
        'margin-left': '10rpx',
      },
      [`${clsPrefix}_bottom-box-price`]: {
        'display': 'flex',
        'align-items': 'center',
      },
      [`${clsPrefix}_surplusn-num`]: {
        'font-size': '24rpx',
        'font-weight': '400',
        'color': '#999',
        'margin-top': '18rpx',
        'line-height': '24rpx'
      },
      [`${clsPrefix}_select-attribute`]: {
        'font-size': '28rpx',
        'font-weight': '400',
        'color': '#333',
        'margin-top': '20rpx',
        'line-height': '28rpx',
      },
      [`${clsPrefix}_close-icon`]: {
        width: '50rpx',
        'position': 'absolute',
        'right': '30rpx',
        'top': '30rpx'
      },
      [`${clsPrefix}_sku-title`]: {
        'font-size':'28rpx',
        'font-weight':500,
        color:'#333',
        'line-height':'40rpx'
      },
      [`${clsPrefix}_sku-select-type`]: {
        border: '2rpx solid #FF4C29',
        background: 'rgba(255, 76, 41, 0.1)',
        'color':'#FF4C29',
      },
      [`${clsPrefix}_sku-type`]: {
        background: '#F2F2F2',
        'border-radius': '28rpx',
        padding:'8rpx 80rpx',
        'color':'#333',
        'font-size':'24rpx',
        'margin-right':'20rpx',
        'margin-top':'20rpx',
        display: 'inline-block',
      },
      [`${clsPrefix}_sku`]: {
        'overflow-y':'scroll',
        'max-height':'460rpx'
      },
      [`${clsPrefix}_sku-box`]: {
        'padding-top':'50rpx'
      },
      [`${clsPrefix}_sku-type-box`]: {
        'margin-left':'0',
      },
      [`${clsPrefix}_quantity-box`]: {
        'display':'flex',
        'justify-content': 'space-between',
        'margin-top':'50rpx',
      },
      [`${clsPrefix}_quantity-number-box`]: {
        'display':'flex',
      },
      [`${clsPrefix}_quantity-number-operation`]: {
        'width': '50rpx',
        'height': '50rpx',
        'background': '#F2F2F2',
        'border-radius': '6rpx 0px 0px 6rpx',
        'color':'#333',
        'text-align':'center'
      },
      [`${clsPrefix}_quantity-number`]: {
        width: '100rpx',
        height: '50rpx',
        background: '#F2F2F2',
        'font-size':'24rpx',
        color:'#333',
        'text-align':'center',
        'margin':'0 4rpx',
      },
      [`${clsPrefix}_btn-submit`]: {
        'width': '688rpx',
        height: '80rpx',
        background: '#FF4C29',
        'border-radius': '40rpx',
        'text-align':'center',
        'font-weight': 500,
        color: '#FFF',
        'line-height': '80rpx',
        'margin-top':'46rpx'
      },
    };
   const html = `
    <a style="${changeStyle(styles[`${clsPrefix}_overlay`])}" type="close">
    </a>
    <div style="${changeStyle(styles[`${clsPrefix}_sku-popup`])}">
      <div style="${changeStyle(styles[`${clsPrefix}_goods-box`])}">
        <img style="${changeStyle(styles[`${clsPrefix}_goods-img`])}" src="https://pre-omo.aiyouyi.cn/thumbnail/180x200000/999/image/31207/9fb5d571cb7e46acac912daef3ba2d62.jpg" />
        <div style="${changeStyle(styles[`${clsPrefix}_goods-price`])}">
          <div style="line-height:36rpx">
            <span style="${changeStyle(styles[`${clsPrefix}_red-symbol-price`])}">¥</span>
            <span style="${changeStyle(styles[`${clsPrefix}_red-number-price`])}">99</span>
            <span style="${changeStyle(styles[`${clsPrefix}_red-decimal-price`])}">.00</span>
            <del style="${changeStyle(styles[`${clsPrefix}_red-del-price`])}">¥ 165.00</del>
          </div>
          <div style="${changeStyle(styles[`${clsPrefix}_bottom-box-price`])}">
            <div>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-symbol-price`])}">¥</span>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-number-price`])}">99</span>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-decimal-price`])}">.00</span>
            </div>
            <img style="${changeStyle(styles[`${clsPrefix}_bottom-vip-icon`])}" src="https://omo.aiyouyi.cn/web-file/wx/app/images/vip9.png" />
          </div>
          <p style="${changeStyle(styles[`${clsPrefix}_surplusn-num`])}">剩余442件</p>
          <p style="${changeStyle(styles[`${clsPrefix}_select-attribute`])}">已选:"黑色""M"</p>
        <div>
        <img 
          type="close" 
          src="https://test-omo.aiyouyi.cn/web-file/wx/app/images/gui/grayCancle.png" 
          style="${changeStyle(styles[`${clsPrefix}_close-icon`])}"
          />
        </div>
      </div>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_sku`])}" type="scrollView">
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_quantity-box`])}">
      <div style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">数量</div>
      <div style="${changeStyle(styles[`${clsPrefix}_quantity-number-box`])}">
        <a style="${changeStyle(styles[`${clsPrefix}_quantity-number-operation`])}">-</a>
        <input type="number" style="${changeStyle(styles[`${clsPrefix}_quantity-number`])}"/>
        <a style="${changeStyle(styles[`${clsPrefix}_quantity-number-operation`])}">+</a>
      </div>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_btn-submit`])}">确定</div>
    </div>  
    `;

**Comment by zhangaichen** [comment]
` const styles = {
      [`${clsPrefix}_overlay`]: {
        width: '100%',
        height: '100%',
        'z-index': 999,
        position: 'fixed',
        background: '#03000F',
        opacity: '0.6',
      },
      [`${clsPrefix}_sku-popup`]: {
        left: 0,
        top: 0,
        width: '100%',
        'max-height': '80%',
        'z-index': 999,
        position: 'fixed',
        background: "#fff",
        bottom: '0',
        padding: '30rpx',
        'border-radius': '20rpx 20rpx 0px 0px',
        'box-sizing': 'border-box',
      },
      [`${clsPrefix}_goods-box`]: {
        display: 'flex',
      },
      [`${clsPrefix}_goods-img`]: {
        width: '180rpx',
        height: '180rpx'
      },
      [`${clsPrefix}_goods-price`]: {
        'margin-left': '20rpx',
        'font-size': '0'
      },
      [`${clsPrefix}_red-number-price`]: {
        color: '#FF4C29',
        'font-size': '40rpx'
      },
      [`${clsPrefix}_red-symbol-price`]: {
        color: '#FF4C29',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_red-decimal-price`]: {
        color: '#FF4C29',
        'font-size': '34rpx'
      },
      [`${clsPrefix}_red-del-price`]: {
        color: '#999999',
        'font-size': '26rpx',
        'margin-left': '10rpx'
      },
      [`${clsPrefix}_bottom-symbol-price`]: {
        color: '#333333',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_bottom-number-price`]: {
        color: '#333333',
        'font-size': '28rpx'
      },
      [`${clsPrefix}_bottom-decimal-price`]: {
        color: '#333333',
        'font-size': '24rpx'
      },
      [`${clsPrefix}_bottom-vip-icon`]: {
        'width': '88rpx',
        'margin-left': '10rpx',
      },
      [`${clsPrefix}_bottom-box-price`]: {
        'display': 'flex',
        'align-items': 'center',
      },
      [`${clsPrefix}_surplusn-num`]: {
        'font-size': '24rpx',
        'font-weight': '400',
        'color': '#999',
        'margin-top': '18rpx',
        'line-height': '24rpx'
      },
      [`${clsPrefix}_select-attribute`]: {
        'font-size': '28rpx',
        'font-weight': '400',
        'color': '#333',
        'margin-top': '20rpx',
        'line-height': '28rpx',
      },
      [`${clsPrefix}_close-icon`]: {
        width: '50rpx',
        'position': 'absolute',
        'right': '30rpx',
        'top': '30rpx'
      },
      [`${clsPrefix}_sku-title`]: {
        'font-size':'28rpx',
        'font-weight':500,
        color:'#333',
        'line-height':'40rpx'
      },
      [`${clsPrefix}_sku-select-type`]: {
        border: '2rpx solid #FF4C29',
        background: 'rgba(255, 76, 41, 0.1)',
        'color':'#FF4C29',
      },
      [`${clsPrefix}_sku-type`]: {
        background: '#F2F2F2',
        'border-radius': '28rpx',
        padding:'8rpx 80rpx',
        'color':'#333',
        'font-size':'24rpx',
        'margin-right':'20rpx',
        'margin-top':'20rpx',
        display: 'inline-block',
      },
      [`${clsPrefix}_sku`]: {
        'overflow-y':'scroll',
        'max-height':'460rpx'
      },
      [`${clsPrefix}_sku-box`]: {
        'padding-top':'50rpx'
      },
      [`${clsPrefix}_sku-type-box`]: {
        'margin-left':'0',
      },
      [`${clsPrefix}_quantity-box`]: {
        'display':'flex',
        'justify-content': 'space-between',
        'margin-top':'50rpx',
      },
      [`${clsPrefix}_quantity-number-box`]: {
        'display':'flex',
      },
      [`${clsPrefix}_quantity-number-operation`]: {
        'width': '50rpx',
        'height': '50rpx',
        'background': '#F2F2F2',
        'border-radius': '6rpx 0px 0px 6rpx',
        'color':'#333',
        'text-align':'center'
      },
      [`${clsPrefix}_quantity-number`]: {
        width: '100rpx',
        height: '50rpx',
        background: '#F2F2F2',
        'font-size':'24rpx',
        color:'#333',
        'text-align':'center',
        'margin':'0 4rpx',
      },
      [`${clsPrefix}_btn-submit`]: {
        'width': '688rpx',
        height: '80rpx',
        background: '#FF4C29',
        'border-radius': '40rpx',
        'text-align':'center',
        'font-weight': 500,
        color: '#FFF',
        'line-height': '80rpx',
        'margin-top':'46rpx'
      },
    };
   const html = `
    <a style="${changeStyle(styles[`${clsPrefix}_overlay`])}" type="close">
    </a>
    <div style="${changeStyle(styles[`${clsPrefix}_sku-popup`])}">
      <div style="${changeStyle(styles[`${clsPrefix}_goods-box`])}">
        <img style="${changeStyle(styles[`${clsPrefix}_goods-img`])}" src="https://pre-omo.aiyouyi.cn/thumbnail/180x200000/999/image/31207/9fb5d571cb7e46acac912daef3ba2d62.jpg" />
        <div style="${changeStyle(styles[`${clsPrefix}_goods-price`])}">
          <div style="line-height:36rpx">
            <span style="${changeStyle(styles[`${clsPrefix}_red-symbol-price`])}">¥</span>
            <span style="${changeStyle(styles[`${clsPrefix}_red-number-price`])}">99</span>
            <span style="${changeStyle(styles[`${clsPrefix}_red-decimal-price`])}">.00</span>
            <del style="${changeStyle(styles[`${clsPrefix}_red-del-price`])}">¥ 165.00</del>
          </div>
          <div style="${changeStyle(styles[`${clsPrefix}_bottom-box-price`])}">
            <div>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-symbol-price`])}">¥</span>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-number-price`])}">99</span>
              <span style="${changeStyle(styles[`${clsPrefix}_bottom-decimal-price`])}">.00</span>
            </div>
            <img style="${changeStyle(styles[`${clsPrefix}_bottom-vip-icon`])}" src="https://omo.aiyouyi.cn/web-file/wx/app/images/vip9.png" />
          </div>
          <p style="${changeStyle(styles[`${clsPrefix}_surplusn-num`])}">剩余442件</p>
          <p style="${changeStyle(styles[`${clsPrefix}_select-attribute`])}">已选:"黑色""M"</p>
        <div>
        <img 
          type="close" 
          src="https://test-omo.aiyouyi.cn/web-file/wx/app/images/gui/grayCancle.png" 
          style="${changeStyle(styles[`${clsPrefix}_close-icon`])}"
          />
        </div>
      </div>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_sku`])}" type="scrollView">
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
      <dl style="${changeStyle(styles[`${clsPrefix}_sku-box`])}">
        <dt style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">颜色</dt>
        <dd style="${changeStyle(styles[`${clsPrefix}_sku-type-box`])}">
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])} ${changeStyle(styles[`${clsPrefix}_sku-select-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
          <a style="${changeStyle(styles[`${clsPrefix}_sku-type`])}">黑色</a>
        </dd>
      </dl>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_quantity-box`])}">
      <div style="${changeStyle(styles[`${clsPrefix}_sku-title`])}">数量</div>
      <div style="${changeStyle(styles[`${clsPrefix}_quantity-number-box`])}">
        <a style="${changeStyle(styles[`${clsPrefix}_quantity-number-operation`])}">-</a>
        <input type="number" style="${changeStyle(styles[`${clsPrefix}_quantity-number`])}"/>
        <a style="${changeStyle(styles[`${clsPrefix}_quantity-number-operation`])}">+</a>
      </div>
    </div>
    <div style="${changeStyle(styles[`${clsPrefix}_btn-submit`])}">确定</div>
    </div>  
    `;`

**Comment by zhangaichen** [comment]
`
const changeStyle = (obj = {}) => {
let style = '';
Object.keys(obj).forEach((item) => {
style += ${item}:${obj[item] ? obj[item] : '\'\''};;
});
return style;
};
`

**Comment by zhangaichen** [comment]
@jin-yufeng
