### ISSUE TITLE
rem字体会被自动替换掉

### ISSUE THREAD

**Issue by konatatenshi** [jin-yufeng/mp-html#365]
APP因为做了字体调整，于是内容加入了rem，但是类似`<font size="4rem">1.</font>`这种，会被替换掉rem从而无法让APP自动调整字体大小。

**Comment by jin-yufeng** [comment]
`font` 标签的 `size` 属性只能是 `1-7` 之间的数字，表示字体的大小（[详细](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font#attr-size)）  
要设置单位的话应该用 `style="font-size: 4rem"`

**Comment by konatatenshi** [comment]
OK，草率了
