### ISSUE TITLE
txv-video是否支持nvue模式

### ISSUE THREAD

**Issue by comxza** [jin-yufeng/mp-html#367]
## 问题描述  
txv-video是否支持nvue模式下，我看文档说的是h5和app，不知道这个app是否包含nvue模式下
![image](https://user-images.githubusercontent.com/21981010/141789555-88ccdeff-affe-408b-946a-2b2843c4ccdc.png)

**Comment by jin-yufeng** [comment]
`uni-app` 的 `h5` 和 `app` 端（包含 `nvue`）是可以直接使用 `iframe` 标签的（即不需要使用该插件就可以播放）  
小程序端无法使用 `iframe` 标签，要播放腾讯视频的话就需要该插件进行替换

**Comment by comxza** [comment]
哦哦哦好的明白  谢谢，
顺便我在使用中有这样一个问题，zai'shi在使用代码块的时候  ，config开启了highlight，但是解析的时候如下图   ，并无高亮呢
![image](https://user-images.githubusercontent.com/21981010/141793343-63ee48c4-418e-4935-82ac-79cfc4a6110e.png)

![image](https://user-images.githubusercontent.com/21981010/141793293-3538a1f0-4677-4ef3-ab80-eee347ce1b50.png)
我返回的数据结构也是<pre><code class="language-php">里面是代码</code></pre>
![image](https://user-images.githubusercontent.com/21981010/141793465-b9d8c2a3-10f9-4812-891a-db87d48ec842.png)

**Comment by jin-yufeng** [comment]
默认配置不支持 `php` 语言，要去 [prismjs](https://prismjs.com/) 官网下载包含 `php` 的 `prism.min.js` 替换 `plugins/highlight/` 下的文件，然后重新构建

**Comment by comxza** [comment]
我先去[prismjs](https://prismjs.com/index.html)
选择了所有语言，
![image](https://user-images.githubusercontent.com/21981010/141884236-7b949e78-fb96-48bb-b46f-5a626cee3d2e.png)
然后下载了js和css
![image](https://user-images.githubusercontent.com/21981010/141884303-d649b418-dc50-4ac0-a96d-1b571694170d.png)
并且替换了这两个，
![image](https://user-images.githubusercontent.com/21981010/141884345-bc809ffc-16c7-448a-9983-1c5691a573c1.png)
然后编译成，我把编译好的复制到项目根目录。也就是，r如下图，这两个文件夹
![image](https://user-images.githubusercontent.com/21981010/141884393-333a8d68-008c-402a-b320-bcdc55638671.png)
![image](https://user-images.githubusercontent.com/21981010/141884453-8e6e75a5-1505-46fc-9805-4bc52b8d876f.png)
但是最终运行到app，出现以下错误
![image](https://user-images.githubusercontent.com/21981010/141884499-89134853-4d9e-4a6b-8a2f-498208563737.png)
，这是什么原因造成的呢

**Comment by jin-yufeng** [comment]
选择所有语言后文件过大，会被跳过 `ES6 转 ES5` 的处理，然后这个 `extend` 方法是 `es6` 的方法导致了报错吧  
选择需要的语言就好，文件太大也影响性能

**Comment by comxza** [comment]
![image](https://user-images.githubusercontent.com/21981010/141980844-3213c0d1-17d1-464f-beab-2c72ab674d1a.png)
![image](https://user-images.githubusercontent.com/21981010/141980878-b99eb415-99fb-4308-9bc6-21975dcf6f33.png)
![image](https://user-images.githubusercontent.com/21981010/141981811-4fe39afb-df31-48c9-9024-9339dded4c92.png)
按照以上这个操作  H5端  超出了，  app端不能滑动呢

**Comment by jin-yufeng** [comment]
暂时用非压缩版的 `css` 可以解决  
![微信截图_20211120162543](https://user-images.githubusercontent.com/48236054/142722456-9a4527e6-e218-411c-bcbc-97b80a0815f1.png)

**Comment by comxza** [comment]
https://github.com/jin-yufeng/mp-html/commit/b6762e3fb96f70cae5903a92f9d91d8b8af21bb5
我这看这里边有修复，这个修复是说可以试用压缩版的css吗，还是说还的据需使用未压缩版本的css和压缩版的js

**Comment by jin-yufeng** [comment]
修复后的可以直接使用压缩版的，修复前的需要使用未压缩版的

**Comment by comxza** [comment]
上面提到  修复后使用压缩版本，可能bug并未完全修复  
如果我的主题模式选择为Okaidia
![image](https://user-images.githubusercontent.com/21981010/142763808-e1033797-fc88-4118-a5bc-81eacfea78b8.png)
这样会存在css样式不过来，也就是会出现此问题https://github.com/jin-yufeng/mp-html/issues/367#issuecomment-970203092
我测试其他几个主题并未发现此问题

**Comment by comxza** [comment]
以及我在配置文件中  
如截图，这三个配置  默认是false   我都设置为true   ，只有现实语言名称可行，其他的都未出现，并且显示语言说的在右上角，然而实际在左下角
![image](https://user-images.githubusercontent.com/21981010/142763899-7bca5ad6-2c1a-4c4b-9c5f-187b5aef827a.png)
![image](https://user-images.githubusercontent.com/21981010/142763952-92e8d1ae-ca0f-47d3-a276-fa1353471aa4.png)

**Comment by jin-yufeng** [comment]
上面那个修改只改了原生包的部分，忘了改 `uni-app` 的部分，不知道是不是这个问题  
至于其他问题，我这里没有复现，可以试试这个 [demo.zip](https://github.com/jin-yufeng/mp-html/files/7576391/demo.zip)
![微信图片_20211121214559](https://user-images.githubusercontent.com/48236054/142764814-17d60f05-5229-43d7-bec8-4602616f9623.jpg)

**Comment by jin-yufeng** [comment]
对了，修改配置文件后需要重新构建组件包，在构建后的组件包里修改配置是无法生效的

**Comment by comxza** [comment]
https://github.com/jin-yufeng/mp-html/issues/367#issuecomment-974822651

看样子复制代码在nvue下不支持吗？我刚才按照你说的方式从新构建组件，把你demo中index.vue改成nvue    复制代码没效果

**Comment by jin-yufeng** [comment]
是的，`nvue` 暂不支持长按复制代码

**Comment by comxza** [comment]
这个后续有什么解决方案吗？
