### ISSUE TITLE
在editable状态下，使用insertText()方法插入文本并在编辑状态下，使用getContent()方法获取不到内容

### ISSUE THREAD

**Issue by mlzk** [jin-yufeng/mp-html#368]
## 问题描述  
在editable状态下，使用insertText()方法插入文本并在编辑状态下，使用getContent()方法获取不到内容

有什么方法可以主动取消这个文本的编辑状态么？

**Comment by jin-yufeng** [comment]
为避免过于频繁的设置数据，目前是输入框触发 `blur` 事件后才会去维护 `nodes` 结构，然后 `getContent` 方法才能获取到  
但是点击保存按钮时，`tap` 事件早于 `blur` 事件触发，导致在 `tap` 事件里调用 `getContent` 会获取不到当前编辑的内容  
暂时可以通过在获取内容前设置一个小延时来解决  
```javascript
editEnd() {
  setTimeout(()=>{
    const content = ctx.getContent()
  }, 50)
}
```

**Comment by mlzk** [comment]
感谢回复
