### ISSUE TITLE
 [system]TypeError: Cannot read property 'replace' of undefined     at Emoji.onUpdate (webpack-internal:///F:\front\getfriend\components\mp-html\emoji\index.js:190:18)

### ISSUE THREAD

**Issue by semix333** [jin-yufeng/mp-html#371]
uniapp 开启emoji插件，打包之后放到组件里面会报这个错误

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目

**Comment by semix333** [comment]
大佬，麻烦看下，直接打开pages/editor/editor.vue这个页面，里面有引入mphtml这个组件，打开就会报错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jin-yufeng/mp-html"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jin-yufeng/mp-html]  [system]TypeError: Cannot read property 'replace' of undefined     at Emoji.onUpdate (webpack-internal:///F:\front\getfriend\components\mp-html\emoji\index.js:190:18) (Issue #371)





 
提供可复现的 demo 项目
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jin-yufeng** [comment]
没有附件？

**Comment by semix333** [comment]
***@***.***, 发你这个邮箱了，刚才回复的时候有上传附件，不知道为什么你收不到，我发你126邮箱了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jin-yufeng/mp-html]  [system]TypeError: Cannot read property &#39;replace&#39; of undefined     at Emoji.onUpdate (webpack-internal:///F:\front\getfriend\components\mp-html\emoji\index.js:190:18) (Issue #371)





 
没有附件？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jin-yufeng** [comment]
有这个 `bug`，暂时可以通过设置 `<mp-html content="">` 来解决

**Comment by semix333** [comment]
okkkk
