### ISSUE TITLE
原生微信小程序中写类选择器无效(.detail)，而在uniapp中使用类选择器有效，为什么？

### ISSUE THREAD

**Issue by happyqian** [jin-yufeng/mp-html#372]
在.wxss文件写上
.detail {
   color:red;
}无效

**Comment by jin-yufeng** [comment]
你是在页面的 `wxss` 里写，然后想在组件内生效吗？  
小程序的组件默认是样式隔离的，即组件外的样式不会影响到组件内  
`uni-app` 好像是设置取消了这个隔离  
要在组件内生效的样式可以写到 [externStyle](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=externstyle) 里然后进行构建或者直接加到 `node/node.wxss/vue`

**Comment by happyqian** [comment]
明白了，谢谢老师！！
