### ISSUE TITLE
H5-webview中关于加载自定义style

### ISSUE THREAD

**Issue by janice-jia** [jin-yufeng/mp-html#373]
## 问题描述  
![image](https://user-images.githubusercontent.com/15044639/142898902-330e5768-d8b3-4997-8a99-46ba44159ba0.png)

以上方式，无法加载样式

**Comment by jin-yufeng** [comment]
`cssString` 是 `style` 标签吗？默认不支持 `style` 标签，需要的话要添加 [style](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=style) 扩展

**Comment by janice-jia** [comment]
已经解决了，配置中已经开启style，感谢大神～
