### ISSUE TITLE
设置字体大小

### ISSUE THREAD

**Issue by Tianrui007** [jin-yufeng/mp-html#375]
## 问题描述  
我在页面中增加了一个按钮，想修改字体大小，但是修改后tagStyle后不会实时渲染，请问需要如何处理才可以？

**Comment by jin-yufeng** [comment]
如果所有内容要设置相同的字体大小，且富文本内容中没有单独设置 `font-size`，那下面这样就可以了，会自动继承到子标签  
```html
<mp-html container-style="font-size:{{fontSize}}px" />
```
如果不同的标签要设置不同的字体大小，或者富文本标签本身设置了 `font-size` 需要进行覆盖的话，就麻烦一点，`tag-style` 只是在解析时生效的，只能重新设置一下 `content` 内容（`content` 属性没有改变时重新设置可能不生效，可以通过组件实例上的 [setContent](https://jin-yufeng.gitee.io/mp-html/#/advanced/api?id=setcontent) 方法进行设置）
