### ISSUE TITLE
建议组件加入自定义options

### ISSUE THREAD

**Issue by lbc19920615** [jin-yufeng/mp-html#376]
## 新功能描述

微信Component可以设置    styleIsolation: 'apply-shared',  这样page和app.wxss里的样式就可以自定了

## 应用场景
通过class设置富文本

**Comment by jin-yufeng** [comment]
这个感觉不同人的需要不一样吧，有些人可能并不希望页面设置的样式影响到内部  
之后作为一个配置项也可以  
目前需要在组件里用的样式可以加到 `node/node.wxss` 里或者加到 `tools/config.js` 的 [externStyle](https://jin-yufeng.gitee.io/mp-html/#/overview/quickstart?id=externstyle) 中然后构建到组件里
