### ISSUE TITLE
ios兼容问题 span标签渲染出来内容独占一行 

### ISSUE THREAD

**Issue by luoxuan-huang** [jin-yufeng/mp-html#378]
## 使用环境  

Taro 3.2.9  开发微信小程序  微信开发者工具 调试库版本 2.21.0 
## 问题描述  

![111](https://user-images.githubusercontent.com/73371782/145331548-5b71cb83-cbec-413d-a342-d0b255f35a18.png)
1.开启了复制属性selectable=force ，页面中span标签渲染出来内容独占一行。
使用mp-html  2.2.0版本 作为富文本渲染组件，开启了复制属性selectable=force，渲染详情页面异常，ios 中span标签内容独占一行 。android系统正常，在线mp-html测试也正常。开启了复制属性selectable=true ，则ios android 均正常。

## 复现方式  

<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-size: 18px;\">一、医药行业的现状与展望<span class=\"Apple-converted-space\"> </span></span></span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">（1）医药行业是一个长期来看稳定增长的行业，但政策是最大的扰动因素。</span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">       今年以来，医药板块整体走势较弱，回调较多，短期来看受集采等相关政策的影响较大。但政策对于公司的长逻辑，包括海外市场的逻辑影响不大，只会对短期的情绪造成比较大的冲击。医药作为典型的<span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder; display: inline;\">长坡厚雪</span>的成长行业，有着长期的、内生的驱动力，整体行业发展的趋势是持续向上的；而从政策端来看，中长期的政策也会引导行业更加稳定地发展。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; display: inline-block; padding: 0px; margin: 0px; font-weight: bolder;\">（2）今年是行业的政策大年，预期明年医药相关政策会进入到相对平稳的阶段。</span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">       未来不同医疗细分行业的超预期政策出台的可能性较低，整个医疗行业的政策开拓期或已经结束。对于医药这类成长型行业，每次下跌都是加仓的机会，板块的回调是未来上涨的很好的驱动力。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">（3）未来医药行业长期增长的三个重要推动力：人口老龄化、政府投资推动、中国疾病谱的发展和变迁。</span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">     <span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\"> </span>首先，我国人口老龄化问题日趋严重，未来5-10年医药行业都是比较好的投资方向。其次，政府投资在推动医疗市场发展上起到了引导作用，医保支出持续增长；并且政府对于能够解决患者需求、解决医疗痛点的创新产品的支持力度非常大，医保准入也保证了创新产品一旦获批，会快速放量，国内创新药的商业化环境很好。最后，中国疾病谱的发展和变迁也是医药行业内生增长的动能。总体来说，中长期来看医药行业有望稳定增长，可长期投资。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-size: 18px;\">二、光大健康优加重点掘金创新药、医疗器械、医疗消费三大领域<span class=\"Apple-converted-space\"> </span></span></span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">（1）创新医疗<span class=\"Apple-converted-space\"> </span></span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">     <span class=\"Apple-converted-space\"> </span><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\"> 创新医疗板块包括了创新医药、创新机械、创新生物制品以及创新服务商等，创新是整个医药行业未来的大趋势。</span>今年国内获批了很多新药产品，预计未来不仅仅这部分新药会贡献收入和利润，同时一些国产创新药在美国、欧洲等海外市场的销量的增加，海外市场逐步开拓，预期整个创新板块能够打开全球估值的天花板。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">       <span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">我国创新药市场逐步崛起，值得重点关注。</span>近年来，随着国家政策扶持力度的进一步加大、自主创新意识的提升以及海外高级人才归国热潮，创新药市场正在逐步崛起。在投资回报方面，创新药前期研发投入大，同时研发周期较长，但满足临床紧急需求、疗效确切的创新药获批上市之后，将为药企及投资者带来高额回报。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">       <span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">创新医疗服务是医药行业增长最快的细分行业。</span>CXO呈现出全球化竞争的特性，特别是临床前 CRO 和 CMO。随着海外产业的转移、国内政策鼓励创新以及资本力量的助推，预期国内创新服务仍将维持高速增长。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">（2）医疗器械<span class=\"Apple-converted-space\"> </span></span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">       中国医疗器械销售规模从 2016 年的 3700 亿元增长至2019 年的6882 亿元，年均复合增长率为18%。新冠疫情防控需求增加，国内医疗器械企业蓬勃发展，国家政策大力支持国产医疗设备限制并进口产品，国产设备有望迎来利好。</p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\"><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">（3）医疗消费</span></p>\n<p style=\"box-sizing: inherit; padding: 0px; margin: 0px; color: #535353; font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; text-size-adjust: auto;\">   <span class=\"Apple-converted-space\"> </span><span style=\"box-sizing: inherit; padding: 0px; margin: 0px; font-weight: bolder;\">  “政策+市场\"双轮驱动各医疗消费赛道发展。</span>从市场发展来看，医美、体检、眼科及口腔等细分医疗消费赛道已超过千亿规模，部分赛道如医美行业技术壁垒低，毛利率高；从政策面来看，中国政府从国家层面的顶层设计中将健康教育纳入国民素质教育体系，侧面助推医疗消费市场拓展。</p>

**Comment by jin-yufeng** [comment]
微信 `ios` 端现在无法通过 `css` 中的 `user-select` 实现长按复制，只能通过 [text](https://developers.weixin.qq.com/miniprogram/dev/component/text.html) 标签的 `user-selet` 属性实现，代价就是文本块会变成 `inline-block` 布局，且无法修改，[文档](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=selectable) 里已经注明，需要自行适配

**Comment by luoxuan-huang** [comment]
请问需要怎么适配

**Comment by luoxuan-huang** [comment]
文档仔细看了，文本块变成inline-block布局，应该是在一行显示才对。可微信请教您吗？ 微信15115398859

**Comment by jin-yufeng** [comment]
`inline-block` 超过一行的效果就和 `block` 差不多了  
![微信截图_20211209183757](https://user-images.githubusercontent.com/48236054/145381130-39dbc9bc-6daf-4efc-b2d5-c7cf82da6f8f.png)

自行适配的意思是要去修改 `html` 内容，在文本块 `inline-block` 布局无法改变的情况下看看能不能改成合理的效果，没有统一的方案

**Comment by 0zcl** [comment]
[文档](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=selectable) 里已经注明，需要自行适配。请问需要怎么适配? @jin-yufeng @luoxuan-huang 

![image](https://user-images.githubusercontent.com/26007970/221335297-bd742f4a-e042-4f1d-ba80-9264936f006c.png)
这里 的text 是不要让它换行才对
