### ISSUE TITLE
html字符串中包含音频文件，IOS端，音频文件点击播放按钮无反应，无法播放。安卓可以正常打开。

### ISSUE THREAD

**Issue by luoxuan-huang** [jin-yufeng/mp-html#379]
## 使用环境  

Taro 3.2.9  开发微信小程序  微信开发者工具 调试库版本 2.21.0 
## 问题描述  

使用mp-html  2.2.0版本 作为富文本渲染组件，html字符串中包含音频文件，IOS（iphone8  ios系统15.0）端，音频文件点击播放按钮无反应，无法播放。安卓可以正常打开。微信小程序开发者工具可以正常打开
## 复现方式  

```html
<p><video src="https://kf-test.any800.com/group1/M00/00/80/wKgLimGTImOAWeOVAFgtw3jqdmk613.mp4" controls="controls" width="300" height="150">↵        【您的浏览器不支持 video 标签。】↵      </video> <audio src="https://kf-test.any800.com/group1/M00/00/7F/wKgLimGRwCyAaLeWAD8qj2biUZg391.wma" controls="controls">↵        【您的浏览器不支持 audio 标签。】↵      </audio></p>
```

**Comment by jin-yufeng** [comment]
[文件格式](https://developers.weixin.qq.com/miniprogram/dev/api/media/audio/InnerAudioContext.html#%E6%94%AF%E6%8C%81%E6%A0%BC%E5%BC%8F) 问题，`ios` 不支持 `wma`

**Comment by luoxuan-huang** [comment]
非常感谢您的解答 @jin-yufeng
