### ISSUE TITLE
uniapp写小程序添加selectable="force"后在微信ios端下划线、删除线失效，斜体状态下文字展示不全

### ISSUE THREAD

**Issue by AdeleGo-design** [jin-yufeng/mp-html#382]
使用uniapp写小程序，添加selectable="force"后在微信ios端出现以下问题：
1.下划线、删除线失效
2.斜体状态下文字展示不全，文字右上角缺一点

html里面标签：<i>斜体</i>   <strike>删除线</strike>  <u>下划线</u>

请问要怎么解决？非常感谢

**Comment by jin-yufeng** [comment]
微信小程序的 `text` 组件设置 `user-select` 属性后好像 `text-decoration` 就设置不了了（[详细](https://developers.weixin.qq.com/community/develop/doc/00086ec3e8cff8c24f3dad6e85ac00)）
