### ISSUE TITLE
关于使用插件问题

### ISSUE THREAD

**Issue by drc5521** [jin-yufeng/mp-html#383]
## 问题描述  
在修改插件之后生成组建包后（比如editor），把项目上传到github上，用另一台电脑克隆下来，然后运行，是不是还要重新进行插件的配置（包括修改配置，生成组建包），这样是不是太麻烦了？

**Comment by jin-yufeng** [comment]
如果是通过 `npm` 方式引入的，然后 `node_modules` 没有上传的话确实会这样  
这种情况的话建议把生成好的组件包（`dist/`）拷贝到项目的 `components` 目录下，用源码方式引入
