### ISSUE TITLE
段落之间加margin

### ISSUE THREAD

**Issue by haoxf** [jin-yufeng/mp-html#384]
## 新功能描述
当前段落之间没有设置margin, 内容看起来很拥挤，只能手动加入空行，显示第三方内容时很不方便

**Comment by jin-yufeng** [comment]
如果你的每个段落都是一个 `p` 标签的话通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性给 `p` 标签设置默认 `margin` 就行了  
如果没什么规律的话只能具体调整 `html` 内容了

**Comment by haoxf** [comment]
> 如果你的每个段落都是一个 `p` 标签的话通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 属性给 `p` 标签设置默认 `margin` 就行了 如果没什么规律的话只能具体调整 `html` 内容了

现在我的解决方案是给所有的块级元素加上 tag-style
