### ISSUE TITLE
能不能添加个无图模式

### ISSUE THREAD

**Issue by lentg** [jin-yufeng/mp-html#385]
## 新功能描述
动态切换有图/无图
## 应用场景
无图的情况下，用户可以自己定义图片的显示方式（用户自己在这插件之外显示图片）

**Comment by jin-yufeng** [comment]
如果要去掉图片的话对传入的 `html` 做 `html.replace(/<img[\s\S]*?>/g, '')` 就可以了吧

**Comment by lentg** [comment]
这样是可以，不过切换回来又要重新格式html，有点麻烦，不过谢谢了。
