### ISSUE TITLE
taro vue 引入weixin平台源码的时会出现 Bad attr `wx

### ISSUE THREAD

**Issue by SIYU9825** [jin-yufeng/mp-html#386]
## 问题描述  
想在taro项目里尝试用一下这个组件，但在页面编译时报了个错误

`Bad attr  wx`

[ WXML 文件编译错误] ./subpages/detail/components/mp-html/node/node.wxml
`> 89 | <view wx:else id="{{n2.attrs.id}}" class="_{{n2.name}} {{n2.attrs.class}}" style="{{n2.attrs.style}}">`

at files://subpages/detail/components/mp-html/node/node.wxml#85(env: Windows,mp,1.05.2110290; lib: 2.20.1)

**Comment by jin-yufeng** [comment]
你使用的是哪里的文件？这看起来像是 `src` 目录下的文件，应该要使用 `dist` 目录下的文件

**Comment by SIYU9825** [comment]
> 你使用的是哪里的文件？这看起来像一个`src`目录下的文件，应该要使用`dist`目录下的文件

感谢,自己大意了搞错路径了,确实是这个原因
