### ISSUE TITLE
能否对图片增加 referrerPolicy='no-referrer' 属性的设置？

### ISSUE THREAD

**Issue by yangchao508** [jin-yufeng/mp-html#387]
在小程序里的富文本内容中时常会携带一些其他场景的图片，部分图片会因为设置了防盗链导致小程序访问403 不能显示，通过设置image属性referrerPolicy='no-referrer'就可以解决。

**Comment by yangchao508** [comment]
我自己在源码里的 图片标签里加上去试了 可以解决类似 135编辑器处理过的图片 链接为135编辑器的图片 在小程序无法显示的问题

**Comment by jin-yufeng** [comment]
这个目前好像只有微信有，而且文档里只有 [wx.previewImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html#%E5%8F%82%E6%95%B0) 有这个参数，[image](https://developers.weixin.qq.com/miniprogram/dev/component/image.html) 组件没有，暂时先不添加了  
有需要的朋友可以参考一下这个方案

**Comment by laogui** [comment]
微信的官方文档image里的确没这个参数说明，但加了可解决部分第三方图片防盗链的问题。
