### ISSUE TITLE
taro3 支付宝小程序linktap 报错

### ISSUE THREAD

**Issue by chmubai** [jin-yufeng/mp-html#388]
![image](https://user-images.githubusercontent.com/16893170/147440349-944cc644-7948-47a8-8473-21c9f0caf8ac.png)
![image](https://user-images.githubusercontent.com/16893170/147440392-ec5715bd-8708-4b92-a65b-a3a41b3ee3e9.png)

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目
