### ISSUE TITLE
Taro3 使用后 不显示  不知道是哪里不对

### ISSUE THREAD

**Issue by pupillxy** [jin-yufeng/mp-html#395]
![image](https://user-images.githubusercontent.com/41733945/149604884-4cf2e7e9-a1ce-4552-a995-29d465369706.png)
![image](https://user-images.githubusercontent.com/41733945/149604892-04c47bad-a2be-4cdf-96a7-90abe655d921.png)
![image](https://user-images.githubusercontent.com/41733945/149604906-a3ddc45d-cc03-4884-b2eb-25c37b11bb7a.png)
![image](https://user-images.githubusercontent.com/41733945/149604920-fa7dfa4c-e153-4f36-b2b4-0d844ef0955a.png)
 真不知道怎么弄了 显示是空的

**Comment by jin-yufeng** [comment]
`content="<div>123</div>"` 或者 `:content="content"（变量名）`

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目

**Comment by pupillxy** [comment]
这个&nbsp; vue3的

**Comment by jin-yufeng** [comment]
没有附件？
