### ISSUE TITLE
开启了 markdown配置，没有生效，为什么

### ISSUE THREAD

**Issue by peter100u** [jin-yufeng/mp-html#399]
## markdown不生效

1. 已经配置好了
     plugins: [
    'highlight', // 代码高亮
    'markdown',  // 解析 md
    'img-cache'  // 图片缓存
  ],

2. 已经使用一下命令了
    npm install 
    npm run build:weixin
也提示构建成功了，也看到dist中有md插件了，但是使用就是不生效

3. 使用如下
    <mp-html content="{{sectionMarkdown}}" />

4. 我确定自己的markdown 字符串没有问题
请问是什么原因，导致markdown配置，在我的小程序中不生效，或者是什么原因导致

**Comment by jin-yufeng** [comment]
需要将 `markdown` 属性设置为 `true` 才会解析 `markdown`，详见 [文档](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=markdown)  
```html
<mp-html markdown content="{{sectionMarkdown}}" />
```
