### ISSUE TITLE
<mp-html>内容渲染失败BUG

### ISSUE THREAD

**Issue by 1239937890** [jin-yufeng/mp-html#412]
## 使用环境  

使用环境：uni.app编译微信小程序，预览二维码在手机IOS端。
## 问题描述  

问题描述：每个页面都使用了<mp-html>，页面点击跳转，一直到小程序的页面栈的最底层，之后页面一直返回，当返回到页面栈的第五层之后，有的页面<mp-html>里的内容会消失渲染失败。
## 复现方式  

复现方式：两个使用<mp-html>页面相互跳转到页面栈的最底层，之后在一直返回

**Comment by 1239937890** [comment]
两个页面都使用了<mp-html>，相互跳转，到小程序页面栈的最底层，之后在一直返回，前几个页面栈<mp-html>里的内容会丢失

**Comment by 1239937890** [comment]
两个页面都使用了mp-html

**Comment by jin-yufeng** [comment]
富文本内容多吗？可能被系统回收了吧
![微信截图_20220314185613](https://user-images.githubusercontent.com/48236054/158158630-935abfaa-03a7-4b88-b5d5-0f2428c68b92.png)

**Comment by 1239937890** [comment]
您好，这个问题一开始是使用uview的u-parse发现的，今天在dcloud上导入了mp-html示例 测试了下 内容并不多只是一些文本，手机系统内存也很充足的，跳转到页面栈底层之后，页面左滑一直返回，大概五页之后 mp-html内的内容丢失

**Comment by 1239937890** [comment]
录屏测试附件已发送 mp_html@126.com 邮箱

**Comment by 1239937890** [comment]
@jin-yufeng 您好，iOS上返回内容丢失的方便修复下么
