### ISSUE TITLE
uniapp导入Prism.min.js和Prism.css后报错

### ISSUE THREAD

**Issue by zxyzzxxyy** [jin-yufeng/mp-html#416]
## 问题描述  
在prism官网选择了c++和java后下载了prism.min.js和prism.css 替换后打包覆盖运行报错

![SW1YF})$QN8(U Y8~6LD0](https://user-images.githubusercontent.com/79697833/160556012-b53b98a9-9b84-4560-a865-bc1bc7d7f319.png)

![OX7B90`{JCM61WL7_I9Z5 1](https://user-images.githubusercontent.com/79697833/160555831-408b2c1a-81b7-4352-b5ae-bc9a28684eae.png)

D0](https://user-images.githubusercontent.com/79697833/160555854-dd9f837c-14ee-4825-9a8b-c9edd9aff6e0.png)
![Z52 0`J}KM_D8$JO7EAQLH7](https://user-images.githubusercontent.com/79697833/160555872-27cf698c-7e7c-450d-9753-a8e763be8fa9.png)

**Comment by jin-yufeng** [comment]
先直接把下载 `prism.min.js` 复制到构建后的包里

**Comment by zxyzzxxyy** [comment]
可以了非常感谢
