### ISSUE TITLE
微信小程序编辑图片后，只能本机看，我用得是unicloud，请问是否可以存储到对应空间的云存储中

### ISSUE THREAD

**Issue by guocdfeifei** [jin-yufeng/mp-html#420]
## 问题描述  
图片存储的是临时地址
wxfile://tmp_930ca6e0c46c28b3c9f2531f439b0e69ddfc40aee8bf042f.jpg

**Comment by jin-yufeng** [comment]
获取图片链接的方法是自己在页面上配置的啊

**Comment by guocdfeifei** [comment]
> 获取图片链接的方法是自己在页面上配置的啊

找到了谢谢，修改地方
···javascript
function upload(src) {
		return new Promise((resolve, reject) => {
			console.log('上传图片：', src)
			
···
unicloud样例
···javascript
const db = uniCloud.database();
	// 上传图片方法
	function upload(src) {
		return new Promise((resolve, reject) => {
			console.log('上传图片：', src)
			
			
			// promise方式
			uniCloud.uploadFile({
				filePath: src,
				cloudPath: 'a.jpg',
				onUploadProgress: function(progressEvent) {
				  console.log(progressEvent);
				  var percentCompleted = Math.round(
					(progressEvent.loaded * 100) / progressEvent.total
				  );
						},
						success(res) {
							// console.log("res",res)
							resolve(res.fileID)
						},
						fail() {},
						complete() {}
					});
           })
	}
···
