### ISSUE TITLE
腾讯视频插件2.1.0版无法显示播放控件（controls）

### ISSUE THREAD

**Issue by iamxjb** [jin-yufeng/mp-html#424]
## 使用环境  
微信小程序下使用腾讯视频插件2.1.0版

## 问题描述  

1、不显示播放控件(controls)
2、不支持属性autoplay

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目

**Comment by iamxjb** [comment]
我经过反复的测试，不是mp-html的问题，是我的代码中的样式文件导致的。不好意思。
