### ISSUE TITLE
微信小程序，开启“上传时进行代码保护”之后，上传的体验版和开发版会报错

### ISSUE THREAD

**Issue by zx327216** [jin-yufeng/mp-html#425]
## 微信小程序  
调试基础库：2.23.2
mp-html版本：2.3.0

## 问题描述  
页面白屏
![image](https://user-images.githubusercontent.com/30823536/164383990-dceb9137-7abd-4af5-8648-a0cd4eaaf923.png)

## 复现方式  
![image](https://user-images.githubusercontent.com/30823536/164384208-4501570a-b07d-4ef8-9e81-fe1090014132.png)
1、开启“上传时进行代码保护”
2、点击真机调试，生成二维码，手机扫码出现白屏和**“问题描述”**中的报错信息

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目

**Comment by zx327216** [comment]
> 提供可复现的 demo 项目
https://gitee.com/gitee_zhangxuan/mp-html.git

**Comment by zx327216** [comment]
> 提供可复现的 demo 项目

https://gitee.com/gitee_zhangxuan/mp-html.git

**Comment by jin-yufeng** [comment]
我这里测试正常
![QQ截图20220421181426](https://user-images.githubusercontent.com/48236054/164437884-986b0866-c528-4e09-9a99-f796f7c460ad.png)
![QQ截图20220421181507](https://user-images.githubusercontent.com/48236054/164437997-608b9604-5490-4781-9cc2-c077a9820103.png)
![QQ截图20220421183002](https://user-images.githubusercontent.com/48236054/164439573-2d28634c-5911-4f40-ba12-02c7790b0358.png)

**Comment by zx327216** [comment]
> 我这里测试正常 ![QQ截图20220421181426](https://user-images.githubusercontent.com/48236054/164437884-986b0866-c528-4e09-9a99-f796f7c460ad.png) ![QQ截图20220421181507](https://user-images.githubusercontent.com/48236054/164437997-608b9604-5490-4781-9cc2-c077a9820103.png) ![QQ截图20220421183002](https://user-images.githubusercontent.com/48236054/164439573-2d28634c-5911-4f40-ba12-02c7790b0358.png)

我的开发工具是windows版本
![image](https://user-images.githubusercontent.com/30823536/164585577-fee48961-96d0-47d6-95a8-ac2f2d1c3609.png)

**Comment by zx327216** [comment]
> > 我这里测试正常 ![QQ截图20220421181426](https://user-images.githubusercontent.com/48236054/164437884-986b0866-c528-4e09-9a99-f796f7c460ad.png) ![QQ截图20220421181507](https://user-images.githubusercontent.com/48236054/164437997-608b9604-5490-4781-9cc2-c077a9820103.png) ![QQ截图20220421183002](https://user-images.githubusercontent.com/48236054/164439573-2d28634c-5911-4f40-ba12-02c7790b0358.png)
> 
> 我的开发工具是windows版本 ![image](https://user-images.githubusercontent.com/30823536/164585577-fee48961-96d0-47d6-95a8-ac2f2d1c3609.png

**Comment by zx327216** [comment]
看来和微信开发这工具版本也没啥关系，换成和你一样的版本还是报错和白屏

**Comment by zx327216** [comment]
最终解决办法，可通过配置project.config.json中的babelSetting来忽略npm包
![image](https://user-images.githubusercontent.com/30823536/164613081-6fb81f34-6546-4ba6-ad7a-ce0f1b8e2ce1.png)
