### ISSUE TITLE
Cannot read property \'children\' of undefined

### ISSUE THREAD

**Issue by xmzhy** [jin-yufeng/mp-html#428]
## 使用环境  
微信原生小程序，基础库版本2.24.1 

## 问题描述  
Cannot read property \'children\' of undefined
TypeError: Cannot read property \'children\' of undefined
at ki.getNode (https://usr/components/mp-html/node/node.appservice.js:282:391)
at ki.imgLoad (https://usr/components/mp-html/node/node.appservice.js:282:1045)
at Object.i.safeCallback (https://lib/WASubContext.js:2:442213)
at https://lib/WASubContext.js:2:624646
at h (https://lib/WASubContext.js:2:525572)
at https://lib/WASubContext.js:2:525942

## 复现方式  
使用场景是商品详情中渲染只有十几个图片的简单富文本内容，在极限情况下（非常快速切换规格），也就是极快速切换富文本内容，就会出现这个问题。

## 临时解决方式
修改node.js 里的getNode 函数
    getNode (path) {
      const nums = path.split('_')
      let node = this.properties.childs[nums[0]]
      for (let i = 1; i < nums.length; i++) {
        node = node ? node.children[nums[i]] : ''
      }
      return node
    },

期待能找到问题根源，谢啦

**Comment by jin-yufeng** [comment]
找到根本原因比较困难，暂时先按照类似你这种办法 `try catch` 一下
