### ISSUE TITLE
图文详情页渲染，最后有一个 rich-text 标签，没有内容，但是有高度

### ISSUE THREAD

**Issue by godkun** [jin-yufeng/mp-html#433]
## 使用环境  
微信小程序  uni-app

## 问题描述  
设置 
```
tagStyle: {
        p: "min-height: 600rpx",
      }
```
后，图文详情页渲染，最后有一个 rich-text 标签，没有内容，但是有高度，如下图所示

<img width="2011" alt="image" src="https://user-images.githubusercontent.com/26134303/169465944-99f7845b-76fc-46da-bd00-5021a6723850.png">

这种是什么原因呢

## 复现方式  
参考问题描述

**Comment by jin-yufeng** [comment]
你给 `p` 标签设置了 `min-height: 600rpx`，那自然所有 `p` 标签（包括空的）都会有高度啊

**Comment by godkun** [comment]
嗯嗯，说的对，主要是富文本内容有 <p><br/></p>  导致设置 p 标签样式的时候，出现空的内容了。我这边正则过滤下。
