### ISSUE TITLE
定时器`setInterval`未回收

### ISSUE THREAD

**Issue by liyujiang-gzu** [jin-yufeng/mp-html#437]
<html>
<body>
<summary style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; text-decoration: none; outline: 0px;">定时器是全局的，并不是跟页面绑定的，当小程序从一个页面路由到另一个页面之后，前一个页面定时器应注意手动回收 <i class="ui-icon-arrow-down-o" style="box-sizing: border-box; margin: 0px 0px 0px 5px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; display: inline-block; width: 16px; height: 8px; -webkit-mask: url(&quot;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='11' height='7' viewBox='0 0 11 7'%3E  %3Cdefs%3E    %3ClinearGradient id='27ae5ee4-2566-47d2-9f7f-6fb2b19d956e-c' x1='50%25' x2='50%25' y1='0%25' y2='100%25'%3E      %3Cstop offset='0%25' stop-color='%23FCFCFC'/%3E      %3Cstop offset='100%25' stop-color='%23F1F1F1'/%3E    %3C/linearGradient%3E    %3Cpath id='27ae5ee4-2566-47d2-9f7f-6fb2b19d956e-b' d='M5.058 8.287l-.707.707L.5 5.14a.664.664 0 0 1 0-.942L4.35.347l.707.707L1.442 4.67l3.616 3.617z'/%3E    %3Cfilter id='27ae5ee4-2566-47d2-9f7f-6fb2b19d956e-a' width='184.1%25' height='146.3%25' x='-42.1%25' y='-11.6%25' filterUnits='objectBoundingBox'%3E      %3CfeOffset dy='1' in='SourceAlpha' result='shadowOffsetOuter1'/%3E      %3CfeGaussianBlur in='shadowOffsetOuter1' result='shadowBlurOuter1' stdDeviation='.5'/%3E      %3CfeColorMatrix in='shadowBlurOuter1' values='0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.0612828351 0'/%3E    %3C/filter%3E    %3Cfilter id='27ae5ee4-2566-47d2-9f7f-6fb2b19d956e-d' width='163.1%25' height='134.7%25' x='-31.5%25' y='-5.8%25' filterUnits='objectBoundingBox'%3E      %3CfeGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='.5'/%3E      %3CfeOffset in='shadowBlurInner1' result='shadowOffsetInner1'/%3E      %3CfeComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/%3E      %3CfeColorMatrix in='shadowInnerInner1' values='0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0'/%3E    %3C/filter%3E  %3C/defs%3E  %3Cg fill='none' fill-rule='evenodd' opacity='.5' transform='rotate(-90 3.51 3.184)'%3E    %3Cuse fill='%23000' filter='url(%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-a)' xlink:href='%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-b'/%3E    %3Cuse fill='url(%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-c)' xlink:href='%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-b'/%3E    %3Cuse fill='%23000' filter='url(%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-d)' xlink:href='%2327ae5ee4-2566-47d2-9f7f-6fb2b19d956e-b'/%3E  %3C/g%3E%3C/svg%3E&quot;) 50% 50% / cover no-repeat; background-color: rgb(204, 204, 204); transform-origin: 50% 50%; transform: rotate(180deg);"></i></summary><slot name="user-agent-default-slot" id="details-content"><div style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; text-decoration: none;"><table class="audit-result-table" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: inherit; vertical-align: baseline; text-decoration: none; border-collapse: collapse; border-spacing: 0px; width: 1120px; table-layout: fixed;"><thead style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none;"><th style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font: inherit; vertical-align: middle; text-decoration: none; text-align: left;">定时器</th><th style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font: inherit; vertical-align: middle; text-decoration: none; text-align: right;">调用堆栈</th><th style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font: inherit; vertical-align: middle; text-decoration: none; text-align: right;">页面</th></thead><tbody style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none;"><tr style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none;"><td style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; vertical-align: middle; text-decoration: none; text-align: left; color: rgb(127, 127, 127); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><p title="setInterval" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">setInterval</p></td><td style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; vertical-align: middle; text-decoration: none; text-align: right; color: rgb(127, 127, 127); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at Proxy.setContent (<a href="javascript:;" title="uni_modules/mp-html/components/mp-html/mp-html.js:177:21" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">uni_modules/mp-html/components/mp-html/mp-html.js:177:21</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at Proxy.content (<a href="javascript:;" title="uni_modules/mp-html/components/mp-html/mp-html.js:66:12" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">uni_modules/mp-html/components/mp-html/mp-html.js:66:12</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at callWithErrorHandling (<a href="javascript:;" title="common/vendor.js:2758:20" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">common/vendor.js:2758:20</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at callWithAsyncErrorHandling (<a href="javascript:;" title="common/vendor.js:2766:17" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">common/vendor.js:2766:17</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at Array.job (<a href="javascript:;" title="common/vendor.js:3214:9" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">common/vendor.js:3214:9</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at flushPreFlushCbs (<a href="javascript:;" title="common/vendor.js:2901:7" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">common/vendor.js:2901:7</a>)</p><p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">at patch (<a href="javascript:;" title="common/vendor.js:4895:7" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: middle; text-decoration: none; color: rgb(16, 174, 255); cursor: pointer;">common/vendor.js:4895:7</a>)</p></td><td style="box-sizing: border-box; margin: 0px; padding: 9px 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-color: rgb(58, 58, 58); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; vertical-align: middle; text-decoration: none; text-align: right; color: rgb(127, 127, 127); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><br class="Apple-interchange-newline">
</body>
</html>定时器是全局的，并不是跟页面绑定的，当小程序从一个页面路由到另一个页面之后，前一个页面定时器应注意手动回收 
定时器	调用堆栈	页面
setInterval

at Proxy.setContent ([uni_modules/mp-html/components/mp-html/mp-html.js:177:21](javascript:;))

at Proxy.content ([uni_modules/mp-html/components/mp-html/mp-html.js:66:12](javascript:;))

at callWithErrorHandling ([common/vendor.js:2758:20](javascript:;))

at callWithAsyncErrorHandling ([common/vendor.js:2766:17](javascript:;))

at Array.job ([common/vendor.js:3214:9](javascript:;))

at flushPreFlushCbs ([common/vendor.js:2901:7](javascript:;))

at patch ([common/vendor.js:4895:7](javascript:;))

**Comment by jin-yufeng** [comment]
定时器是为了确定富文本内容是否加载完毕，每 `350ms` 获取一次高度，和上一次无变化就会回收（参考 [L341](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/index.js#L341)），等 `ready` 事件触发后再跳转页面应该就没有这个问题了  
另外如果组件销毁了，定时器也会被回收（参考 [L160](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/index.js#L160)）

**Comment by liyujiang-gzu** [comment]
> 等 ready 事件触发后再跳转页面

谢谢回复
