### ISSUE TITLE
禁止小程序JavaScript解释器

### ISSUE THREAD

**Issue by zhangaichen** [jin-yufeng/mp-html#440]
https://developers.weixin.qq.com/community/develop/doc/000e8822f0427878262e661be5b801
请问对于小程序新策略是否受影响

**Comment by zhangaichen** [comment]
看他好像对于动态html也是不行的

**Comment by jin-yufeng** [comment]
应该没有影响，本组件不涉及javascript解释器，目前示例小程序审核也正常通过
