### ISSUE TITLE
请问怎么配置让文字先显示出来，再加载图片和视频？

### ISSUE THREAD

**Issue by Jungle68** [jin-yufeng/mp-html#443]
## 问题描述  
尝试使用了`[lazy-load]` 无效，还是内容加载完毕了一起显示出来的

**Comment by jin-yufeng** [comment]
1. `lazy-load` 只对图片有效，目前没有视频懒加载的方法
2. 设置了 `lazy-load` 在一定范围内的图片也会立刻加载，只有内容足够长才会懒加载不可见区域的图片
3. 内容大部分情况都是图片的情况参考 [懒加载问题](https://jin-yufeng.gitee.io/mp-html/#/question/faq?id=lazy-load)
4. 以上都不能解决的提供可复现的 `demo` 项目

**Comment by Jungle68** [comment]
@jin-yufeng  感谢回复，这边尝试处理一下
