### ISSUE TITLE
使用新版mp-html ，解析小程序图文详情时，出现表格头没有渲染现象

### ISSUE THREAD

**Issue by godkun** [jin-yufeng/mp-html#444]
## 使用环境  
uni-app 微信小程序

## 问题描述  
使用新版mp-html ，解析小程序图文详情时，出现表格头没有渲染现象

![image](https://user-images.githubusercontent.com/26134303/182282794-dc0e4c7c-75b7-4c99-8595-e52fa5dcf900.png)

老板解析没有问题

**Comment by jin-yufeng** [comment]
提供 html 内容

**Comment by godkun** [comment]
好，感谢  

<table><tbody><tr class="firstRow"><td width="717" valign="top"><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211229/20211229152057629562_original.jpg" title="" alt=""/></td><td width="717" valign="top"><a href="https://shop.vivo.com.cn/wap/compare?spuId=10007036&skuId=122298&rightSpuId=10007035&rightSkuId=122336" target="_self"><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211229/20211229152103340308_original.jpg" title="" alt=""/></a></td></tr></tbody></table><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20220106/20220106171905287193_original.jpg" title="" alt=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141348355448_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141348183600_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/2021122014141149780_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141411293168_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/2021122014141256299_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/2021122014141214379_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141412244213_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141412863111_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141437710430_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141438249432_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141437775888_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141438401103_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/202112201414578117_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/2021122014145752277_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141458171360_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141458932258_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141518860702_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141519199480_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141518740796_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141519689698_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141544683456_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141544831596_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141545603323_original.jpg" style=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211220/20211220141903670933_original.jpg" title="" alt=""/></p><p></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211222/20211222142925663530_original.jpg" title="" alt=""/></p><p><img src="https://shopstatic.vivo.com.cn/vivoshop/commodity/20211222/2021122214290513050_original.jpg" style=""/></p>

**Comment by jin-yufeng** [comment]
在示例项目里无法复现，提供可复现的 demo 项目
