### ISSUE TITLE
Taro Vue3 使用mp-html时报错

### ISSUE THREAD

**Issue by Waymilk** [jin-yufeng/mp-html#445]
![image](https://user-images.githubusercontent.com/37338061/183596243-e05879bd-7756-4a8d-b77b-8592b4b9d061.png)

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目

**Comment by jin-yufeng** [comment]
看起来像这个问题 https://taro-docs.jd.com/taro/docs/hybrid/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by HuangYaobin** [comment]
同样是这个问题 @Waymilk 兄弟 后面是怎么解决的

**Comment by whevether** [comment]
> 

兄弟taro可以使用vue或react 原生方式渲染
