### ISSUE TITLE
uniapp  vue3  audio标签显示不出来

### ISSUE THREAD

**Issue by RoneLeo** [jin-yufeng/mp-html#450]
## 使用环境  

uniapp  vue3  h5  页面中audio标签显示不出来，content属性传入的值是有audio标签的，但是完全显示不出来。

## 问题描述  

step1：从这个地址直接拉取uniapp+vite+ts+vue3的模板
step2：从npm下载mp-html
step3：使用mp-html，传入的content中含有audio标签，audio标签不展示，其他内容能正常展示。 

## 复现方式  

这是我的demo压缩包：  https://prejie.360tianma.com/application/tenma02wz_politics/view/uni-preset-vue.zip
下载下来后，安装依赖，run起来就能看到。

**Comment by jin-yufeng** [comment]
`vue3` 的 `h5` 没有 `audio` 标签了（参考 [链接](https://ask.dcloud.net.cn/question/136913)），需要使用音频可以引入 [audio](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=audio) 扩展

**Comment by RoneLeo** [comment]
已解决，消谢谢回复。
