### ISSUE TITLE
解析带emoji表情的富文本有问题

### ISSUE THREAD

**Issue by fuyunjiuxiao** [jin-yufeng/mp-html#455]
## 使用环境  
微信小程序   2.25.4

## 问题描述  
<p style=\"text-align: start;\">忙碌了一年是时候好好休息啦！\uD83D\uDE17\uD83D\uDE33\uD83D\uDC80</p><p style=\"text-align: start;\"><br></p><p style=\"text-align: start;\">避开熙熙攘攘的人群，拥抱美好的冬日暖阳，自驾出行宝藏露营地来啦！</p><p style=\"text-align: start;\">地点：老谷仓营地</p><p style=\"text-align: start;\">建议自驾导航至“THEOLDARN老谷仓”（上海市青浦区陈新路585号）</p><p style=\"text-align: start;\">秋收结束后的稻田是什么样子的呢</p><p style=\"text-align: start;\">金色的浪潮退去后</p><p style=\"text-align: start;\">留下满地金黄落叶</p><p style=\"text-align: start;\">站在田头眺望</p><p style=\"text-align: start;\">像是给稻田铺上了一床</p><p style=\"text-align: start;\">看不到边际的被子</p><p style=\"text-align: start;\">微风拂过</p><p style=\"text-align: start;\">风中隐约还有淡淡稻香</p><p style=\"text-align: start;\">暖暖阳光懒懒爬进帐</p><p style=\"text-align: start;\">幽幽微醺淡淡咖啡香</p><p style=\"text-align: start;\">在老谷仓的一切都是慢悠悠</p><p style=\"text-align: start;\">没有喧闹的市集</p><p style=\"text-align: start;\">没有炫目的灯光</p><p style=\"text-align: start;\">一顶不大的帐篷</p><p style=\"text-align: start;\">一片金色的草坪</p><p style=\"text-align: start;\">一旁深爱的家人</p><p style=\"text-align: start;\">一切都是最好的模样</p><p style=\"text-align: start;\"><br></p><p style=\"text-align: start;\">新年新气象|老谷仓全新升级</p><p style=\"text-align: start;\">新增加了热水洗碗啦，YYDS，当然24小时热水淋浴也都有哦~~</p><p style=\"text-align: start;\">营地中心建立，提供基础服务，价格亲民，气罐10/个、预定即送5斤柴火，续柴仅需3元/斤营地</p><p style=\"text-align: start;\">服务全新升级，帅气的管家George服务</p>
![image](https://user-images.githubusercontent.com/109142751/187620813-1fb176fb-f3b6-4def-88df-8768b5c531b5.png)

**Comment by changjiangqian** [comment]
我也有这个问题，如何解决？只要有表情标签就乱了

**Comment by changjiangqian** [comment]
@fuyunjiuxiao

**Comment by changjiangqian** [comment]
@jin-yufeng
