### ISSUE TITLE
插件属性化

### ISSUE THREAD

**Issue by jxfsuda** [jin-yufeng/mp-html#456]
目前插件需下载源码编译

有没有可能,增加一个plugins的属性,给我一个数组或者对象注入实现插件方法.
我的需求较简单,在onParse的时候,对各种标签进行个性化style注入,无需编译源码.且更新麻烦.

另问:
标签的 自定义属性能解析进去吗?  比如 我们自定义了  data-id="car"  或  preview-type="newwin" 这样的

谢谢

**Comment by jin-yufeng** [comment]
通过源码编译加载插件是因为小程序空间有限，为了不增加不必要的大小，没有用到的插件就不加载进去，如果通过属性方式加载插件就必须把所有插件都添加到组件包里  
`data-` 属性在 `img` 和 `a` 标签中有效，可以在 `imtap` 和 `linktap` 事件中获取，其他标签会自动去除

**Comment by jxfsuda** [comment]
哦,我思考了一下,貌似较插件不太合适,  filter 或者拦截器之类的好点, 目前我是新建了一个demo插件,实现了onParse方法, 在这个里面可以无限扩展. 因为我不需要自定义标签.  
这样尽量对源码减少改动.
