### ISSUE TITLE
请问小程序端mp-html 可以插入表格吗？

### ISSUE THREAD

**Issue by renhuan** [jin-yufeng/mp-html#459]
## 问题描述  
请问小程序端mp-html 可以插入表格吗？

**Comment by renhuan** [comment]
目前后端插入表格 可以解析修改，小程序端如果要插入表格呢

**Comment by jin-yufeng** [comment]
可以啊，有 `insertTable` 方法，可参考 [示例](https://github.com/jin-yufeng/mp-html-demo/blob/master/pages/demo/demo.js#L212)

**Comment by renhuan** [comment]
好的，多谢
