### ISSUE TITLE
文本宽度超过屏幕时，不会自动换行

### ISSUE THREAD

**Issue by MRwangqi** [jin-yufeng/mp-html#461]
## 使用环境  
- 小程序平台，基础库为 mp-html:2.4.0 版本

## 问题描述  
- mp-html 展示富文本内容时，文本宽度超过屏幕时，会展示不全，可不可以超过宽度时自动换行

我的富文本 html 是：
```
<pre>
<strong>解释:</strong> 将一格0变成1，最终连通两个小岛得到面积为 3 的岛屿。
</pre>
```

strong 标签后面的内容在屏幕宽度不够的时候，会展示不全

**Comment by jin-yufeng** [comment]
1. 组件内也可以横向滚动，不能滚动的话提供可复现的 `demo`
2. 要自动换行不要用 `pre` 标签或者给 `pre` 设置 `white-space: pre-wrap`

**Comment by MRwangqi** [comment]
> 1. 组件内也可以横向滚动，不能滚动的话提供可复现的 `demo`
> 2. 要自动换行不要用 `pre` 标签或者给 `pre` 设置 `white-space: pre-wrap`

感谢回复，用  white-space: pre-wrap 可以
