### ISSUE TITLE
字节小程序源码引入方式不显示编辑器

### ISSUE THREAD

**Issue by 501956430** [jin-yufeng/mp-html#462]
demo地址 https://developer.open-douyin.com/ide/minicode/6uMw2sf

``` 

ttml:
<mp-html content="{{html}}" />


js:
Page({
    onLoad () {
      this.setData({
        html: '<div>Hello World!</div>'
      })
    }
  })
```

<img width="365" alt="截屏2022-09-19 18 29 56" src="https://user-images.githubusercontent.com/20204491/190998816-c3e62b12-f8a9-441f-af93-f388d322c66f.png">

如何显示这样：
![2EEBC5DB-CDA1-49D8-8AF4-B7C13C4C2AEC_1_102_o](https://user-images.githubusercontent.com/20204491/191000335-664113f4-c20f-451d-97ad-6026a220a8cc.jpeg)

**Comment by jin-yufeng** [comment]
1. 给 `mp-html` 标签设置 `editable` 属性后即可编辑  
2. 工具栏需要在页面上自行配置，可以参考 [示例项目](https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=editable_demo)

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 501956430** [comment]
<img width="680" alt="截屏2022-09-19 18 55 57" src="https://user-images.githubusercontent.com/20204491/191002581-79359ba7-82ab-4c12-b600-64312260b25a.png">
@jin-yufeng
