### ISSUE TITLE
a链接后面有时会自动换行

### ISSUE THREAD

**Issue by glsnh** [jin-yufeng/mp-html#465]
## 使用环境  
微信小程序

## 问题描述  
a链接后面有时会自动换行，如果后面的文字能正好一行容纳不会出现，否则就会自动换行。试了一下更改模拟器机型，如果一行能容纳也不会自动换行。
![问题截图](https://tx.glsnh.cn/自动换行反馈.png)

## 复现方式  
```
全球领先的中文搜索引擎——<a href='https://www.baidu.com/'>点击跳转到百度</a>、致力于让网民更便捷地获取信息，找到所求。
<br>
全球领先的中文搜索引擎——<a href='https://www.baidu.com/'>点击跳转到百度</a>、致力于网民更
<br>
全球领先的中文搜索引擎——<a href='https://www.baidu.com/'>点击跳转到百度</a>、致力于
```

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目，我测试没发现有这个问题
![微信截图_20221015120608](https://user-images.githubusercontent.com/48236054/195967998-09dc4559-e612-4663-9d52-68182d2ba6eb.png)

**Comment by glsnh** [comment]
设置 selectable 为 false后果然就好了，但是没办法选择文字了啊

![对比图片](https://tx.glsnh.cn/docsify/mp-html/20221023214947.png)

**Comment by jin-yufeng** [comment]
https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=selectable

**Comment by 0zcl** [comment]
@glsnh 设置 selectable 为 force，也出现图片上的情况，会自动换行了。请问大哥解决了么

**Comment by jin-yufeng** [comment]
@glsnh 这是微信原生限制，要可复制就会变成 `inline-block` 布局， 应该只能自己调整 `html` 内容使得在这种情况下不会很怪
