### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by BuYiErSan** [jin-yufeng/mp-html#468]
## 问题描述  
为啥都是压缩过得，我需要没压缩的版本重构一下，群主能否提供一下

**Comment by jin-yufeng** [comment]
src 目录下的就是没压缩的源码

**Comment by BuYiErSan** [comment]
在这个站点看到了
https://jin-yufeng.gitee.io/mp-html/#/overview/feature
非常感谢作者


| |
buyiersan
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月12日 12:22 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jin-yufeng/mp-html] 源码问题 (Issue #468) |

src 目录下的就是没压缩的源码
