### ISSUE TITLE
使用源码样式不正确

### ISSUE THREAD

**Issue by BuYiErSan** [jin-yufeng/mp-html#469]
## 问题描述  
![image](https://user-images.githubusercontent.com/115606744/195262043-be143659-9612-40f2-bae5-153a1e0bee69.png)
![image](https://user-images.githubusercontent.com/115606744/195262136-e373ed27-74d3-4a7e-8389-7e07463c2f0a.png)

使用源码，图片不能正常显示

**Comment by BuYiErSan** [comment]
![1665555744915](https://user-images.githubusercontent.com/115606744/195265521-133cbfee-c2d3-4a17-a0dc-e515a982a9f1.png)

补充一下，两个源码的差异

**Comment by jin-yufeng** [comment]
源码要构建后再用
https://jin-yufeng.gitee.io/mp-html/#/advanced/develop

**Comment by jin-yufeng** [comment]
那你的直接引用是指什么
html内容是什么
描述清楚

**Comment by BuYiErSan** [comment]
### 正常
1、使用  npm install mp-html
2、{"usingComponents": {"mp-html": "mp-html"}}
3、<mp-html content="{{html}}" />

### 异常
1、npm run build:weixin
2、将源码中对应平台的代码包（dist/platform）拷贝到 components 目录下，更名为 mp-html
3、{ "usingComponents": {"mp-html": "/components/mp-html/index"}}

### html内容
<p><img src="https://file.tencentads.com/files/uedit/image/20221012/6380117319617013751528924.jpg" _src="https://file.tencentads.com/files/uedit/image/20221012/6380117319617013751528924.jpg" title="落地页风格.jpg" alt="落地页风格.jpg"/></p>

**Comment by BuYiErSan** [comment]
我再全局样式增加了
image {
    max-width: 100%;
}
解决了这个问题，不知道是bug还是我这里环境的问题，谢谢作者了
