### ISSUE TITLE
设置lazy-load=true 提示一个错误

### ISSUE THREAD

**Issue by iamxjb** [jin-yufeng/mp-html#470]
## 使用环境  
微信小程序

## 问题描述  
提示错误
<img width="646" alt="1665831923824" src="https://user-images.githubusercontent.com/1930574/195983203-9ca30589-df96-4032-8c78-6d7b7b65fd37.png">

## 复现方式  
在开发工具里提示 ,  在正文里没有图片也会报这个错误。
经过调试检查提示错误的代码是：src/miniprogram/index.js
<img width="781" alt="1665832227757" src="https://user-images.githubusercontent.com/1930574/195983348-941a8f7d-9f72-4745-97ad-c55ffa269da0.png">

<img width="928" alt="1665832319476" src="https://user-images.githubusercontent.com/1930574/195983404-bd0d41a6-2617-40f9-9974-c1671ec90ef5.png">

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目
