### ISSUE TITLE
taro 中 linktap 事件无反应

### ISSUE THREAD

**Issue by Tom-Jack-Huang** [jin-yufeng/mp-html#471]
## 问题描述  
 <mp-html content={htmlStr} copyLink={false} linktap={(e)=>{
            console.log('233333333')
            alert('2222222');
          }}/>

**Comment by jin-yufeng** [comment]
react的话应该写作onLinktap吧

**Comment by Embrace924** [comment]
![image](https://github.com/jin-yufeng/mp-html/assets/42015704/1a8b6357-1dd9-4ec0-8618-7169a46a544e)
还是无响应 点击事件

**Comment by Embrace924** [comment]
> ![image](https://user-images.githubusercontent.com/42015704/265579070-1a8b6357-1dd9-4ec0-8618-7169a46a544e.png) 还是无响应 点击事件

ok了
