### ISSUE TITLE
mp-html编译报错

### ISSUE THREAD

**Issue by ha159** [jin-yufeng/mp-html#472]
[ WXML 文件编译错误] ./uni_modules/mp-html/components/mp-html/node/node.wxml
 Bad attr `nodes` with message
  27 | }

**Comment by jin-yufeng** [comment]
提供可复现的 demo

**Comment by fyk00395** [comment]
插件市场 
![image](https://user-images.githubusercontent.com/87518771/202070353-b9ae389d-2c5a-4730-b148-b4dc7c546779.png)
在页面中直接使用 编译报错
![image](https://user-images.githubusercontent.com/87518771/202070451-6ce8acfa-b9e0-46d5-a6c2-873f91d48c93.png)

**Comment by fyk00395** [comment]
![image](https://user-images.githubusercontent.com/87518771/202075191-33c15c45-48a9-408a-9a31-576ca9b7136b.png)
去掉:nodes可解决

**Comment by fyk00395** [comment]
问题来源：
![image](https://user-images.githubusercontent.com/87518771/202077526-65619807-8426-4219-b49b-1ba186154562.png)
:nodes

**Comment by chuanchengbingyu** [comment]
小程序中使用确实不行，大神在2.4.0的调整不兼容小程序了，2.4.0之前版本都可以
![QQ截图20221125145514](https://user-images.githubusercontent.com/5027357/203920171-73e40306-a8fb-4577-9f68-c0f1f8287a84.png)

**Comment by jin-yufeng** [comment]
@chuanchengbingyu @fyk00395 示例项目无法复现此问题，有问题按模板要求提供可复现的demo和环境信息

**Comment by chuanchengbingyu** [comment]
秦元发已收到你的邮件！

**Comment by 521qq** [comment]
我也遇到了这个问题，就是采用uni-app版本的源码方式引入之后，编译为小程序会出现这个问题

**Comment by jin-yufeng** [comment]
这个问题应该是由 uni-app 编译器版本太老导致的，可以升级一下

**Comment by chuanchengbingyu** [comment]
秦元发已收到你的邮件！
