### ISSUE TITLE
富文本渲染异常

### ISSUE THREAD

**Issue by DangerousBaymax** [jin-yufeng/mp-html#475]
## 问题描述  
uni-app的微信与抖音小程序环境下，对如下富文本渲染时，会频繁换行，原本一行的内容会变成多行，原因是什么，是因为富文本编辑的时候操作过头导致标签太杂了么？

`"<span style=\"color: rgb(57, 116, 244); font-size: 16px; font-family: 黑体, SimHei;\"><strong><span style=\"font-size: 16px; color: rgb(57, 116, 244); font-family: 黑体;\">本周</span></strong><span style=\"font-size: 16px; color: rgb(57, 116, 244); font-family: 黑体, SimHei;\"><strong><span style=\"font-size: 16px; font-family: 黑体;\">国内</span></strong><strong><span style=\"font-size: 16px; font-family: 黑体;\"><a href=\"antsoo://appExponentPush?materialsName=PP&top=1\" target=\"_blank\" style=\"color: rgb(57, 116, 244);\">PP</a>市场震荡运行</span></strong></span></span><span style=\"font-size: 16px; font-family: 黑体, SimHei;\"><span style=\"font-size: 16px; color: rgb(57, 116, 244); font-family: 黑体, SimHei;\"><strong><span style=\"font-size: 16px; font-family: 黑体;\">，主流牌号周涨跌幅20-200元/吨。</span></strong></span></span>"`

渲染效果：

![952700B4-561F-4e2c-8677-951E8CAF3F2F](https://user-images.githubusercontent.com/40587075/200262439-ca58845b-7ce3-4836-aef9-e5b8d3f81df6.png)

另外，我试了一下如果连续使用strong标签，也会产生这种换行的情况

`<strong>12</strong><strong>34</strong>`

我把富文本标签自行整理了下如图...

![F4191271-A068-469b-B56F-AF101B08968A](https://user-images.githubusercontent.com/40587075/200262399-41c3c11c-7f27-481d-94b0-87db3772b55e.png)

最后还有一个问题就是，为什么我下载新的mp-html源码放到项目里面以后，编译会报错：

`Bad attr `nodes` with message`

希望能得到您的回复...这个换行问题看了好久了没有解决办法...

**Comment by jin-yufeng** [comment]
提供可复现的 demo 项目

**Comment by DangerousBaymax** [comment]
您用我上面给出的富文本就可以复现了大佬

**Comment by jin-yufeng** [comment]
我在示例项目里测试没有出现你说的情况

**Comment by DangerousBaymax** [comment]
好的，那等我手头上的事情忙完弄一个demo

**Comment by oszc** [comment]
同样问题
