### ISSUE TITLE
新人请教，所有console事件均无反应

### ISSUE THREAD

**Issue by jpgaus** [jin-yufeng/mp-html#477]
新手请教

后台图片保存为相对路径，/uploads/image/aa.jpg，但无法显示图片。 
1，组件参数已添加 domain="http://my.xx.com" 
2，chrome跟了一下，get url为 localhost:8080/uploads/...，似乎没有替换成功 
3，在app真机运行也是不显示 
4，该图片完整路径真实存在，保存于服务器中，在浏览器中可直接打开，不涉及跨域盗链设置
5，已查看说明与常见问题，没找到解决办法。

-》 补充
很奇怪，chrome调试，文档内容均可以正常显示，但是所有的事件，比如 ready, linktap等，都没有任何console显示
重新下载插件/右键更新，重启应用，还是这个情况

**Comment by jin-yufeng** [comment]
demo项目测试正常，有问题提供复现方式  
路径拼接：
![微信截图_20221202202922](https://user-images.githubusercontent.com/48236054/205293246-b0524f15-c775-475f-9032-27d5533eb53a.png)
![微信截图_20221202202937](https://user-images.githubusercontent.com/48236054/205293279-21d7d413-a877-4b38-b5ba-0bff79769c20.png)
事件信息：  
![微信截图_20221202202827](https://user-images.githubusercontent.com/48236054/205293071-4f61e8ab-34bc-41f9-b96f-e78df0d4efbe.png)

**Comment by jpgaus** [comment]
非常感谢！
一直没收到github邮件回复提醒，幸亏登录看看，我再试一下！
