### ISSUE TITLE
Taro3 Vue3 引入mp-html后无法渲染content内容

### ISSUE THREAD

**Issue by HuangYaobin** [jin-yufeng/mp-html#478]
## 使用环境  
taro3.5.8

## 问题描述  
![image](https://user-images.githubusercontent.com/51368773/205229071-d03092f1-fdad-45b7-8e71-563ad37883e1.png)

## 复现方式  
https://github.com/HuangYaobin/taro-mphtml-demo.git

**Comment by Zejia** [comment]
请问解决了吗？ 我好像也遇见这个问题

**Comment by jin-yufeng** [comment]
#511
