### ISSUE TITLE
pre>code 内容会自动换行

### ISSUE THREAD

**Issue by Ucer** [jin-yufeng/mp-html#482]
见下图：第一段后有个换行符没换行

原html 格式如下 
```html
<h1 id="代码块">代码块</h1>
<pre><code class="language-js">
1、哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中哈哈哈哈哈哈中 
2、第2段
</code></pre>
```

渲染出来结果如下 
![image](https://user-images.githubusercontent.com/28194791/211230479-0bebd9b3-f5ac-4463-806c-0a9d1bdc5199.png)

**Comment by jin-yufeng** [comment]
![微信截图_20230225182443](https://user-images.githubusercontent.com/48236054/221351866-21c06007-c3a5-4abf-8860-414b69db62c9.png)
提供可复现的 `demo` 项目
