### ISSUE TITLE
UniApp Editable 运行在微信小程序中 ToolTip 错位

### ISSUE THREAD

**Issue by a77uu** [jin-yufeng/mp-html#484]
## 使用环境  
微信小程序 （2.29.1）

## 问题描述  
如果 mp-html 在 uni-forms 表单中并且作为 uni-forms-item 中的元素，ToolTip 将会错位 (top的值随机)

## 复现方式  
按上述方式写在vue页面中，ToolTip 会错位到页面底部（超出了所有元素撑大的高度）

**Comment by jin-yufeng** [comment]
提供可复现的demo项目
