### ISSUE TITLE
taro 飞书小程序用taro原生模块引入 页面报错

### ISSUE THREAD

**Issue by lzy383408003** [jin-yufeng/mp-html#485]
## 使用环境  
  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

## 问题描述  
进入使用了mp-html页面报下面错误
[TMA][ERROR][RUNTIME] TypeError: this.behaviors.forEach is not a function
    at t.<anonymous> (tma-core.js:3)
    at new t (tma-core.js:3)
    at lR (tma-core.js:3)
    at ./src/components/mp-Html/index.js (index.js:196)
    at __webpack_require__ (runtime.js? [sm]:80)
    at checkDeferredModules (runtime.js? [sm]:46)
    at Array.webpackJsonpCallback [as push] (runtime.js? [sm]:33)
    at index.js:1
    at Pw (tma-core.js:3)
    at Gg.require (tma-core.js:3)
[TMA][WARN][RUNTIME] Page route 错误: Page[pages/take-car/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.
[TMA][ERROR][RUNTIME] Page.data should be an object

## 复现方式  
              <View className={styles.Text}>
                <View className={styles.mb40}>
                  {protocol.length > 0 && (
                    <mp-html content={protocol[protocolIdx].richTextDescription} />
                  )}
                </View>
              </View>

## 相应页面index.config.js配置
              export default {
                usingComponents: {
                  'mp-html': '../../components/mp-html/index'
                }
              };

**Comment by jin-yufeng** [comment]
提供可复现的 demo

**Comment by jin-yufeng** [comment]
taro 只能使用各平台的原生包，飞书可能不行
