### ISSUE TITLE
关于某些a连接会换到新行问题

### ISSUE THREAD

**Issue by xiuluo-psz** [jin-yufeng/mp-html#488]
## 使用环境  
微信小程序平台，基础库2.29.2，mp-html版本2.4.1

## 问题描述  
同样的html代码段，在PC上，a标签紧跟着文字后。作为mp-html的富文本后，a标签会换行。请问有什么办法让当前情况的a标签紧跟文字后面
小程序上异常截图
![image](https://user-images.githubusercontent.com/39213524/216211205-9ad11d40-d35c-42d3-abf2-f9c1192d6258.png)
PC上正常截图
![新建位图图像](https://user-images.githubusercontent.com/39213524/216212145-5648b72a-6cf9-4542-9b8e-baa218b339ec.png)

## 复现方式  
代码段如下
`<p style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">同样的html代码段，在PC上，a标签紧跟着文字后。作为mp-html的富文本后，a标签会换行。请问有什么办法让当前情况的a标签紧跟文字后面<a href=" "><sup>1</sup></a ></p >`

**Comment by songxinglin98** [comment]
这个问题解决了嘛

**Comment by jin-yufeng** [comment]
该行放不下了就自动换行了吧
强行不换行的话我觉得除非改成这样 `<span style="white-space:nowrap">面<a href=" "><sup>1</sup></a></span>`
不过我测试好像没出现这种情况，要么都在上一行，要么和最后一个字一起到下一行
![微信截图_20230324214424](https://user-images.githubusercontent.com/48236054/227537609-25ef5d11-9334-41bb-b5e5-4b34991737ba.png)
