### ISSUE TITLE
uni_module方式引入mp-html，开发版真机调试正常，体验版真机体验失败

### ISSUE THREAD

**Issue by casatwy** [jin-yufeng/mp-html#489]
## 问题描述  

按照mp-html文档给到的uni-app下uni_module安装方式引入mp-html，开发版真机调试正常，体验版真机体验失败。
<img width="834" alt="截屏2023-02-09 20 49 28" src="https://user-images.githubusercontent.com/1005781/217817360-92f57a0f-ec19-447b-8b0d-d8e035ef8020.png">

在微信小程序开发工具里面能够看到HBuilder X已经存在mp-html：
<img width="296" alt="截屏2023-02-09 21 34 10" src="https://user-images.githubusercontent.com/1005781/217827268-00d8fb0a-7044-4845-8b5e-b055cbd67260.png">

微信小程序运行截图如下：

<img width="435" alt="截屏2023-02-09 20 45 06" src="https://user-images.githubusercontent.com/1005781/217817827-217b4b62-5b08-414b-b7b3-6aa313b7e243.png">

<img width="444" alt="截屏2023-02-09 20 43 23" src="https://user-images.githubusercontent.com/1005781/217818168-445c877c-ce57-43cf-9936-d1cf6d37ae9d.png">

**Comment by serein-man** [comment]
+1，只有安卓APP正式包会这样不显示内容；微信小程序，ios包正常
