### ISSUE TITLE
uniapp中，使用mp-html，会出现富文本渲染丢失的情况，频率较高，富文本中可能含有svg，但是也有些没有特殊字符的渲染不出来

### ISSUE THREAD

**Issue by lululu222** [jin-yufeng/mp-html#493]

**Comment by jin-yufeng** [comment]
提供复现方式

**Comment by lululu222** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zouvchen** [comment]
> 提供复现方式

你好，微信小程序里，富文本中svg中animate标签，begin是click，无法出现效果。能不能帮忙看看，谢谢。
<svg width="500" height="500"><circle cx="100" cy="100" r="50" fill="#7fd"><animate attributeName="r" from="50" to="100" dur="2s" fill="freeze" repeatCount="2" repeatDur="6s" begin="click" calcMode="linear" keyTimes="0;0.5;1" values="10;50;20"></animate></circle></svg>

**Comment by zouvchen** [comment]
‘<svg width="500" height="500"><circle cx="100" cy="100" r="50" fill="#7fd"><animate attributeName="r" from="50" to="100" dur="2s" fill="freeze" repeatCount="2" repeatDur="6s" begin="click" calcMode="linear" keyTimes="0;0.5;1" values="10;50;20"></animate></circle></svg>’

**Comment by zouvchen** [comment]
`<svg width="500" height="500"><circle cx="100" cy="100" r="50" fill="#7fd"><animate attributeName="r" from="50" to="100" dur="2s" fill="freeze" repeatCount="2" repeatDur="6s" begin="click" calcMode="linear" keyTimes="0;0.5;1" values="10;50;20"></animate></circle></svg>`

**Comment by jin-yufeng** [comment]
> > 提供复现方式
> 
> 你好，微信小程序里，富文本中svg中animate标签，begin是click，无法出现效果。能不能帮忙看看，谢谢。

小程序原生不支持 `svg`，是转成 `img` 显示的，`click` 这种无法生效

**Comment by lululu222** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
