### ISSUE TITLE
uni app tx-video组件，进入页面的时候视频自动播放了，如何取消自动播放呢？

### ISSUE THREAD

**Issue by imtiger** [jin-yufeng/mp-html#494]
## 问题描述  
每次进入页面，视频都自动播放了，试了pausemedia方法，也没有效果。

<img width="726" alt="image" src="https://user-images.githubusercontent.com/2855042/223601310-0efa551f-4f02-4780-969b-8d8cfe35e088.png">
请问这种如何解决，进入页面不要自动播放视频。

**Comment by jin-yufeng** [comment]
腾讯视频插件 [v1](https://github.com/tvfe/txv-miniprogram-plugin/blob/master/archieve/readme.md) 不会自动播放，[v2](https://github.com/tvfe/txv-miniprogram-plugin) 会自动播放，可以按需选择
