### ISSUE TITLE
代码高亮的HTML部分也会被解析

### ISSUE THREAD

**Issue by sandycs-protoss** [jin-yufeng/mp-html#501]
## 问题描述  
如果某一段代码是HTML，希望将它代码高亮。有没有好的办法？
因为它被包含在PRE里，但还是会被mp-html解析。就显示不正常了

**Comment by jin-yufeng** [comment]
`html` 代码要用实体编码 `&lt;` 和 `&gt;`，不然会被认为是标签

**Comment by guaobai** [comment]
感谢
