### ISSUE TITLE
使用小程序方式引入插件文档说明增加细节信息

### ISSUE THREAD

**Issue by Chen-Page** [jin-yufeng/mp-html#502]
使用小程序方式直接引入插件
在文档中没有具体的说明怎么引入
希望能加上说明信息，方便使用

![image](https://user-images.githubusercontent.com/42233758/226794308-920e35a6-3fae-42e3-bb2d-b62186a3ddd7.png)

**Comment by jin-yufeng** [comment]
https://jin-yufeng.gitee.io/mp-html/#/advanced/plugin?id=use
