### ISSUE TITLE
["usingComponents"]["mp-html"]: "mp-html" 未找到

### ISSUE THREAD

**Issue by jacksonjim** [jin-yufeng/mp-html#503]
## 使用环境  

微信小程序，原生开发工具，项目使用typescript 
  "dependencies": {
    "mp-html": "^2.4.1"
  },
  "devDependencies": {
    "miniprogram-api-typings": "^3.9.0",
    "typescript": "^4.9.5"
  },

## 问题描述  

[ miniprogram/pages/ifmtInfo/ifmtInfo.json 文件内容错误] miniprogram/pages/ifmtInfo/ifmtInfo.json: ["usingComponents"]["mp-html"]: "mp-html" 未找到(env: Windows,mp,1.06.2303060; lib: 2.30.2)

**Comment by jin-yufeng** [comment]
构建 `npm` 了没有

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jacksonjim** [comment]
构建是构建了，后面发现原因放在根目录上的package.json 一直是不行，另外你们的说明没有说明与新版本的开发者工具的差异，新版本的是有些步骤不需要操作！project&nbsp;
-&nbsp;&nbsp;miniprogram
&nbsp; &nbsp;-- package.json 需要在这个目录中增加这个文件，npm&nbsp; install mp-html&nbsp; 才有能正常编译
-&nbsp; package.json
&nbsp;





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年5月13日(星期六) 晚上6:15
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [jin-yufeng/mp-html] [&quot;usingComponents&quot;][&quot;mp-html&quot;]: &quot;mp-html&quot; 未找到 (Issue #503)





 
构建 npm 了没有
