### ISSUE TITLE
uni-app vite+vu3+ts 使用markdown插件报错

### ISSUE THREAD

**Issue by yunexuan** [jin-yufeng/mp-html#508]
## 使用环境  

uni-app 3.0
vue 3.2
vite 4.0.4

## 问题描述  

![image](https://user-images.githubusercontent.com/21151159/231660880-62d35b94-0eb0-4bb5-ab22-08f42323b876.png)

## 复现方式  

使用源码添加markdown插件后打包后放入到uni_modules中
![image](https://user-images.githubusercontent.com/21151159/231661155-830ebe3e-ad6a-4b49-a661-2f7b2483ffbe.png)

**Comment by jin-yufeng** [comment]
提供可复现的 demo
