### ISSUE TITLE
lazyLoad提示未定义

### ISSUE THREAD

**Issue by woxiaoyao81** [jin-yufeng/mp-html#513]
## 使用环境  
mp-html版本号：v2.4.1，HbuilderX版本3.7.11，微信小程序没有问题，APP中使用图片懒加载lazyLoad

## 问题描述  
一般是在初次时，会报node.vue中lazyLoad未定义错误

## 复现方式  
content是包括图片html
```
<mp-html lazy-load container-style="padding:5px 10px;font-size:1.2em;" :content="content"/>
```
加载时有时报会报node.vue中lazyLoad未定义错误，经查源码初步定位于node的mounted中获取根节点部分代码的问题
```
this.$nextTick(() => {
  for (this.root = this.$parent; this.root.$options.name !== 'mp-html'; this.root = this.root.$parent);
})	
```
APP端应该渲染太快，this.root并不是根节点，此时访问this.root.lazyLoad导致报错

**Comment by jin-yufeng** [comment]
暂时没复现出来，不过可能出现的话加个条件判断好了
