### ISSUE TITLE
不能渲染这段特殊的文字

### ISSUE THREAD

**Issue by gitzhanghaogit** [jin-yufeng/mp-html#514]
解析不了下面的文字  uni-app不会报错  会直接卡死页面 不能返回 不能点击 页面失去响应  最后查出来是 mp-html 不能解析导致的
## 使用环境  

uviewui 1.5.7 版本 或者直接官网教程 也是解析不了这段文字
## 问题描述  

uviewui 1.5.7 版本 使用 u-parse 解析不了下面的文字   不会报错  会卡死页面 u-parse 采用的是mp-html 为富文本解析 mp-html也解析不了
## 复现方式  

官网教程解析不了这段html文字

 [解析]当工程量偏差项目出现承包人在工程量清单中填报的综合单价与发包人招标控制价相应清单项目的综合单价偏差超过15％时，工程量偏差项目综合单价的调整可参考以下公式：
1)当P0<P2×(1-L)×(1-15％)时，该类项目的综合单价：
P1按照P2×(1-L)×(1-15％)调整(7-5)
2)当P0>P2×(1+15％)时，该类项目的综合单价：
P1按照P2×(1+15％)调整(7-6)
3)当P0>P2×(1-L)×(1-15％)或P0<P2×(1+15％)时，可不予调整。
式中P0—承包人在工程量清单中填报的综合单价；
P2—发包人在招标控制价相应项目的综合单价；
L—计价规范中定义的承包人报价浮动率。
本题中P2×(1-L)×(1-15％)=350×（1-5%）×(1-15％)=282.625<300，故可不予调整。

**Comment by jin-yufeng** [comment]
示例项目解析正常，提供可复现的 demo 项目

**Comment by sampsonliu** [comment]
可以解析
<img width="413" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/15682051/1f630c93-b284-4dec-917f-cfbaec1af337">
