### ISSUE TITLE
markdown脚注渲染问题

### ISSUE THREAD

**Issue by a82327636** [jin-yufeng/mp-html#516]
--markdown内容 
//aaaaa   [^1]。
//关系整理通顺[^2]。

//[^1]: 评论121
//[^2]: 评论221

--mp-html渲染结果
//aaaaa^1
//关系整理通顺^2

脚注没有显示，也不能点击
(将上面“//”去掉再验证)

**Comment by jin-yufeng** [comment]
markdown 采用 [marked](https://github.com/markedjs/marked) 进行解析，不支持脚注语法  
不过需要使用的话可以用 [markedjs-extra](https://github.com/xiaoliwang/markedjs-extra) 里的 `markedjs_extra.min.js` 替代原来的 `marked.min.js`
