### ISSUE TITLE
动态拼接markdown字符串会造成闪动

### ISSUE THREAD

**Issue by mmdlsu** [jin-yufeng/mp-html#517]
## 问题描述  
uniapp中用作ChatGPT内容渲染时，流式输出时，拼接markdown字符串会造成闪动，请问有什么解决办法？
![screenshots](https://github.com/jin-yufeng/mp-html/assets/57515771/ac100429-a561-4522-b186-9ad1e5cc97bf)

**Comment by mmdlsu** [comment]
找到解决办法了更新到marked最新[已经修复闪烁的问题](https://github.com/markedjs/marked/issues/2751)

**Comment by lidingbang** [comment]
所以应该怎么修复，我也遇到了。求指教

**Comment by mmdlsu** [comment]
升级marked.min.js

**Comment by lidingbang** [comment]
请问如何升级。我复制最新的代码上去报错
"default" is not exported by "../../../../program/yi-li-si/dist/uni-app/components/mp-html/markdown/marked.min.js", imported by "../../../../program/yi-li-si/dist/uni-app/components/mp-html/markdown/index.js".
15:16:33.512 at dist/uni-app/components/mp-html/markdown/index.js:6:7
15:16:33.517   4:  * Include github-markdown-css (https://github.com/sindresorhus/github-markdown-css)
15:16:33.517   5:  */
15:16:33.521   6: import marked from './marked.min'
15:16:33.521             ^
15:16:33.524   7: let index = 0

**Comment by mmdlsu** [comment]
> 请问如何升级。 我复制最新的代码上去报错 “默认”不是由“../../../../program/yi-li-si/dist/uni-app/components/mp-html/markdown/marked.min.js“，由”../../../../program/yi-li-si/dist/uni-app/components/mp-html/markdown/index.js“. 15：16：33.512 at dist/uni-app/components/mp-html/markdown/index.js：6：7 15：16：33.517 4： * 包括 github-markdown-css （ [https://github.com/sindresorhus/github-markdown-css ](https://github.com/sindresorhus/github-markdown-css)） 15：16：33.517 5： */ 15：16：33.521 6：导入标记自“./marked.min” 15：16：33.521 ^ 15：16：33.524 7：let index = 0

![image](https://github.com/jin-yufeng/mp-html/assets/57515771/06391688-ff85-49c4-b716-5b22c375c143)

**Comment by lidingbang** [comment]
再次打扰了。我是先npm包下来，然后找到marked.min.js的代码复制下来，最后粘贴在mp-html的marked.min.js。请问升级方法是这样吗

**Comment by mmdlsu** [comment]
> 再次打扰了。我是先npm包下来，然后找到marked.min.js的代码复制下来，最后粘贴在mp-html的marked.min.js。请问升级方法是这样吗

小程序里面打包，把旧的marked.min.js替换为最新的

**Comment by mmdlsu** [comment]
> 再次打扰了。我是先npm包下来，然后找到marked.min.js的代码复制下来，最后粘贴在mp-html的marked.min.js。请问升级方法是这样吗

![image](https://github.com/jin-yufeng/mp-html/assets/57515771/44fea014-24c1-4ea6-97cd-b873a1199429)

**Comment by mmdlsu** [comment]
> 实在不好意思，打扰了。我复制的文件还是不行，是因为marked没有导出方法，而mp-html有，我自己加导出会有问题。所以可以让我复制大佬的marked.min.js代码吗

用uni_modules的形式，不要用npm，不好修改

**Comment by zyMacro** [comment]
> 再次打扰了。我是先npm包下来，然后找到marked.min.js的代码复制下来，最后粘贴在mp-html的marked.min.js。请问升级方法是这样吗

请问你解决这个问题了吗

**Comment by zyMacro** [comment]
> > 实在不好意思，打扰了。我复制的文件还是不行，是因为marked没有导出方法，而mp-html有，我自己加导出会有问题。所以可以让我复制大佬的marked.min.js代码吗
> 
> 用uni_modules的形式，不要用npm，不好修改

大佬，我直接把marked.min.js文件替换成https://github.com/markedjs/marked/commits/master/marked.min.js项目的文件，但没有work报错了，需要做些其他的处理吗，比如index.js需要改动吗
<img width="336" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/9b317bfb-d256-4f6e-b2d9-770ded384f9c">

**Comment by mmdlsu** [comment]
![image](https://github.com/jin-yufeng/mp-html/assets/57515771/e7495a2c-4245-4d5e-800a-93c2ab428765)

**Comment by zyMacro** [comment]
> ![image](https://user-images.githubusercontent.com/57515771/259936617-e7495a2c-4245-4d5e-800a-93c2ab428765.png)

大佬的意思是在index.js中加入marked.use吗，我试了一下好像还是不行。
<img width="569" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/624d9d2a-5b63-4fa9-8eb5-a58f62b92730">
<img width="1127" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/7f23d89a-2737-4f94-aded-4af7ac804875">
<img width="1186" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/4bba969a-4f72-474a-8df7-0540e72181f3">

**Comment by mmdlsu** [comment]
用marked  v5.0.2

**Comment by zyMacro** [comment]
> 用marked v5.0.2

<img width="1100" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/a9979c48-b523-41f6-8aae-805c268d8a2d">
v5.0.2试过了也不行，应该是直接替换了就可以了对吧，这也不存在编译啥的？

**Comment by mmdlsu** [comment]
[mp-html.zip](https://github.com/jin-yufeng/mp-html/files/12319361/mp-html.zip)

**Comment by zyMacro** [comment]
> 我直接打包一份把你试试[mp-html.zip](https://github.com/jin-yufeng/mp-html/files/12319361/mp-html.zip)
感谢大佬，确实work了，我比较了一下，不知道是不是下面这行代码的原因？
<img width="1146" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/a8d77913-2899-4a7b-b56b-df4f8d53b579">
另外，还想问下，我有个eventstream的接口返回的字符串（类似下图，每次新加一个字符这样），我先是直接把内容传给content，这样由于相当于每次都是重新渲染，导致经常闪烁，我试过改成setcontent传入新增的字符，但是每次追加的字符会直接换行展示。想问下大佬，有什么建议吗。
<img width="635" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/8efab12a-dfdd-4f74-8113-c8563151e051">

**Comment by mmdlsu** [comment]
我是这样直接拼接的list[i].content +=content

**Comment by zyMacro** [comment]
> 我是这样直接拼接的list[i].content +=content

大佬，还想问个问题。为什么用了您打的包以后，代码高亮失效了，我看你这也引入了highlight啊，另外可以大致告诉我你打的包work的原因吗，跟markdown文件夹以外的内容有关系吗，因为我直接把我的包里面markdown替换掉也还是不行

**Comment by zyMacro** [comment]
> 我直接打包一份把你试试[mp-html.zip](https://github.com/jin-yufeng/mp-html/files/12319361/mp-html.zip)

大佬，还是想打扰下，为什么你这个包的代码高亮失效了呀

**Comment by mmdlsu** [comment]
截图看看
<mp-html class="char-text char-text-me" :content="" markdown selectable/>

**Comment by zyMacro** [comment]
> 截图看看 `<mp-html :content="" markdown selectable/>`
<img width="503" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/ab880a79-d901-4674-99f1-aa7adaddb875">

我是直接用大佬打的包，然后看着文档改了这个地方，看着只有js支持的好一些。
<img width="873" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/6067ef76-b9e0-4198-9dbb-3b95e446c02b">
然后查了下文档，https://marked.js.org/using_advanced#highlight
高亮相关的配置都在5.0版本废弃了，换用marked-highlight
<img width="873" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/17961768/6067ef76-b9e0-4198-9dbb-3b95e446c02b">
但我不知道我们这种用法，index.js里应该怎样引入marked-highlight包
https://www.npmjs.com/package/marked-highlight

**Comment by mmdlsu** [comment]
没问题哦，我这里测试js、java、php都有高亮
![image](https://github.com/jin-yufeng/mp-html/assets/57515771/ec0b1aad-2637-4e3f-b543-e94faf16def0)

**Comment by zyMacro** [comment]
> 没问题哦，我这里测试js、java、php都有高亮 ![image](https://user-images.githubusercontent.com/57515771/260655461-ec0b1aad-2637-4e3f-b543-e94faf16def0.png)

我理解的代码高亮是关键字，变量等都是各用一种颜色，我看您这图里面好像颜色也比较单一

**Comment by mmdlsu** [comment]
我那个就是代码高亮，你可以测试从插件中去掉
![image](https://github.com/jin-yufeng/mp-html/assets/57515771/687ce345-2f75-417e-ab24-05f5e638ec85)
要显示行号的话可以开启，我是关了的
![image](https://github.com/jin-yufeng/mp-html/assets/57515771/1e46a770-62d5-4f83-90d8-d0774f084aa3)

**Comment by mmdlsu** [comment]
> > 没问题哦，我这里测试js、java、php都有高亮 ![image](https://user-images.githubusercontent.com/57515771/260655461-ec0b1aad-2637-4e3f-b543-e94faf16def0.png)
> 
> 我理解的代码高亮是关键字，变量等都是各用一种颜色？我看您这图里面好像颜色也比较单一。 比如下面这样？ <img alt="image" width="295" src="https://user-images.githubusercontent.com/17961768/260660016-94ba6c7f-9528-4eb7-a725-85000be3b2ef.png">

我可能理解错了，有时间再看看

**Comment by mmdlsu** [comment]
> > 没问题哦，我这里测试js、java、php都有高亮 ![image](https://user-images.githubusercontent.com/57515771/260655461-ec0b1aad-2637-4e3f-b543-e94faf16def0.png)
> 
> 我理解的代码高亮是关键字，变量等都是各用一种颜色？我看您这图里面好像颜色也比较单一。 比如下面这样？ <img alt="image" width="295" src="https://user-images.githubusercontent.com/17961768/260660016-94ba6c7f-9528-4eb7-a725-85000be3b2ef.png">

mp-html用的是prism.min.js，目前把  langPrefix: ''删掉对js有效果，去prism官网有语言选择不知道是不是没加上语言
![image](https://github.com/jin-yufeng/mp-html/assets/57515771/f087989b-9107-412b-9a72-88b0840bb420)

**Comment by zyMacro** [comment]
> > > 没问题哦，我这里测试js、java、php都有高亮 ![image](https://user-images.githubusercontent.com/57515771/260655461-ec0b1aad-2637-4e3f-b543-e94faf16def0.png)
> > 
> > 
> > 我理解的代码高亮是关键字，变量等都是各用一种颜色？我看您这图里面好像颜色也比较单一。 比如下面这样？ <img alt="image" width="295" src="https://user-images.githubusercontent.com/17961768/260660016-94ba6c7f-9528-4eb7-a725-85000be3b2ef.png">
> 
> mp-html用的是prism.min.js，目前把 langPrefix: ''删掉对js有效果，去prism官网有语言选择不知道是不是没加上语言 ![image](https://user-images.githubusercontent.com/57515771/260688884-f087989b-9107-412b-9a72-88b0840bb420.png)

感谢大佬，确实是这个问题，默认语言只有js等几种，手动加上其他的以后就work了
