### ISSUE TITLE
markdown可以支持换行吗？

### ISSUE THREAD

**Issue by 2424004764** [jin-yufeng/mp-html#534]
## 问题描述  
可以换行吗？
![image](https://github.com/jin-yufeng/mp-html/assets/24261680/2d4b9a0d-fbe8-4249-8277-d5c342902090)

**Comment by jin-yufeng** [comment]
可以通过 [tag-style](https://jin-yufeng.gitee.io/mp-html/#/basic/prop?id=tag-style) 给 `pre` 标签设置
