### ISSUE TITLE
video 无法退出全屏

### ISSUE THREAD

**Issue by LvJing520** [jin-yufeng/mp-html#535]
## 使用环境  

vue3版本，h5在安卓手机上
## 问题描述  

video标签点击全屏按钮全屏后无法退出全屏
![image](https://github.com/jin-yufeng/mp-html/assets/25576929/49385d52-4eaa-4e28-a263-c3cb7843586f)

## 复现方式  

html：<p><br></p><div data-w-e-type="video" data-w-e-is-void>
<video poster="https://haowu-mp-oss-test.lkhaowu.cn/halvie-eaf-fe-resource/resource/26/image/1689064748100-51628.jpg" controls="true" width="auto" height="auto"><source src="https://image-upyun.halvie.com/resource/26/video/1677747185715-62277.mp4" type="video/mp4"/></video>
</div><p><br></p>

**Comment by jin-yufeng** [comment]
`video` 标签表现和本组件无关
