### ISSUE TITLE
base64图片无法预览

### ISSUE THREAD

**Issue by zzsscc** [jin-yufeng/mp-html#536]
https://github.com/jin-yufeng/mp-html/blob/d67be378ebda5d690a92dad9b3adb431b593c8d8/src/miniprogram/parser.js#L424

这里会导致base64图片无法预览，是出于什么原因这么做呢？

**Comment by CharlesDIP** [comment]
是的 base64格式的图片 点击不能预览

**Comment by jin-yufeng** [comment]
#249
