### ISSUE TITLE
markdown代码高亮块gt,lt未解析？

### ISSUE THREAD

**Issue by yhtsnda** [jin-yufeng/mp-html#538]
## 使用环境  
uniapp

## 问题描述  
markdown代码高中的&gt和&lt未解析
## 复现方式  
![image](https://github.com/jin-yufeng/mp-html/assets/1248897/2b57db1c-7f3f-47fc-8126-a4aa14adc100)
![image](https://github.com/jin-yufeng/mp-html/assets/1248897/98dec6d3-450d-48d1-8dfb-3c72641d9473)

**Comment by jin-yufeng** [comment]
`markdown` 里不用写 `lt;` 吧
```python
if arr &lt; 3
```
