### ISSUE TITLE
使用latex插件, 加载html中latex公式,在小程序中会换行

### ISSUE THREAD

**Issue by xuhang1993** [jin-yufeng/mp-html#540]
![image](https://github.com/jin-yufeng/mp-html/assets/12042799/403433b1-afe8-44f9-abb5-c10265803de4)
![image](https://github.com/jin-yufeng/mp-html/assets/12042799/da18f886-6c12-479a-8135-e6f8d7c7cff2)
let html2 =
  '"<p> <span class="mathrc"contenteditable="false" unselectable="on">$ \\sqrt 3$</span>与 <span class="mathrc"contenteditable="false" unselectable="on">$ \\sqrt 3$</span> 二次根式</p>"';

**Comment by drucker2310** [comment]
@xuhang1993   我的也是，使用latex时，用string.raw转换的latex代码，出现了文字和公式换行，你的解决了吗
/

**Comment by drucker2310** [comment]
@ jin-yufeng @ Zeng-J   能否给个latex正确换行和不换行的处理示例呢

**Comment by drucker2310** [comment]
感谢作者的回答，这个问题在mp-html/atex文件夹下的index.js文件中将下面代码的 name 的字符串由‘div’改为 span
 if ((index + 1) % 2 === 0) {
        return {
          name: 'div',
          attrs: {},
          f: 'display:inline-block',
          children: parse.default(str)
        }

**Comment by kdsemfosdk** [comment]
您那个转义符是怎么处理的呢？一个斜杠不是处理不了吗？

**Comment by drucker2310** [comment]
如果不在脚本区写，而在组件上写就不需要转换。在脚本区的话，你可以用string.raw转化就可以了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月04日 18:18 |
| 收件人 | jin-yufeng/mp-html ***@***.***> |
| 抄送人 | drucker2310 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [jin-yufeng/mp-html] 使用latex插件, 加载html中latex公式,在小程序中会换行 (Issue #540) |

您那个转义符是怎么处理的呢？一个斜杠不是处理不了吗？

**Comment by kdsemfosdk** [comment]
html:"$\textrm {e}^{+}\textrm {e}^{-}\rightarrow τ^{+}τ^{-}$",        this.html2=String.raw`this.html`     这样不行呀  大佬

**Comment by drucker2310** [comment]
你为什么不按我发的来

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月04日 20:35 |
| 收件人 | jin-yufeng/mp-html ***@***.***> |
| 抄送人 | drucker2310 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [jin-yufeng/mp-html] 使用latex插件, 加载html中latex公式,在小程序中会换行 (Issue #540) |

html:"$\textrm {e}^{+}\textrm {e}^{-}\rightarrow τ^{+}τ^{-}$", this.html2=String.rawthis.html 这样不行呀 大佬

**Comment by kdsemfosdk** [comment]
里面放原始模板字符串可以   我这边场景是需要变量   一放变量就不行了

**Comment by drucker2310** [comment]
原始那就不是模板字符串，我不是已经给你放到变量里了吗，不然html 是什么，不是变量吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月05日 09:13 |
| 收件人 | jin-yufeng/mp-html ***@***.***> |
| 抄送人 | drucker2310 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [jin-yufeng/mp-html] 使用latex插件, 加载html中latex公式,在小程序中会换行 (Issue #540) |

里面放原始模板字符串可以 我这边场景是需要变量 一放变量就不行了

**Comment by typing233** [comment]
那如果我 想换行，用什么，/n无效

**Comment by drucker2310** [comment]
> 那如果我 想换行，用什么，/n无效

用 \\
