### ISSUE TITLE
loadingImg的大小如何设置呢？

### ISSUE THREAD

**Issue by qtbui159** [jin-yufeng/mp-html#543]
## 问题描述  
loadingImg的大小如何设置呢？谢谢

**Comment by jin-yufeng** [comment]
目前的逻辑是如果 `img` 的 `style` 里设置了大小就按照设置的显示，如果没有就按照 `loadingImg` 本身的大小显示，要修改目前只能在[源码](https://github.com/jin-yufeng/mp-html/blob/master/src/miniprogram/node/node.wxml#L37)上改
