### ISSUE TITLE
支付宝图片设置宽高后被解析为mode=""导致显示不出来

### ISSUE THREAD

**Issue by Evelyn0910** [jin-yufeng/mp-html#544]
## 使用环境  

支付宝小程序

## 问题描述  

![image](https://github.com/jin-yufeng/mp-html/assets/51017029/8c9eb9c1-b6b0-4309-8d49-37c4207885ab)

## 复现方式  

<img style="width:120px ; height:120px ; display: block;" title="请上传图片" src="https://xxx" alt="请上传图片,宽度：120px ，高度：120px " data-v-48790b81="" />

**Comment by Evelyn0910** [comment]
图片实际可以打开，已用<image src="" />测试过

**Comment by Evelyn0910** [comment]
代码片段：<img style="width:120px ; height:120px ; display: block;" title="请上传图片" src="https://xxx" alt="请上传图片,宽度：120px ，高度：120px " data-v-48790b81="" />

**Comment by Evelyn0910** [comment]
代码片段：`<img style="width:120px ; height:120px ; display: block;" title="请上传图片" src="https://zhicall.zjuss.cn/yizhuimages/20230807/16914139116358514734.jpeg" alt="请上传图片,宽度：120px ，高度：120px " data-v-48790b81="" />`

**Comment by Evelyn0910** [comment]
代码片段：<img style="width:120px ; height:120px ; display: block;" title="请上传图片" src="https://xxx" alt="请上传图片,宽度：120px ，高度：120px " data-v-48790b81="" />

**Comment by Evelyn0910** [comment]
代码片段：`<img style="width:120px ; height:120px ; display: block;" title="请上传图片" src="https://xxx" alt="请上传图片,宽度：120px ，高度：120px " data-v-48790b81="" />`

**Comment by jin-yufeng** [comment]
![微信截图_20230923180201](https://github.com/jin-yufeng/mp-html/assets/48236054/09ece8fc-bc93-4097-8978-5b99d81b1b37)

**Comment by jin-yufeng** [comment]
一个空的 `mode` 图片似乎会被截取
