### ISSUE TITLE
span标签设置text-align： justify 两端未对齐

### ISSUE THREAD

**Issue by weihong991010** [jin-yufeng/mp-html#546]
## 使用环境  

uni-app 微信小程序 
## 问题描述  

<img width="344" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/57937445/079e85a1-1ca6-4707-a395-5ecb35e52878">

## 复现方式  
<img width="497" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/57937445/4827cb13-2369-4d12-a4e5-f845bc709c08">

**Comment by jin-yufeng** [comment]
`text-align` 要加在块级标签上，加在 `span` 上是没有用的

**Comment by jin-yufeng** [comment]
提供可复现的 `demo` 项目
