### ISSUE TITLE
关于新版将不支持getSystemInfo，不知道能否改成getSystemInfoAsync

### ISSUE THREAD

**Issue by zero3412** [jin-yufeng/mp-html#549]
## 问题描述
开发者工具提示：
Current Wechat version do not support asynchronous getSystemInfo. "wx.getSystemInfoAsync" will be finished by synchronous implementation.

## 需求
（腾讯小程序版）每次看到开发者工具中有这样的提示就很不爽，不知道能否改进下呢?

**Comment by jin-yufeng** [comment]
这个提示说的是不支持异步吧

**Comment by jin-yufeng** [comment]
`getSystemInfoAsync` `2.14.1` 才支持，组件内用的是 `getSystemInfoSync`，没有说新版不支持吧

**Comment by zero3412** [comment]
> `getSystemInfoAsync` `2.14.1` 才支持，组件内用的是 `getSystemInfoSync`，没有说新版不支持吧

是哦，哈哈哈，眼拙了，这提示也真是。。。 。。。
