### ISSUE TITLE
plus is not defined 

### ISSUE THREAD

**Issue by jonsen-liu** [jin-yufeng/mp-html#554]
微信小程序使用 报错  ReferenceError: plus is not defined

**Comment by jonsen-liu** [comment]
![image](https://github.com/jin-yufeng/mp-html/assets/26186472/04114105-d9d8-4f25-873b-100c1ef2210a)

**Comment by jonsen-liu** [comment]
每人知道是什么问题么？

**Comment by jin-yufeng** [comment]
plus 是条件编译到 app 端的，不知道你是怎么使用的，参考一下示例吧

**Comment by XieMiLe** [comment]
我的项目中也复现了，有个富文本是正常的，只有这一段富文本是报错的，怀疑是html的导致的。`<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about1.37cee314.png" srcset="" /></p>\r\n\r\n<p data-v-31b62ad2="">&ldquo;一物一码&rdquo; -饮片-&ldquo;&rdquo;</p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about2.c59a2963.png" srcset="" /></p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about3.4eede27c.png" srcset="" /></p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about4.f6244ad7.png" srcset="" /></p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p data-v-31b62ad2=""></p>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about5.70ff8777.png" srcset="" /></p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p data-v-31b62ad2=""></p>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about6.ced57e41.png" srcset="" /></p>\r\n\r\n<h1 data-v-40403607="" style="text-align: center;"><strong></strong></h1>\r\n\r\n<p data-v-31b62ad2=""></p>\r\n\r\n<p style="text-align: center;"><img alt="" data-v-31b62ad2="" src="https://sxcyfw.daodikeji.com/img/about7.ec24f44d.png" srcset="" /></p>`

**Comment by jin-yufeng** [comment]
`getUrl` 里的 `plus` 是条件编译到 `app` 端的，正常编译到微信小程序是不会有的  
如果是 `cli` 编译的要注意 https://github.com/jin-yufeng/mp-html/issues/330#issuecomment-913617687
