### ISSUE TITLE
使用表情后，页面渲染错误。

### ISSUE THREAD

**Issue by changjiangqian** [jin-yufeng/mp-html#557]
这是使用mp-html渲染出的节点的代码：
[{"name":"p","attrs":{},"children":[{"type":"text","text":"第一站：[生气] 1️⃣嘉定图书馆：裕民南路1288号😰😣💎11231232131</p"}]}]

这是我内容代码
<img width="487" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/145734470/987aa92d-57b2-42be-af0d-ff57971330c5">

**Comment by changjiangqian** [comment]
这是渲染图：
<img width="1108" alt="image" src="https://github.com/jin-yufeng/mp-html/assets/145734470/126f7272-71a5-4468-964a-381782b327af">

**Comment by jin-yufeng** [comment]
![微信截图_20231023173732](https://github.com/jin-yufeng/mp-html/assets/48236054/32be8ba0-e12f-437f-a19e-120a6bf9176f)
提供可复现的demo项目

**Comment by changjiangqian** [comment]
发现问题了，微信小程序的appjson要设置： "lazyCodeLoading": "requiredComponents"，可能是因为引入了其它组件冲突，貌似冲突的组件是：painter
