### ISSUE TITLE
iOS真机未渲染tag-style定义的table的border样式

### ISSUE THREAD

**Issue by suxiaogang** [jin-yufeng/mp-html#558]
## 使用环境  
微信小程序，iOS 16.6，基础库 2.29.2

## 问题描述  
开发者工具中可正常显示tag-style定义的td border样式，真机未能显示

## 复现方式  
```
<mp-html tag-style="{{tagStyle}}" content="{{tableHTML}}" />

data: {
    tableHTML: '<table><tbody><tr><td>Cell1</td><td>Cell2</td></tr><tr><td>Cell11</td><td>Cell22</td></tr></tbody></table>',
    tagStyle: {
        table: 'border-collapse:collapse;font-size:22rpx;background-color:#f5f5f5;',
        td: 'border:1rpx solid #000;',
        hr: 'border-top:none;border-bottom:1rpx dashed #b5b5b5;margin:40rpx 0;'
    }
},
```

<img width="400" alt="开发者工具" src="https://github.com/jin-yufeng/mp-html/assets/1567518/c258cd0e-4553-497d-9539-108dfdf34455">

<img width="400" alt="真机" src="https://github.com/jin-yufeng/mp-html/assets/1567518/10ecd068-6f28-41ec-97e2-875e3d5cc854">

**Comment by suxiaogang** [comment]
补充：更加严格的说，应该是只有table的border的属性真机渲染有问题

刚才特意设置了background-color:red，开发者工具和真机都会起作用，但border依旧不行

**Comment by allanwxl** [comment]
得改下node.vue逻辑
