### ISSUE TITLE
微信小程序渲染解析以下格式的html异常包含（sgv animate）

### ISSUE THREAD

**Issue by yu110212539** [jin-yufeng/mp-html#560]
微信小程序渲染以下结构首张图片不展示，h5端解析正常。
`<html><head></head><body><section style="line-height: 2;font-size: 14px;box-sizing: border-box;font-style: normal;font-weight: 400;text-align: justify;" data-mpa-powered-by="yiban.io"><section style="text-align: left;margin-top: 10px;margin-bottom: 10px;line-height: 0;box-sizing: border-box;" powered-by="xiumi.us"><section style="max-width: 100%;vertical-align: middle;display: inline-block;line-height: 0;width: 80%;height: auto;box-sizing: border-box;"><img class="rich_pages wxw-img" data-ratio="0.09052631578947369" data-s="300,640" data-src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/bc918b3eb7dab9dc9ab0827f07cfe2c3.png?sign=244936862-1699284048650-4739-664f0bdea931fc679b6666c7a00c113f" data-w="475" style="vertical-align: middle;max-width: 100%;width: 100%;box-sizing: border-box;" src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/bc918b3eb7dab9dc9ab0827f07cfe2c3.png?sign=244936862-1699284048650-8493-9c987b77f045a5400ff947decf87cf59"></section></section><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="user-select: text;overflow: hidden;text-align: center;line-height: 0;max-width: 100%;box-sizing: border-box;-webkit-user-select: text;"><section style="overflow: hidden;box-sizing: border-box;"><section style="max-width: 100%;margin-top: -1px;box-sizing: border-box;" powered-by="xiumi.us"><section style="overflow: hidden;max-width: 100%;box-sizing: border-box;"><section style="overflow: hidden;box-sizing: border-box;"><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="height: 0px;line-height: 0;max-width: 100%;box-sizing: border-box;"><section style="box-sizing: border-box;"><section style="display: contents;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: contents;box-sizing: border-box;"><section style="display: contents;width: 100%;box-sizing: border-box;"><svg opacity="0" style="background-size: 100%;background-repeat: no-repeat;display: inline;max-width: 100%;background-image: url(&quot;https://cms-test-cdn.shede.cn/business-res/wxContentSync/747a1e2f37ec043518855e5d2d1caf77.png?sign=244936862-1699284048650-3287-76f5b63dfb2a02fea088fa921e7978a5&quot;);box-sizing: border-box;" viewbox="0 0 1080 1920"><animate attributename="opacity" values="0;1" begin="0.1s" dur="0.01s" fill="freeze" restart="never" style="box-sizing: border-box;"></animate></svg></section></section></section><section style="display: contents;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: contents;box-sizing: border-box;"><section style="display: contents;width: 100%;box-sizing: border-box;"><svg style="background-size: 100%;background-repeat: no-repeat;display: block;line-height: 0;margin-top: 0px;transform: scale(1);-webkit-transform: scale(1);-moz-transform: scale(1);-o-transform: scale(1);max-width: 100%;background-image: url(&quot;https://cms-test-cdn.shede.cn/business-res/wxContentSync/1fcd848230c50e06a0e43f5da4106bb1.png?sign=244936862-1699284048650-6619-b06c102be30b588a04e8096f8c175825&quot;);box-sizing: border-box;" viewbox="0 0 1080 6610"></svg></section></section></section></section></section></section><section style="max-width: 100%;transform: rotateZ(0deg);-webkit-transform: rotateZ(0deg);-moz-transform: rotateZ(0deg);-o-transform: rotateZ(0deg);pointer-events: none;box-sizing: border-box;" powered-by="xiumi.us"><section style="line-height: 0;max-width: 100%;box-sizing: border-box;"><section style="display: contents;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: contents;box-sizing: border-box;"><section style="display: contents;width: 100%;box-sizing: border-box;"><svg viewbox="0 0 1080 1919" style="pointer-events: none;max-width: none !important;box-sizing: border-box;"><animate attributename="width" fill="freeze" restart="never" calcmode="spline" keysplines="0.42 0 0.58 1.0; 0.42 0 0.58 1.0" keytimes="0;0.001;1" values="100%;443.7708333333333%;443.7708333333333%" dur="5000s" begin="click+0.5s" style="box-sizing: border-box;"></animate><g opacity="0" style="box-sizing: border-box;"><animate attributename="opacity" values="0;1" begin="0s" dur="0.01s" fill="freeze" restart="never" style="box-sizing: border-box;"></animate><animate attributename="opacity" values="1;0" dur="0.5s" begin="click" restart="never" style="box-sizing: border-box;"></animate><foreignobject x="0" width="1080" height="1920" style="box-sizing: border-box;"><svg style="background-size: 100%;background-repeat: no-repeat;display: inline;line-height: 0;pointer-events: painted;background-image: url(&quot;https://cms-test-cdn.shede.cn/business-res/wxContentSync/98c461e90c795aec8275001f514c4ed8.png?sign=244936862-1699284048650-1523-4c27d27acae60c00e27b077a44ecb6ad&quot;);box-sizing: border-box;" viewbox="0 0 1080 1920"><animate attributename="height" begin="click+0.5s" restart="never" dur="0.00001s" to="0" fill="freeze" calcmode="discrete" style="box-sizing: border-box;"></animate></svg></foreignobject></g></svg></section></section></section></section></section></section></section></section></section></section></section><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="font-family: PingFangSC-light;letter-spacing: 1px;line-height: 2;font-size: 16px;max-width: 100%;text-align: left;box-sizing: border-box;"><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;"><section style="display: inline-block;width: 100%;vertical-align: top;align-self: flex-start;flex: 0 0 auto;background-color: rgb(252, 250, 249);box-sizing: border-box;"><section style="max-width: 100%;margin-top: -4px;width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="flex-flow: row nowrap;max-width: 100%;width: 100%;box-sizing: border-box;"><section style="display: flex;justify-content: flex-start;flex-direction: row;max-width: 100%;box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section></section></section></section></section><p style="white-space: normal;margin: 0px;padding: 0px;box-sizing: border-box;" powered-by="xiumi.us"><br style="box-sizing: border-box;"></p><section style="display: flex;flex-flow: row nowrap;text-align: left;justify-content: flex-start;margin: 15px 0% 0px;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;vertical-align: top;width: auto;align-self: stretch;flex: 0 0 0%;height: auto;margin: 0px;border-width: 0px;box-sizing: border-box;"><section style="transform: perspective(0px);-webkit-transform: perspective(0px);-moz-transform: perspective(0px);-o-transform: perspective(0px);transform-style: flat;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: flex;flex-flow: row nowrap;text-align: center;justify-content: center;margin: 0px 0% 5px;transform: rotateX(180deg);-webkit-transform: rotateX(180deg);-moz-transform: rotateX(180deg);-o-transform: rotateX(180deg);box-sizing: border-box;"><section style="display: inline-block;vertical-align: bottom;width: auto;align-self: flex-end;flex: 0 0 0%;line-height: 0;height: auto;box-sizing: border-box;"><section style="margin: 11px 0% -5px;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 6px;height: 6px;vertical-align: top;overflow: hidden;border-style: solid;border-width: 1px;border-radius: 50px 0px 50px 50px;border-color: rgb(217, 185, 135);box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="display: inline-block;vertical-align: top;width: 22px;flex: 0 0 auto;align-self: stretch;height: auto;border-style: none none solid solid;border-width: 1px;border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(217, 185, 135) rgb(217, 185, 135);box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="display: inline-block;vertical-align: top;width: auto;flex: 100 100 0%;align-self: stretch;height: auto;border-left: 1px solid rgb(217, 185, 135);border-bottom-left-radius: 0px;margin: 0px -20px 0px -22px;box-sizing: border-box;"><section style="margin: 5px 0% 3px;transform: translate3d(-7px, 0px, 0px);-webkit-transform: translate3d(-7px, 0px, 0px);-moz-transform: translate3d(-7px, 0px, 0px);-o-transform: translate3d(-7px, 0px, 0px);justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 100%;vertical-align: top;background-color: rgba(217, 171, 100, 0.07);padding: 0px 0px 0px 10px;align-self: flex-start;flex: 0 0 auto;box-sizing: border-box;"><section style="margin: 0px 0%;box-sizing: border-box;" powered-by="xiumi.us"><section style="color: rgb(217, 185, 135);padding: 0px 10px;text-align: center;box-sizing: border-box;"><p style="margin: 0px;padding: 0px;box-sizing: border-box;"><strong style="box-sizing: border-box;">互 动 话 题</strong></p></section></section></section></section></section><section style="display: inline-block;vertical-align: top;width: auto;align-self: stretch;flex: 0 0 0%;height: auto;box-sizing: border-box;"><section style="transform: perspective(0px);-webkit-transform: perspective(0px);-moz-transform: perspective(0px);-o-transform: perspective(0px);transform-style: flat;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: flex;flex-flow: row nowrap;text-align: center;justify-content: center;margin: 0px 0% 5px;transform: rotateX(180deg) rotateY(180deg);-webkit-transform: rotateX(180deg) rotateY(180deg);-moz-transform: rotateX(180deg) rotateY(180deg);-o-transform: rotateX(180deg) rotateY(180deg);box-sizing: border-box;"><section style="display: inline-block;vertical-align: bottom;width: auto;align-self: flex-end;flex: 0 0 0%;line-height: 0;height: auto;box-sizing: border-box;"><section style="margin: 11px 0% -5px;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 6px;height: 6px;vertical-align: top;overflow: hidden;border-style: solid;border-width: 1px;border-radius: 50px 0px 50px 50px;border-color: rgb(217, 185, 135);box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="display: inline-block;vertical-align: top;width: 18px;flex: 0 0 auto;align-self: stretch;height: auto;border-style: none none solid solid;border-width: 1px;border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(217, 185, 135) rgb(217, 185, 135);box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section></section><section style="margin: -5px 0% 10px;text-align: left;justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 100%;vertical-align: top;padding: 0px 6px;border-width: 0px;align-self: flex-start;flex: 0 0 auto;box-sizing: border-box;"><section style="text-align: justify;justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 100%;vertical-align: top;border-left: 1px solid rgb(217, 185, 135);border-bottom-left-radius: 0px;padding: 0px;border-right: 1px solid rgb(217, 185, 135);border-top-right-radius: 0px;align-self: flex-start;flex: 0 0 auto;box-sizing: border-box;"><section style="transform: translate3d(4px, 0px, 0px);-webkit-transform: translate3d(4px, 0px, 0px);-moz-transform: translate3d(4px, 0px, 0px);-o-transform: translate3d(4px, 0px, 0px);margin: 5px 0% -10px;justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 100%;vertical-align: top;border-width: 0px;background-color: rgba(255, 255, 255, 0);padding: 10px 20px 15px 15px;align-self: flex-start;flex: 0 0 auto;box-sizing: border-box;"><section style="margin: 0px 0%;box-sizing: border-box;" powered-by="xiumi.us"><section style="color: rgb(48, 47, 46);text-align: center;padding: 0px 10px;line-height: 2;letter-spacing: 1px;box-sizing: border-box;"><p style="margin: 0px;padding: 0px;box-sizing: border-box;"><span style="background-color: rgba(255, 255, 255, 0);"></span><br></p><p>金秋丰收时，杯酒敬舍得</p><p>在评论区分享你成长路上的点滴收获&nbsp;</p><p style="margin: 0px;padding: 0px;box-sizing: border-box;">我们将在<span style="color: rgb(217, 185, 135);box-sizing: border-box;">10月27号</span></p><p style="margin: 0px;padding: 0px;box-sizing: border-box;">挑选出1位精选用户</p><p style="margin: 0px;padding: 0px;box-sizing: border-box;">送出100ml舍得小酒1瓶</p><p style="margin: 0px;padding: 0px;box-sizing: border-box;"><br></p></section></section></section></section><section style="font-size: 0px;margin: 0px 0%;justify-content: flex-start;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 97%;vertical-align: top;flex: 0 0 auto;height: auto;align-self: flex-start;box-sizing: border-box;"><section style="margin: 4px 0% 5px;transform: translate3d(-6px, 0px, 0px);-webkit-transform: translate3d(-6px, 0px, 0px);-moz-transform: translate3d(-6px, 0px, 0px);-o-transform: translate3d(-6px, 0px, 0px);box-sizing: border-box;" powered-by="xiumi.us"><section style="background-color: rgb(217, 185, 135);height: 1px;box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section></section></section></section></section><p style="white-space: normal;margin: 0px;padding: 0px;box-sizing: border-box;" powered-by="xiumi.us"><br style="box-sizing: border-box;"></p><section style="text-align: center;justify-content: center;display: flex;flex-flow: row nowrap;box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: auto;vertical-align: top;min-width: 10%;max-width: 100%;flex: 0 0 auto;height: auto;line-height: 0.5;padding: 0px 10px;align-self: flex-start;box-sizing: border-box;"><section style="margin: 10px 0%;box-sizing: border-box;" powered-by="xiumi.us"><section style="font-size: 16px;color: rgb(217, 185, 135);text-align: right;text-shadow: rgba(251, 220, 173, 0.65) 1px 3px;letter-spacing: 3px;box-sizing: border-box;"><p style="text-align: center;margin: 0px;padding: 0px;box-sizing: border-box;"><span style="font-size: 18px;box-sizing: border-box;"><strong style="box-sizing: border-box;">往期推荐</strong></span></p></section></section><section style="box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block;width: 20px;height: 3px;vertical-align: top;overflow: hidden;border-top: 1px solid rgb(217, 185, 135);border-top-left-radius: 0px;line-height: 0.5;box-sizing: border-box;"><svg viewbox="0 0 1 1" style="float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><a title="https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247538322&amp;idx=1&amp;sn=d37a7c4cd76ebab7251ec13289556220&amp;scene=21#wechat_redirect" formlinkparm="&quot;https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247538322&amp;idx=1&amp;sn=d37a7c4cd76ebab7251ec13289556220&amp;scene=21#wechat_redirect&quot;" href="https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247538322&amp;idx=1&amp;sn=d37a7c4cd76ebab7251ec13289556220&amp;scene=21#wechat_redirect" target="_blank" rel="noopener noreferrer" powered-by="xiumi.us" data-linktype="1"><section style="text-align: center;margin-top: 10px;margin-bottom: 10px;line-height: 0;box-sizing: border-box;"><section style="max-width: 100%;vertical-align: middle;display: inline-block;line-height: 0;box-sizing: border-box;"><span class="js_jump_icon h5_image_link"><img class="rich_pages wxw-img" data-ratio="0.32222222222222224" data-s="300,640" data-src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/5a42f9dd02fc402a40f5f2a1e98e8afd.jpeg?sign=244936862-1699284048650-2286-911005b87c4b3616751cc71269dba47d" data-w="1080" style="vertical-align: middle;max-width: 100%;width: 100%;box-sizing: border-box;" src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/5a42f9dd02fc402a40f5f2a1e98e8afd.jpeg?sign=244936862-1699284048650-1531-5cd08ee5d7babc67f5aa0b24cdd585e4"></span></section></section></a><a title="https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247537716&amp;idx=1&amp;sn=0dc36692b4b91538e18fe70027675e01&amp;scene=21#wechat_redirect" formlinkparm="&quot;https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247537716&amp;idx=1&amp;sn=0dc36692b4b91538e18fe70027675e01&amp;scene=21#wechat_redirect&quot;" href="https://mp.weixin.qq.com/s?__biz=MzUxMjA5NjU1MA==&amp;mid=2247537716&amp;idx=1&amp;sn=0dc36692b4b91538e18fe70027675e01&amp;scene=21#wechat_redirect" target="_blank" rel="noopener noreferrer" powered-by="xiumi.us" data-linktype="1"><section style="text-align: center;margin-top: 10px;margin-bottom: 10px;line-height: 0;box-sizing: border-box;"><section style="max-width: 100%;vertical-align: middle;display: inline-block;line-height: 0;box-sizing: border-box;"><span class="js_jump_icon h5_image_link"><img class="rich_pages wxw-img" data-ratio="0.32222222222222224" data-s="300,640" data-src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/a08dc46df4b545044645c33f42618dd6.png?sign=244936862-1699284048650-4773-2674a19babdaa95f2fba0a114b841fc0" data-w="1080" style="vertical-align: middle;max-width: 100%;width: 100%;box-sizing: border-box;" src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/a08dc46df4b545044645c33f42618dd6.png?sign=244936862-1699284048650-6187-873ff75c20d3b51afe218bd135a47ccc"></span></section></section></a><p style="white-space: normal;margin: 0px;padding: 0px;box-sizing: border-box;" powered-by="xiumi.us"><br style="box-sizing: border-box;"></p><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: unset;-webkit-tap-highlight-color: rgba(0, 0, 0, 0);margin-bottom: 0px;padding-right: 10px;padding-left: 10px;outline: 0px;white-space: normal;background-color: rgb(255, 255, 255);font-size: 16px;line-height: 2;letter-spacing: 1px;color: rgb(160, 160, 160);max-width: 100%;box-sizing: border-box;"><p style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;text-align: center;margin: 0px;padding: 0px;box-sizing: border-box;"><span style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;font-size: 14px;box-sizing: border-box;">扫描下方二维码</span></p><p style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;text-align: center;margin: 0px;padding: 0px;box-sizing: border-box;"><span style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;font-size: 14px;box-sizing: border-box;">关注舍得酒官方视频号</span></p><p style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;text-align: center;margin: 0px;padding: 0px;box-sizing: border-box;"><span style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;font-size: 14px;box-sizing: border-box;">舍得酒官方微信公众号</span></p><p style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;text-align: center;margin: 0px;padding: 0px;box-sizing: border-box;"><span style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;font-size: 14px;box-sizing: border-box;">获取更多老酒资讯</span></p></section></section><section style="max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);margin-top: 10px;margin-bottom: 10px;outline: 0px;color: rgb(34, 34, 34);font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif;letter-spacing: 0.544px;white-space: normal;background-color: rgb(255, 255, 255);font-size: 16px;text-align: center;line-height: 0;max-width: 100%;box-sizing: border-box;"><section style="box-sizing: border-box;"><section style="display: inline-block;max-width: 100%;box-sizing: border-box;" powered-by="xiumi.us"><section style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;line-height: 0;max-width: 100%;box-sizing: border-box;"><section style="max-width: 100%;vertical-align: middle;display: inline-block;line-height: 0;-webkit-tap-highlight-color: rgba(0, 0, 0, 0);outline: 0px;box-sizing: border-box;"><img class="rich_pages wxw-img" data-ratio="0.7125" data-s="300,640" data-src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/f11158596d8dedc9823170e0a45bf1df.gif?sign=244936862-1699284048650-5023-ccf4716ae68c85439cca3ed087fe830c" data-w="640" style="vertical-align: middle;max-width: 100%;width: 100%;box-sizing: border-box;" src="https://cms-test-cdn.shede.cn/business-res/wxContentSync/f11158596d8dedc9823170e0a45bf1df.gif?sign=244936862-1699284048650-7018-79e7bc19fd12b1eee93d81bbb9723b09"></section></section></section></section></section></section></section><p style="display: none;"><mp-style-type data-value="3"></mp-style-type></p></body></html>`
小程序端展示如下：
![2261699256542_ pic](https://github.com/jin-yufeng/mp-html/assets/23101828/14a4c35a-fe26-4847-a88d-5481bc062eae)
浏览器端展示如下：
![2271699256667_ pic_hd](https://github.com/jin-yufeng/mp-html/assets/23101828/a361cf76-cc0f-42ea-aba2-da49625d10d0)

**Comment by jin-yufeng** [comment]
#569
