### ISSUE TITLE
svg图片展示不对

### ISSUE THREAD

**Issue by leecn-web** [jin-yufeng/mp-html#565]
data:image/svg+xml;utf8,<svg width=\"35px\" height=\"38px\" viewBox=\"0 0 35 38\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"https://www.w3.org/1999/xlink\">\n        \n        <g id=\"页面-1\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\n            <g id=\"产品详情页-售后服务-\" transform=\"translate(-326.000000, -1200.000000)\" fill-rule=\"nonzero\">\n                <g id=\"编组备份\" transform=\"translate(326.000000, 1200.000000)\">\n                    <path d=\"M34.9919909,19.4737352 C34.8368136,17.5833939 34.3758458,15.7344469 33.6227796,13.9820867 C32.8879695,12.2757202 31.8930093,10.6935367 30.6652832,9.28612927 C29.4421586,7.8830749 28.0083899,6.6818632 26.4161641,5.72621641 C24.9374159,4.83853788 23.3445668,4.17622852 21.6832571,3.76228516 C21.4504912,1.65117405 19.6659525,0 id=\"形状\" 17.5117267,0 C15.3529369,0 13.5683982,1.65117405 13.3401963,3.76228516 C12.1215982,4.09343985 10.1773182,4.80174292 8.74877442,5.64342774 C7.14223317,6.59549746 5.69543324,7.79133382 4.44488692,9.2033406 C3.18977657,10.6245461 2.17199618,12.2205277 1.41892997,13.9498911 C0.643043567,15.7344469 0.168383652,17.6201888 0.00864233436,19.5565238 C-0.0461261173,20.2096345 0.159255577,20.7799564 0.629351454,21.2950859 C1.0720631,21.7780198 1.7019003,22.0585815 2.35455768,22.0585815 L16.3661532,22.0585815 L16.3661532,32.2277899 C16.3661532,35.4105543 18.9402705,38 22.1031486,38 C25.2614626,38 27.8355798,35.4105543 27.8355798,32.2231905 C27.8355798,31.5930767 27.3244076,31.0779472 26.6991345,31.0779472 C26.0738613,31.0779472 25.5626891,31.5930767 25.5626891,32.2231905 C25.5626891,34.1457274 24.0109163,35.7141128 22.1031486,35.7141128 C20.1908168,35.7141128 18.63448,34.1503268 18.63448,32.2277899 L18.63448,22.0631808 L32.6415115,22.0631808 C33.2941689,22.0631808 33.9240061,21.7826192 34.3712817,21.2996853 C34.8185574,20.8075527 35.0467593,20.1406439 34.9919909,19.4737352 Z M17.5071627,1.98232873 C18.4062781,1.98232873 19.2004206,2.53425321 19.5472875,3.32534495 C17.9270541,3.10457516 16.5304586,3.18736383 15.4579098,3.33454369 C15.8093407,2.53885258 16.6080472,1.98232873 17.5071627,1.98232873 L17.5071627,1.98232873 Z M32.700844,19.7496974 C32.6825878,19.7680949 32.6643317,19.7772936 32.6415115,19.7772936 L17.4706504,19.7726943 C17.4341381,19.7726943 17.3930617,19.7726943 17.3565494,19.7772936 L2.35455768,19.7772936 C2.33173749,19.7772936 2.31348134,19.7680949 2.29522519,19.7496974 C2.272405,19.7267006 2.26327693,19.694505 2.26784097,19.65771 C2.91593431,11.7283951 9.6068135,5.51924473 17.4980346,5.51924473 C25.3892557,5.51924473 32.0755708,11.7283951 32.7282282,19.65771 C32.7327922,19.7083031 32.7145361,19.7358993 32.700844,19.7496974 Z\" fill=\"%23395A84\"></path>\n                    <path id=\"路径\" d=\"M7.79948002,16.9561384 C7.90289692,16.9868415 8.00631383,17 8.10523434,17 C8.49642003,17 8.86512378,16.7894645 9.05397204,16.4385719 C9.35073359,15.88153 9.84533618,15.0481602 10.5197943,14.2235627 C11.585438,12.9252602 12.9388506,11.8155625 14.4316511,11.0128958 C14.9397429,10.7409541 15.1420803,10.1268921 14.894779,9.61371172 C14.7643838,9.34176999 14.5305716,9.14439293 14.2383065,9.05228363 C13.9505377,8.96017434 13.6312942,8.99087743 13.3660073,9.13562061 C11.6214091,10.0742582 10.0431772,11.3681745 8.79767797,12.8857848 C8.40649229,13.3638759 8.06027047,13.8638978 7.77699808,14.2937412 C7.60613537,14.5525244 7.3858124,14.9297339 7.12502194,15.4165973 C6.97214478,15.7060837 6.95865561,16.0438178 7.08905084,16.3420765 C7.21944607,16.635949 7.48023653,16.859643 7.79948002,16.9561384 L7.79948002,16.9561384 Z\" fill=\"%23C70E2D\"></path>\n                </g>\n            </g>\n        </g>\n    </svg>

**Comment by jin-yufeng** [comment]
具体描述问题
