### ISSUE TITLE
请问要修改这块文字的样式，应该设置什么标签啊？

### ISSUE THREAD

**Issue by guohalin** [jin-yufeng/mp-html#566]
<img width="1390" alt="6676737C-EA67-4560-BD6A-4377237A18A6" src="https://github.com/jin-yufeng/mp-html/assets/17847833/fb2933b3-c3dc-4fd4-84fe-5c158867499f">

**Comment by ljt990218** [comment]
完整的字符串能看看嘛。具体看看你渲染的字符串是怎么样的
