### ISSUE TITLE
传入有内容的<a>标签。会导致渲染出来的内容换行

### ISSUE THREAD

**Issue by xfgdemo** [jin-yufeng/mp-html#568]
## 使用环境  
微信小程序，基础库：3.2.3

## 问题描述  
内容自动换行。
如果传入组件的html 中的<a>标签下嵌套了内容。则<a>标签会换行
![无标题](https://github.com/jin-yufeng/mp-html/assets/40196936/c8acac30-7f8b-42c3-9e48-8a951c4dd40d)
![无1题](https://github.com/jin-yufeng/mp-html/assets/40196936/d1b2f595-9413-49f9-a992-b9c95d3f977a)

## 复现方式  
制造一个有嵌套内容的a标签即可

**Comment by ljt990218** [comment]
能贴出你完整一点的字符串嘛，我这样测试不会换行：
html: '<div>aaaa<a href="www.baidu.com"><span style="color:#ccc">嵌套内容</span></a>bbbb</div>'
![WX20240106-104431@2x](https://github.com/jin-yufeng/mp-html/assets/50509815/a3777158-e2cf-4f6a-a9f8-77e07af6e287)
