### ISSUE TITLE
mp html 不支持svg里的响应标签比如rect、foreignObject、animate

### ISSUE THREAD

**Issue by cosmoyqt** [jin-yufeng/mp-html#569]
## 新功能描述
mp html 不支持svg里的响应标签比如rect、foreignObject、animate
## 应用场景
渲染svg图片增加点击处理渲染图片

**Comment by jin-yufeng** [comment]
小程序本身不支持 `svg`，目前转为 `base64` 的 `img` 显示，但是点击动画等无法实现
