### ISSUE TITLE
快手小程序图片展示有问题

### ISSUE THREAD

**Issue by bequiet201314** [jin-yufeng/mp-html#571]
## 使用环境  

uniapp 快手小程序 1.60.8
## 问题描述  

快手小程序图片展示有问题
![image](https://github.com/jin-yufeng/mp-html/assets/50263229/4e35c8ad-ba47-42dc-a137-a699c6cfc80d)
## 复现方式  

```html
<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_1.jpg" /></p>
<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_2.jpg" /></p>
<p>1231243213y612u73612783612783618</p>
<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_3.jpg" /></p>
```

**Comment by bequiet201314** [comment]
`<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_1.jpg" /></p>
<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_2.jpg" /></p>
<p>1231243213y612u73612783612783618</p>
<p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_3.jpg" /></p>`

**Comment by ljt990218** [comment]
亲测 把 `style="width: 100%"`  替换成 `style="width: 100%; height:100%"` 显示没问题，暂时可以先这样解决。如果你怕替换掉其他标签的样式，也可以匹配 `<img style="width: 100%"` 替换成 `<img style="width: 100%; height:100%"`

**Comment by ljt990218** [comment]
> ## 使用环境
> uniapp 快手小程序 1.60.8
> 
> ## 问题描述
> 快手小程序图片展示有问题 ![image](https://private-user-images.githubusercontent.com/50263229/295076827-4e35c8ad-ba47-42dc-a137-a699c6cfc80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzMxODUsIm5iZiI6MTcwNDc3Mjg4NSwicGF0aCI6Ii81MDI2MzIyOS8yOTUwNzY4MjctNGUzNWM4YWQtYmE0Ny00MmRjLWExMzctYTY5OWM2Y2ZjODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA0MDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDBjNGYyMzYyYTJjNWUwZWYyMmYxZjRiYjhlZTAxZGFjZWFkZTg4ZTBhN2QwYjQwZmFiMzkxOGI0YmJmM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIj6HNH4WhoXBaGtZq7NH7jhitjcMIa6IGKM8med-TU)
> 
> ## 复现方式
> ```
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_1.jpg" /></p>
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_2.jpg" /></p>
> <p>1231243213y612u73612783612783618</p>
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_3.jpg" /></p>
> ```
亲测 把 style="width: 100%" 替换成 style="width: 100%; height:100%" 显示没问题，暂时可以先这样解决。如果你怕替换掉其他标签的样式，也可以匹配 <img style="width: 100%" 替换成 <img style="width: 100%; height:100%"

**Comment by ljt990218** [comment]
> ## 使用环境
> uniapp 快手小程序 1.60.8
> 
> ## 问题描述
> 快手小程序图片展示有问题 ![image](https://private-user-images.githubusercontent.com/50263229/295076827-4e35c8ad-ba47-42dc-a137-a699c6cfc80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzMyNDYsIm5iZiI6MTcwNDc3Mjk0NiwicGF0aCI6Ii81MDI2MzIyOS8yOTUwNzY4MjctNGUzNWM4YWQtYmE0Ny00MmRjLWExMzctYTY5OWM2Y2ZjODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA0MDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NTllMTZhOWUzZDlkZjJlYmEyZDhiYjdlNDQ3Mzk4Mjg0N2Y5ZTU4NTMyNzc1YmI5YWJlYjVlOTkzYjBhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-K3V9vEDCScX_3YSTqD49iK4F1WVv7_sL7MiFDFfIA)
> 
> ## 复现方式
> ```
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_1.jpg" /></p>
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_2.jpg" /></p>
> <p>1231243213y612u73612783612783618</p>
> <p><img style="width: 100%" src="https://cdn-document-huoshan.orange-classroom.com/document/20230314092354_2339329481678757034234_3.jpg" /></p>
> ```

亲测 把 `style="width: 100%"` 替换成 `style="width: 100%; height:100%"` 显示没问题，暂时可以先这样解决。如果你怕替换掉其他标签的样式，也可以匹配 `<img style="width: 100%"` 替换成 `<img style="width: 100%; height:100%"`
