### ISSUE TITLE
markdown和latex可以一起渲染吗

### ISSUE THREAD

**Issue by typing233** [jin-yufeng/mp-html#576]
## 问题描述  
在模板区域写：
<view>
	<mp-html markdown :content="html"/>
</view>
# 报错
会提示这个错误：22:36:33.544 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "时" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.544 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "才" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.546 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "产" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.549 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "生" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.550 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "溢" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.550 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "出" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.550 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "可" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.551 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "以" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.551 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "判" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.551 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "断" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.551 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "溢" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "出" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "标" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "志" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "为" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "。" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "同" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
22:36:33.552 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "时" used in math mode [unicodeTextInMathMode] at uni_modules/mp-html/components/mp-html/latex/katex.min.js:1
# 修正
如果去掉markdown 就正常了， 所以想知道markdown与latex公式可以一起渲染吗
<mp-html :content="html"/>

**Comment by typing233** [comment]
<mp-html markdown :content="html"/>

**Comment by gitgoready** [comment]
请问这个问题解决了吗？  测试markdown里含 latex 格式 ，markdown显示正常，latex不处理：

比如如下文本：
解三角形的应用(测量距离)是高中数学中解三角形这一章中的一个重难点，它将三角形的理论知识与实际问题相结合，解决实际生活中的测量距离问题。下面我将从以下几个方面来讲解这个知识点：

### 1. 基本概念和原理
解三角形的应用(测量距离)主要利用正弦定理和余弦定理来解决实际问题。正弦定理和余弦定理是解三角形的基本工具，它们分别描述了三角形的边和角之间的关系。

- **正弦定理**：在任意三角形中，各边和它所对角的正弦的比相等，即 \(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)。
- **余弦定理**：在任意三角形中，任何一边的平方等于其他两边的平方和减去这两边与它们夹角的余弦的积的两倍，即 \(c^2 = a^2 + b^2 - 2ab \cos C\)。

### 2. 常见问题类型
在测量距离的应用中，常见的问题类型包括：

- **测量不可到达的两点之间的距离**：例如测量河宽、测量两个山峰之间的距离等。
- **测量底部不可到达的物体的高度**：例如测量山高、测量 building 的高度等。

### 3. 解决问题的步骤
解决解三角形的应用(测量距离)问题的一般步骤如下：

1. **分析问题**：理解问题，确定已知条件和需要求解的未知量。
2. **建立三角形模型**：根据问题，建立一个或多个三角形，将实际问题转化为数学问题。
3. **应用正弦定理或余弦定理**：根据已知条件，选择 appropriate 的定理来解三角形，求出未知量。
4. **计算**：进行计算，得出结果。
5. **检验**：检查结果是否符合实际，是否满足问题的条件。

### 4. 例题
为了更好地理解，我们来看一个例题：

**例题**：如图，为了测量河宽，选择河对岸的两个点 \(A\) 和 \(B\)，在河这边的点 \(C\) 处测得 \(\angle ACB = 75^\circ\)，在点 \(D\) 处测得 \(\angle ADB = 30^\circ\)，且 \(CD = 100\) 米， \( \angle BCD = 45^\circ\)。求河宽 \(AB\)。

**解**：
1. **分析问题**：已知 \(\angle ACB = 75^\circ\)，\(\angle ADB = 30^\circ\)，\(\angle BCD = 45^\circ\)， \(CD = 100\) 米，需要求河宽 \(AB\)。
2. **建立三角形模型**：建立 \(\triangle ACD\) 和 \(\triangle BCD\)。
3. **应用正弦定理**：
   - 在 \(\triangle BCD\) 中，由正弦定理得 \(\frac{BD}{\sin 45^\circ} = \frac{CD}{\sin \angle BDC}\)。因为 \(\angle BDC = 180^\circ - 30^\circ = 150^\circ\)，所以 \(\sin \angle BDC = \sin 150^\circ = \frac{1}{2}\)。因此，\(\frac{BD}{\frac{\sqrt{2}}{2}} = \frac{100}{\frac{1}{2}}\)，解得 \(BD = 100\sqrt{2}\)。
   - 在 \(\triangle ACD\) 中，由正弦定理得 \(\frac{AD}{\sin 45^\circ} = \frac{CD}{\sin \angle ADC}\)。因为 \(\angle ADC = 180^\circ - 75^\circ = 105^\circ\)，所以 \(\sin \angle ADC = \sin 105^\circ = \sin 75^\circ = \frac{\sqrt{6} + \sqrt{2}}{4}\)。因此，\(\frac{AD}{\frac{\sqrt{2}}{2}} = \frac{100}{\frac{\sqrt{6} + \sqrt{2}}{4}}\)，解得 \(AD = \frac{100\sqrt{2} \cdot 4}{\sqrt{6} + \sqrt{2}} = \frac{400\sqrt{2}}{\sqrt{6} + \sqrt{2}} \cdot \frac{\sqrt{6} - \sqrt{2}}{\sqrt{6} - \sqrt{2}} = \frac{400\sqrt{2}(\sqrt{6} - \sqrt{2})}{4} = 100(\sqrt{12} - 2) = 200\sqrt{3} - 200\)。
4. **计算**：在 \(\triangle ABD\) 中，由余弦定理得 \(AB^2 = AD^2 + BD^2 - 2 \cdot AD \cdot BD \cdot \cos 30^\circ\)。代入 \(AD = 200\sqrt{3} - 200\)， \(BD = 100\sqrt{2}\)， \(\cos 30^\circ = \frac{\sqrt{3}}{2}\)，得 \(AB^2 = (200\sqrt{3} - 200)^2 + (100\sqrt{2})^2 - 2 \cdot (200\sqrt{3} - 200) \cdot 100\sqrt{2} \cdot \frac{\sqrt{3}}{2}\)。经过计算，得 \(AB = 100\sqrt{6}\)。

因此，河宽 \(AB\) 为 \(\boxed{100\sqrt{6}}\) 米。
