### ISSUE TITLE
希望公式渲染支持双美元符号（公式块），现在仅支持单美元符号（内联公式）

### ISSUE THREAD

**Issue by Pooooooocky** [jin-yufeng/mp-html#582]
## 新功能描述
希望公式渲染支持双美元符号（公式块），现在仅支持单美元符号（内联公式）
希望优化对长、复杂公式的支持

## 应用场景
直接夹在并显示md文档的所有内容，包括长公式、短公式，这样就可以直接渲染不需要做二次处理

**Comment by aasmn** [comment]
### 3. 矩阵  
$$  
A = \begin{pmatrix}  
a_{11} & a_{12} & \cdots & a_{1n} \\  
a_{21} & a_{22} & \cdots & a_{2n} \\  
\vdots & \vdots & \ddots & \vdots \\  
a_{m1} & a_{m2} & \cdots & a_{mn}  
\end{pmatrix}  
$$  
  
### 4. 欧拉公式  
$$  
e^{i\theta} = \cos\theta + i\sin\theta  
$$  
  
### 5. 牛顿第二定律  
$$  
F = ma  
$$  
这种格式还是渲染不了啊

**Comment by aasmn** [comment]
![Image](https://github.com/user-attachments/assets/e9c2b758-4b80-4863-93cf-5c1ad70cc158)
