### ISSUE TITLE
mp-html组件linktap跳转两次

### ISSUE THREAD

**Issue by HUI19930103** [jin-yufeng/mp-html#589]
## 使用环境  
uniapp编译的小程序运行在安卓微信端

## 问题描述  
使用linktap方法，重新定义跳转，运行在安卓微信内的小程序会跳转两次，方法只执行一次

## 复现方式  

`<mp-html class="ql-editor" @linktap="linktap" v-if="item.content" :content="item.content" />`

```
linktap(e) {
                const { href = '' } = e || {};

                if (href) {
                    this.jump({
                        url: href
                    })
                }
            }
```

**Comment by jin-yufeng** [comment]
组件内置的跳转也跳转了一次吧，这个 href 是内部链接吗，内部链接自动跳转，不需要另外定义
