### ISSUE TITLE
数学公式渲染错误

### ISSUE THREAD

**Issue by endOver** [jin-yufeng/mp-html#590]
设 $f(x)=\left\{\begin{array}{ll}\ln \sqrt{x}, &amp; x \geqslant 1, \\ 2 x-1, &amp; x<1 .\end{array}\right.$ 求 $f[f(x)]$

设 $f(x)=\\left\\{\\begin{array}{cl}<br>(\\cos x)^{\\frac{2}{x\\arctan x}}, &amp; x \\neq 0, \\\\<br>a, &amp; x=0 .<br>\\end{array}\\right.$在 $x=0$ 处连续, 则 $a=$</p>

## 问题描述  
![66666666666](https://github.com/jin-yufeng/mp-html/assets/19380381/cf91a4e5-d990-4de5-b5e7-401e5f548632)

**Comment by jin-yufeng** [comment]
没用转义符吧

**Comment by endOver** [comment]
> 所有者

哪个地方没用？

**Comment by jin-yufeng** [comment]
`\` 是转义符，写在字符串里 `\` 要写作 `\\`

**Comment by endOver** [comment]
设 $f(x)=\\left\\{\\begin{array}{cl}<br>(\\cos x)^{\\frac{2}{x\\arctan x}}, &amp; x \\neq 0, \\\\<br>a, &amp; x=0 .<br>\\end{array}\\right.$在 $x=0$ 处连续, 则 $a=$</p>

**Comment by endOver** [comment]
设 $f(x)=\\left\\{\\begin{array}{cl}<br>(\\cos x)^{\\frac{2}{x\\arctan x}}, &amp; x \\neq 0, \\\\<br>a, &amp; x=0 .<br>\\end{array}\\right.$在 $x=0$ 处连续, 则 $a=$</p>
