### ISSUE TITLE
latex 公式显示模式，\[...\]，插值\text{应纳税所得额} 

### ISSUE THREAD

**Issue by mylittlekingkong** [jin-yufeng/mp-html#606]
## 使用环境  

微信小程序，基础库版本2.20.2

## 问题描述  

let str = `\[ \text{应纳税所得额} = \text{累计税前工资收入} - \text{累计五险一金（个人缴纳部分）} - \text{累计专项附加扣除} - \text{累计减除费用} \]
\[ \text{应纳税额} = \text{应纳税所得额} \times \text{预扣税率} - \text{速算扣除数} \]
\[ \text{当月应纳税额} = \text{应纳税额} - \text{累计已缴纳税额} \]`
latex插件，对这种显示模式，\[...\]，插值\text{} ，语法不支持

## 复现方式  

let str = `\[ \text{应纳税所得额} = \text{累计税前工资收入} - \text{累计五险一金（个人缴纳部分）} - \text{累计专项附加扣除} - \text{累计减除费用} \]
\[ \text{应纳税额} = \text{应纳税所得额} \times \text{预扣税率} - \text{速算扣除数} \]
\[ \text{当月应纳税额} = \text{应纳税额} - \text{累计已缴纳税额} \]`

**Comment by drucker2310** [comment]
字符串加个string.raw

**Comment by jin-yufeng** [comment]
公式要用 $$包裹，\text{}是支持的，还要注意转义符

**Comment by lsm1103** [comment]
你们显示latex的分数、根号会有问题吗？
![image](https://github.com/user-attachments/assets/0cdc016f-1361-4da4-9d94-2e3338c21ed9)
